# Generated by Django 5.2 on 2025-07-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignmentauditlog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.module'),
        ),
        migrations.AddField(
            model_name='roleassignmentauditlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='roleassignmentauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='core.module'),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='core.project'),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='roleassignmentauditlog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='scopedrole',
            unique_together={('user', 'group', 'tenant', 'project', 'module')},
        ),
    ]
