# Generated by Django 5.2.3 on 2026-07-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_tenant'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_project_unique_together_remove_project_tenant'),
        ('emissions', '0003_remove_reportingperiod_emissions_r_tenant__54a7a7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignmentauditlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='scopedrole',
            unique_together={('user', 'group', 'project', 'module')},
        ),
        migrations.RemoveField(
            model_name='scopedrole',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
