# Generated by Django 5.2.3 on 2026-07-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_roleassignmentauditlog_tenant_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_project_unique_together_remove_project_tenant'),
        ('mdm', '0002_orgunit'),
    ]

    operations = [
        # Step 1: drop old unique_together that references project (still in DB)
        migrations.AlterUniqueTogether(
            name='scopedrole',
            unique_together=set(),
        ),
        # Step 2: add org_unit field
        migrations.AddField(
            model_name='scopedrole',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='mdm.orgunit'),
        ),
        # Step 3: remove project field
        migrations.RemoveField(
            model_name='scopedrole',
            name='project',
        ),
        # Step 4: set new unique_together with org_unit
        migrations.AlterUniqueTogether(
            name='scopedrole',
            unique_together={('user', 'group', 'org_unit', 'module')},
        ),
        # audit log: remove project, add org_unit
        migrations.RemoveField(
            model_name='roleassignmentauditlog',
            name='project',
        ),
        migrations.AddField(
            model_name='roleassignmentauditlog',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit'),
        ),
    ]
