# Generated by Django 5.2.3 on 2026-07-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_roleassignmentauditlog_project_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('platform', 'Platform'), ('app', 'App')], default='app', max_length=20)),
                ('app_id', models.CharField(blank=True, default='', max_length=50)),
                ('manifest_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_scoped', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Metadata',
                'verbose_name_plural': 'Group Metadata',
            },
        ),
    ]
