# Generated by Django 5.2.3 on 2026-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_platformappconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('anymail.backends.brevo.EmailBackend', 'Brevo (Sendinblue)'), ('anymail.backends.sendgrid.EmailBackend', 'SendGrid'), ('anymail.backends.mailgun.EmailBackend', 'Mailgun'), ('anymail.backends.amazon_ses.EmailBackend', 'Amazon SES'), ('anymail.backends.resend.EmailBackend', 'Resend'), ('django.core.mail.backends.smtp.EmailBackend', 'Generic SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console (dev only)')], default='django.core.mail.backends.console.EmailBackend', help_text='Email backend provider', max_length=100)),
                ('host', models.CharField(blank=True, default='', help_text='SMTP host', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP port (587 TLS, 465 SSL, 25)')),
                ('username', models.CharField(blank=True, default='', help_text='SMTP username or API key', max_length=255)),
                ('password', models.CharField(blank=True, default='', help_text='SMTP password or API key', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use STARTTLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL (port 465)')),
                ('from_email', models.EmailField(default='noreply@carbon.clearturn.tech', help_text='Default From: address', max_length=255)),
                ('from_name', models.CharField(blank=True, default='Carbon Data Trust', help_text='Display name for From: header', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Enable outgoing email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.IntegerField(default=12, help_text='Minimum password length')),
                ('require_uppercase', models.BooleanField(default=True, help_text='Require at least one uppercase letter')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Require at least one lowercase letter')),
                ('require_number', models.BooleanField(default=True, help_text='Require at least one digit')),
                ('require_special', models.BooleanField(default=True, help_text='Require at least one special character')),
                ('max_age_days', models.IntegerField(default=90, help_text='Force password change after N days (0 = never)')),
                ('prevent_reuse_n', models.IntegerField(default=5, help_text='Prevent reuse of last N passwords (0 = unlimited)')),
                ('lockout_after_n', models.IntegerField(default=5, help_text='Lock account after N failed attempts (0 = never)')),
                ('lockout_minutes', models.IntegerField(default=15, help_text='Auto-unlock after N minutes')),
                ('password_reset_timeout_hours', models.IntegerField(default=24, help_text='Reset token expiry in hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Password Policy',
                'verbose_name_plural': 'Password Policy',
            },
        ),
    ]
