# Generated by Django 5.2.3 on 2026-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_phase1_1_email_password_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.IntegerField(default=50, help_text='Default items per page')),
                ('max_page_size', models.IntegerField(default=200, help_text='Maximum allowed items per page')),
                ('enable_pagination', models.BooleanField(default=True, help_text='Global pagination toggle')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily (2 AM)'), ('twice_daily', 'Twice Daily (2 AM + 2 PM)'), ('hourly', 'Hourly'), ('manual', 'Manual Only')], default='daily', max_length=20)),
                ('retention_days', models.IntegerField(default=30, help_text='Auto-delete backups older than N days')),
                ('s3_bucket', models.CharField(blank=True, default='', help_text='Optional S3 bucket for offsite storage', max_length=255)),
                ('s3_path', models.CharField(blank=True, default='', help_text='S3 key prefix, e.g. carbon-backups/', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_backup_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='running', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text='File path or S3 URI', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10)),
                ('retention_days', models.IntegerField(default=90, help_text='Auto-delete request logs older than N days')),
                ('json_format', models.BooleanField(default=True, help_text='Use JSON structured logging')),
                ('db_log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='ERROR', help_text='Min level for DB logging (prevents fillup)', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Configuration',
                'verbose_name_plural': 'Log Configuration',
            },
        ),
    ]
