# Generated by Django 5.2.3 on 2026-08-09 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phase1_2_5_backup_log_api_env'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('both', 'Both')], default='in_app', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dq_violation', 'DQ Violation'), ('dq_rule_failure', 'DQ Rule Execution Failure'), ('password_reset', 'Password Reset Request'), ('backup_failure', 'Backup Failure'), ('backup_success', 'Backup Success'), ('import_complete', 'Import Complete'), ('import_failure', 'Import Failure'), ('system_alert', 'System Alert')], max_length=32)),
                ('min_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_target', models.ForeignKey(blank=True, help_text='Notify all users in this group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'ordering': ['event_type', '-min_severity'],
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('system', 'System'), ('dq_violation', 'DQ Violation'), ('security', 'Security'), ('workflow', 'Workflow'), ('backup', 'Backup'), ('import', 'Import'), ('other', 'Other')], default='system', max_length=32)),
                ('link', models.CharField(blank=True, default='', help_text='Optional deep-link URL', max_length=512)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_b7a080_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_us_user_id_e7dbe1_idx')],
            },
        ),
    ]
