# Generated by Django 5.2.3 on 2026-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_phase1_6_notification_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('dq_violation', 'DQ Violation'), ('dq_rule_failure', 'DQ Rule Execution Failure'), ('password_reset', 'Password Reset Request'), ('backup_failure', 'Backup Failure'), ('backup_success', 'Backup Success'), ('import_complete', 'Import Complete'), ('import_failure', 'Import Failure'), ('system_alert', 'System Alert'), ('freshness_violation', 'Data Freshness Violation'), ('schema_change', 'Schema Change Detected')], max_length=32),
        ),
    ]
