# Generated by Django 5.2.3 on 2026-08-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_phase10_rebrand_from_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('Africa/Cairo', 'Africa/Cairo (Egypt, UTC+2)'), ('UTC', 'UTC (Coordinated Universal Time)'), ('Europe/London', 'Europe/London (UTC+0/+1)'), ('Europe/Berlin', 'Europe/Berlin (CET, UTC+1/+2)'), ('Asia/Riyadh', 'Asia/Riyadh (UTC+3)'), ('Asia/Dubai', 'Asia/Dubai (UTC+4)'), ('America/New_York', 'America/New_York (UTC-5/-4)')], default='Africa/Cairo', help_text='Display timezone for schedule previews and timestamps.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Configuration',
                'verbose_name_plural': 'General Configuration',
            },
        ),
    ]
