# Generated by Django 5.2.3 on 2026-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_generalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', help_text='UI language preference (en/ar).', max_length=10),
        ),
    ]
