# Generated by Django 5.2.3 on 2026-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0002_orgunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='org_type',
            field=models.CharField(choices=[('university', 'University'), ('campus', 'Campus'), ('college', 'College'), ('department', 'Department'), ('division', 'Division'), ('team', 'Team'), ('facility', 'Facility'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
