# Generated by GitHub Copilot
from django.db import migrations, models


def generate_default_lifecycle(apps, schema_editor):
    ReferenceSet = apps.get_model('mdm', 'ReferenceSet')
    ReferenceSet.objects.filter(lifecycle_state__isnull=True).update(lifecycle_state='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_alter_orgunit_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceset',
            name='lifecycle_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20, help_text='Lifecycle state of this reference set'),
        ),
        migrations.RunPython(generate_default_lifecycle, reverse_code=migrations.RunPython.noop),
    ]
