# Generated by Django 5.2.3 on 2026-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0005_add_performance_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='referenceset',
            name='refset_active_domain_idx',
        ),
        migrations.RemoveIndex(
            model_name='referencevalue',
            name='refval_set_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='referencevalue',
            name='refval_validity_idx',
        ),
    ]
