# Generated by Django 5.2.3 on 2026-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_remove_referenceset_refset_active_domain_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='manager_employee_id',
            field=models.PositiveIntegerField(blank=True, help_text='Soft ref to people.Employee (RULE_3: no cross-app FK from core). Who runs this unit.', null=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='org_type',
            field=models.CharField(choices=[('university', 'University'), ('campus', 'Campus'), ('college', 'College'), ('department', 'Department'), ('division', 'Division'), ('team', 'Team'), ('facility', 'Facility'), ('other', 'Other'), ('company', 'Company'), ('section', 'Section'), ('crew', 'Crew'), ('base', 'Base'), ('yard', 'Yard'), ('store', 'Store'), ('cost_center', 'Cost Center')], default='other', max_length=20),
        ),
    ]
