# Generated by Django 5.2.3 on 2026-09-30 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=40)),
                ('lesson_id', models.CharField(max_length=24)),
                ('lesson_version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('offered', 'Offered'), ('started', 'Started'), ('done', 'Done'), ('snoozed', 'Snoozed')], default='offered', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, choices=[('host_row', 'Host row'), ('host_state', 'Host state'), ('answer', 'Answer')], default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'pack_id', 'state'], name='guide_guide_user_id_27a2ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'pack_id', 'lesson_id'), name='uniq_guide_user_pack_lesson')],
            },
        ),
    ]
