# Generated by Django 5.2.3 on 2026-09-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprogress',
            name='step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Coach card 0–3 (know, do, check, after). Last place the caller stopped.'),
        ),
    ]
