# Generated by Django 5.2.3 on 2026-07-20 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('module_delete', 'Module Delete Policy'), ('table_delete', 'Table Delete Policy'), ('module_update', 'Module Update Policy'), ('table_update', 'Table Update Policy')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Policy configuration: rules, checks, thresholds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governance Policy',
                'verbose_name_plural': 'Governance Policies',
                'ordering': ['policy_type'],
            },
        ),
    ]
