# Generated by Django 5.2.3 on 2026-07-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_governancepolicy'),
        ('mdm', '0003_alter_orgunit_org_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governancepolicy',
            options={'ordering': ['policy_type', 'scope_type'], 'verbose_name': 'Governance Policy', 'verbose_name_plural': 'Governance Policies'},
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Apply only to assets in this data domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.datadomain'),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='emission_scope',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')], help_text='Apply only to modules in this emission scope', null=True),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='error_message',
            field=models.TextField(default='This action is blocked by governance policy.', help_text='Custom error message shown to users when policy blocks an action'),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='Apply only to this organization unit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit'),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='remediation_steps',
            field=models.JSONField(default=list, help_text='List of steps user should take to resolve the issue'),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global - All'), ('scope', 'Emission Scope'), ('org_unit', 'Organization Unit'), ('domain', 'Data Domain')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='governancepolicy',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this policy has blocked an action'),
        ),
        migrations.AlterField(
            model_name='governancepolicy',
            name='config',
            field=models.JSONField(default=dict, help_text='Policy rules: check_row_count, max_rows, block_with_dependencies, etc.'),
        ),
        migrations.AlterField(
            model_name='governancepolicy',
            name='policy_type',
            field=models.CharField(choices=[('module_delete', 'Module Delete Policy'), ('table_delete', 'Table Delete Policy'), ('module_update', 'Module Update Policy'), ('table_update', 'Table Update Policy')], max_length=40),
        ),
    ]
