# Generated by Django 5.2.3 on 2026-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_governancepolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
