# Generated by Django 5.2.3 on 2026-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_performance_indices'),
        ('catalog', '0004_assetprofile_is_active'),
    ]

    operations = [
    ]
