# Generated by Django 5.2.3 on 2026-07-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20260729_0810'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetprofile',
            name='assetprof_active_domain_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetprofile',
            name='assetprof_quality_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceevent',
            name='govevent_time_type_idx',
        ),
    ]
