# Generated by Django 5.2.3 on 2026-08-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_adopt_datasets'),
        ('dataschema', '0008_datarow_row_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('transform', 'Transform'), ('copy', 'Copy'), ('aggregate', 'Aggregate'), ('dependency', 'Dependency')], default='dependency', max_length=20)),
                ('transform_description', models.TextField(blank=True, help_text='Human-readable description of the transformation (e.g., "SUM(amount) grouped by date")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_field', models.ForeignKey(blank=True, help_text='Optional: specific source column', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_outgoing', to='dataschema.datafield')),
                ('source_table', models.ForeignKey(help_text='Source table in the lineage relationship', on_delete=django.db.models.deletion.CASCADE, related_name='lineage_outgoing', to='dataschema.datatable')),
                ('target_field', models.ForeignKey(blank=True, help_text='Optional: specific target column', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineage_incoming', to='dataschema.datafield')),
                ('target_table', models.ForeignKey(help_text='Target (destination) table in the lineage relationship', on_delete=django.db.models.deletion.CASCADE, related_name='lineage_incoming', to='dataschema.datatable')),
            ],
            options={
                'indexes': [models.Index(fields=['source_table'], name='catalog_lin_source__3270d6_idx'), models.Index(fields=['target_table'], name='catalog_lin_target__41bcc8_idx')],
                'unique_together': {('source_table', 'target_table', 'edge_type')},
            },
        ),
    ]
