# Generated by Django 5.2.3 on 2026-08-26 11:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_lineageedge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datadomain',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='datadomain',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='datadomain_search_vector_idx'),
        ),
    ]
