# Generated by Django 5.2.3 on 2026-08-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_notes_comments_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='catalog.note')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='catalog_not_entity__4bb8fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'entity_type', 'entity_id'), name='uniq_note_anchor')],
            },
        ),
    ]
