# Generated by Django 5.2.3 on 2026-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_noteanchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceevent',
            name='action',
            field=models.CharField(max_length=40),
        ),
    ]
