# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0002_orgunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text="Stable slug identifier, e.g. 'kw-eosi-accrual'", max_length=120)),
                ('version', models.CharField(help_text="Version string, e.g. '2026.1'", max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('jurisdiction', models.CharField(default='KW', max_length=10)),
                ('category', models.CharField(choices=[('leave', 'Leave'), ('eosi', 'EOSI'), ('gosi', 'GOSI'), ('wps', 'WPS'), ('overtime', 'Overtime'), ('payroll', 'Payroll'), ('other', 'Other')], max_length=20)),
                ('effective_date', models.DateField(help_text='Date the rule becomes effective')),
                ('formula_ref', models.CharField(blank=True, help_text="e.g. 'KLL Art. 51'", max_length=200)),
                ('source_citation', models.TextField(blank=True, help_text='Authoritative citation — EMPTY until sourced')),
                ('inputs_schema', models.JSONField(blank=True, default=dict)),
                ('is_authoritative', models.BooleanField(default=False, help_text='False until sourced from KLL / PIFSS / WPS')),
                ('provenance', models.JSONField(blank=True, help_text='Source doc / URL / reviewed-by — null until sourced', null=True)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'ordering': ['category', 'rule_id', '-effective_date'],
                'unique_together': {('rule_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=3, max_digits=14)),
                ('join_date', models.DateField(help_text='Service start date')),
                ('rotation', models.CharField(blank=True, help_text="Config label only (e.g. '1/1'), NOT calculation logic", max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_unit', models.ForeignKey(help_text='Owning organisational unit (RULE_12 org-scoping)', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='mdm.orgunit')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_no'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('validated', 'Validated'), ('committed', 'Committed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('org_unit', models.ForeignKey(help_text='Owning organisational unit (RULE_12 org-scoping)', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='mdm.orgunit')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(help_text='gross | basic | overtime | leave_pay | eosi_accrual | gosi | deduction | …', max_length=40)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rule_id', models.CharField(max_length=120)),
                ('rule_version', models.CharField(max_length=40)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Exact inputs that produced the amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='people.payrollrun')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='people.employee')),
            ],
            options={
                'verbose_name': 'Payslip Line',
                'verbose_name_plural': 'Payslip Lines',
                'ordering': ['id'],
            },
        ),
    ]
