# Generated by Django 5.2.3 on 2026-08-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_remove_referenceset_refset_active_domain_idx_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('vehicle', 'Vehicle'), ('medical', 'Medical'), ('school', 'School'), ('tickets', 'Tickets'), ('other', 'Other')], max_length=20)),
                ('is_eosi_base', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Benefit Type',
                'verbose_name_plural': 'Benefit Types',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('permission_type', models.CharField(max_length=64)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='people.employee')),
            ],
            options={
                'verbose_name': 'Attendance Permission',
                'verbose_name_plural': 'Attendance Permissions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, max_length=128)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='people.employee')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_benefits', to='people.benefittype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='people.employee')),
            ],
            options={
                'verbose_name': 'Employee Benefit',
                'verbose_name_plural': 'Employee Benefits',
                'ordering': ['employee', 'benefit_type'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('calendar_split', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='people.employee')),
            ],
            options={
                'verbose_name': 'Leave Record',
                'verbose_name_plural': 'Leave Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=40)),
                ('principal', models.DecimalField(decimal_places=3, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='people.employee')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('is_management', models.BooleanField(default=False)),
                ('org_unit', models.ForeignKey(help_text='Owning organisational unit (RULE_12 org-scoping)', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='mdm.orgunit')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='people.position')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['org_unit', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RotationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_schedules', to='people.employee')),
            ],
            options={
                'verbose_name': 'Rotation Schedule',
                'verbose_name_plural': 'Rotation Schedules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('permission', 'Permission')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('leave_type', models.CharField(max_length=40)),
                ('entitled_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='people.employee')),
            ],
            options={
                'verbose_name': 'Leave Entitlement',
                'verbose_name_plural': 'Leave Entitlements',
                'ordering': ['employee', 'year', 'leave_type'],
                'unique_together': {('employee', 'year', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('principal_portion', models.DecimalField(decimal_places=3, max_digits=14)),
                ('interest_portion', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='people.loan')),
            ],
            options={
                'verbose_name': 'Loan Installment',
                'verbose_name_plural': 'Loan Installments',
                'ordering': ['installment_no'],
                'unique_together': {('loan', 'installment_no')},
            },
        ),
    ]
