# Generated by Django 5.2.3 on 2026-08-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0012_datafield_masking_strategy'),
        ('people', '0002_benefittype_attendancepermission_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='source_row',
            field=models.ForeignKey(blank=True, help_text='Source governed measurement row (ADR 0025 lineage seam)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_attendance_records', to='dataschema.datarow'),
        ),
    ]
