# Generated by Django 5.2.3 on 2026-08-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_attendancerecord_source_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRunValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=200)),
                ('passed', models.BooleanField()),
                ('checked', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('sample_failures', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='people.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Run Validation',
                'verbose_name_plural': 'Payroll Run Validations',
                'ordering': ['-created_at'],
            },
        ),
    ]
