# Generated by Django 5.2.3 on 2026-09-01 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_payrollrunvalidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Employee', 'Employee'), ('Position', 'Position')], db_index=True, max_length=20)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('event_kind', models.CharField(choices=[('hired', 'Hired'), ('transferred', 'Transferred'), ('promoted', 'Promoted'), ('salary_change', 'Salary Change'), ('grade_change', 'Grade Change'), ('contract_renewed', 'Contract Renewed'), ('rotation_changed', 'Rotation Changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('profile_updated', 'Profile Updated'), ('position_opened', 'Position Opened'), ('position_filled', 'Position Filled'), ('position_frozen', 'Position Frozen'), ('position_closed', 'Position Closed')], db_index=True, max_length=32)),
                ('effective_date', models.DateField(db_index=True, help_text='Real-world date the change took effect (drives EOSI/KPIs)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the change was entered into the system')),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-recorded_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'effective_date'], name='people_pers_entity__efbbd7_idx'), models.Index(fields=['event_kind', 'effective_date'], name='people_pers_event_k_8cfc67_idx')],
            },
        ),
    ]
