# Generated by Django 5.2.3 on 2026-09-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_personnelevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='civil_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Civil ID (Kuwait) — plain text, no validation of checksum', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type_code',
            field=models.CharField(blank=True, default='', help_text="Code from ReferenceSet 'contract_type' (governed enum)", max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type_code',
            field=models.CharField(blank=True, default='', help_text="Code from ReferenceSet 'employment_type' (governed enum)", max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, default='', help_text="Free text (e.g. 'male'/'female'); NOT a governed enum", max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='kuwaitization',
            field=models.BooleanField(default=False, help_text='Kuwaiti national (nationalization target flag)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager (self FK; RULE_3 soft ref to Employee)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='people.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_ar_family',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_ar_given',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en_family',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en_given',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality_code',
            field=models.CharField(blank=True, default='', help_text="Code from ReferenceSet 'nationality' (governed enum)", max_length=40),
        ),
    ]
