# Generated by Django 5.2.3 on 2026-09-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_employee_civil_id_employee_contract_type_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Current single position (same-app FK; incumbent resolution)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incumbents', to='people.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='fte',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='position',
            name='job_family_code',
            field=models.CharField(blank=True, default='', help_text="Code from ReferenceSet 'job_family' (governed enum)", max_length=40),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('open', 'Open'), ('filled', 'Filled'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='filled', max_length=20),
        ),
    ]
