# Generated by Django 5.2.3 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_employee_position_position_fte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPEG/PNG ≤2 MB)', null=True, upload_to='people/photos/'),
        ),
    ]
