# Generated by Django 5.2.3 on 2026-09-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0008_add_employee_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=10)),
                ('category', models.CharField(blank=True, help_text="Code from ReferenceSet 'compensation_category'", max_length=64)),
                ('is_eosi_base', models.BooleanField(default=False, help_text='Included in EOSI/gratuity base')),
                ('is_gosi_base', models.BooleanField(default=False, help_text='Included in GOSI contribution base')),
                ('is_wps_relevant', models.BooleanField(default=True, help_text='Appears in WPS file')),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_variable', models.BooleanField(default=False, help_text='Variable each month (overtime, commission)')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('governing_rule', models.ForeignKey(blank=True, help_text='ComplianceRule that sets limits/rates for this component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governed_components', to='people.compliancerule')),
            ],
            options={
                'verbose_name': 'Compensation Component',
                'verbose_name_plural': 'Compensation Components',
                'ordering': ['direction', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompensationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_grade_code', models.CharField(blank=True, help_text="Code from ReferenceSet 'pay_grade' (blank = all grades)", max_length=40)),
                ('job_family_code', models.CharField(blank=True, help_text="Code from ReferenceSet 'job_family' (blank = all families)", max_length=40)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('currency', models.CharField(default='KWD', max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_rows', to='people.compensationcomponent')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Null = global plan row (applies to all org units)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensation_plan_rows', to='mdm.orgunit')),
            ],
            options={
                'verbose_name': 'Compensation Plan Row',
                'verbose_name_plural': 'Compensation Plan',
                'ordering': ['pay_grade_code', 'component', '-effective_start'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('currency', models.CharField(default='KWD', max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, help_text='Null = open-ended (current)', null=True)),
                ('reason_note', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_lines', to='people.compensationcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_lines', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_lines', to='people.employee')),
                ('reason_event', models.ForeignKey(blank=True, help_text='PersonnelEvent that triggered this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_changes', to='people.personnelevent')),
                ('source_plan', models.ForeignKey(blank=True, help_text='CompensationPlan row this was inherited from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_lines', to='people.compensationplan')),
                ('source_rule', models.ForeignKey(blank=True, help_text='ComplianceRule that produced this amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_lines', to='people.compliancerule')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compensation_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Compensation Line',
                'verbose_name_plural': 'Employee Compensation Ledger',
                'ordering': ['employee', 'component', '-effective_start'],
                'indexes': [models.Index(fields=['employee', 'effective_start'], name='people_empl_employe_e47f5d_idx'), models.Index(fields=['component', 'effective_start'], name='people_empl_compone_2741a0_idx')],
            },
        ),
    ]
