# Generated by Django 5.2.3 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_benefittype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebenefit',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
