# Generated by Django 5.2.3 on 2026-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_backfill_benefit_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, help_text='Service start date (null = unknown, e.g. bulk ERP import)', null=True),
        ),
    ]
