# Generated by Django 5.2.3 (manual — ADR-0027 / Phase OF-14).
#
# ``LeaveEntitlement.leave_type`` and ``LeaveRecord.leave_type`` move from a
# plain ``CharField(max_length=40)`` code string to a governed
# ``ForeignKey('mdm.ReferenceValue')`` (``on_delete=PROTECT``), mirroring the
# ``correspondence.Correspondence.corr_type`` pattern.
#
# Because the legacy column already holds string codes, a raw ``AlterField``
# cannot cast them to the FK's ``bigint``. We therefore: drop the
# ``unique_together`` constraint, rename the legacy column to a temporary
# ``leave_type_char``, add a nullable FK, backfill it from the legacy string
# codes, drop the temporary column, and finally make the FK non-nullable and
# restore the constraint. The ``RunPython`` also seeds the ``leave_type``
# ReferenceSet + its five values so the FK is immediately resolvable.

import django.db.models.deletion
from django.db import migrations, models

# Mirrors seed_gofsco._ref_set('leave_type', …) — the five governed values.
LEAVE_TYPE_VALUES = [
    ('annual', 'Annual'),
    ('sick', 'Sick'),
    ('emergency', 'Emergency'),
    ('maternity', 'Maternity'),
    ('unpaid', 'Unpaid'),
]


def seed_and_map_leave_types(apps, schema_editor):
    """Seed the ``leave_type`` ReferenceSet/values, then map legacy rows.

    Every existing ``leave_type_char`` string is mapped to the matching
    ``ReferenceValue``; strings with no matching value fall back to ``annual``.
    Rows are never dropped. Uses ``apps.get_model`` (historical models) — no
    direct imports (and no ``correspondence`` import).
    """
    ReferenceSet = apps.get_model('mdm', 'ReferenceSet')
    ReferenceValue = apps.get_model('mdm', 'ReferenceValue')
    LeaveEntitlement = apps.get_model('people', 'LeaveEntitlement')
    LeaveRecord = apps.get_model('people', 'LeaveRecord')

    ref_set, _ = ReferenceSet.objects.get_or_create(
        name='leave_type',
        defaults={
            'slug': 'leave-type',
            'description': 'Leave types',
            'is_active': True,
            'lifecycle_state': 'active',
        },
    )
    ReferenceSet.objects.filter(pk=ref_set.pk).update(
        name='leave_type',
        slug='leave-type',
        is_active=True,
        lifecycle_state='active',
    )

    by_code = {}
    for idx, (code, label) in enumerate(LEAVE_TYPE_VALUES):
        value, _ = ReferenceValue.objects.update_or_create(
            reference_set=ref_set,
            code=code,
            defaults={'label': label, 'is_active': True, 'sort_order': idx},
        )
        by_code[code] = value

    fallback = by_code['annual']

    for ent in LeaveEntitlement.objects.all():
        ent.leave_type = by_code.get(ent.leave_type_char, fallback)
        ent.save(update_fields=['leave_type'])

    for rec in LeaveRecord.objects.all():
        rec.leave_type = by_code.get(rec.leave_type_char, fallback)
        rec.save(update_fields=['leave_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0017_employee_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveentitlement',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='leaveentitlement',
            old_name='leave_type',
            new_name='leave_type_char',
        ),
        migrations.RenameField(
            model_name='leaverecord',
            old_name='leave_type',
            new_name='leave_type_char',
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='leave_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='leave_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.RunPython(
            seed_and_map_leave_types,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='leaveentitlement',
            name='leave_type_char',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='leave_type_char',
        ),
        migrations.AlterField(
            model_name='leaveentitlement',
            name='leave_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='leaveentitlement',
            unique_together={('employee', 'year', 'leave_type')},
        ),
    ]
