# Generated by Django 5.2.3 on 2026-09-06 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0018_leave_type_referencevalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_entitled_days', models.DecimalField(decimal_places=2, default=0, help_text='Days granted to every employee per year by default', max_digits=6)),
                ('max_carryover_days', models.DecimalField(decimal_places=2, default=0, help_text='Maximum unused days that may carry forward to next year (0 = no carryover)', max_digits=6)),
                ('is_carryover_allowed', models.BooleanField(default=False, help_text='Allow unused balance to carry forward at year-end')),
                ('accrual_method', models.CharField(choices=[('upfront', 'Upfront — full allocation on 1 Jan'), ('monthly', 'Monthly — entitled_days ÷ 12 per month')], default='upfront', max_length=10)),
                ('gender_restriction', models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=10)),
                ('requires_approval', models.BooleanField(default=True, help_text='Leave requests of this type require manager approval')),
                ('min_service_days', models.PositiveIntegerField(default=0, help_text='Minimum days of service before the employee may request this leave (0 = no minimum)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(help_text="Leave type from ReferenceSet 'leave_type'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['leave_type__sort_order', 'leave_type__code'],
            },
        ),
    ]
