# Generated by Django 5.2.3 on 2026-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_leave_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paid_off', 'Paid Off'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
