# Generated by Django 5.2.3 — Phase LPR-1A (LeavePolicy registry).

from django.db import migrations, models


def backfill_leave_policy_registry(apps, schema_editor):
    """Backfill the new registry fields from the legacy shape.

    ``name`` ← the governed ``leave_type`` code; ``status`` ← active/deprecated
    from the legacy ``is_active`` boolean. Idempotent: rows that already carry a
    ``name`` are left untouched.
    """
    LeavePolicy = apps.get_model('people', 'LeavePolicy')
    for policy in LeavePolicy.objects.all():
        if policy.name:
            continue
        policy.name = policy.leave_type.code if policy.leave_type_id else ''
        policy.status = 'active' if policy.is_active else 'deprecated'
        policy.save(update_fields=['name', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0020_loan_status_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable policy name (primary identity)', max_length=200),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', help_text='Lifecycle state (supersedes is_active)', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applies_to_org_units',
            field=models.ManyToManyField(blank=True, help_text='Scope to these org units; empty = all org units', related_name='+', to='mdm.orgunit'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applies_to_contract_types',
            field=models.JSONField(blank=True, default=list, help_text='List of contract_type codes; empty = all contract types'),
        ),
        migrations.RunPython(
            backfill_leave_policy_registry,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
