# Generated by Django 5.2.3 — Phase LPR-2A (LeaveEntitlement policy provenance).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_leave_policy_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveentitlement',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Policy that created this entitlement (provenance; null = manual/legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.leavepolicy'),
        ),
    ]
