# Generated by Django 5.2.3 — Phase LPR-3A (LeavePolicyVersion + entitlement provenance).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _snapshot(policy):
    """JSON-safe snapshot of a policy's configurable fields (historical model)."""
    return {
        'leave_type': policy.leave_type.code if policy.leave_type_id else None,
        'default_entitled_days': str(policy.default_entitled_days),
        'max_carryover_days': str(policy.max_carryover_days),
        'is_carryover_allowed': policy.is_carryover_allowed,
        'accrual_method': policy.accrual_method,
        'gender_restriction': policy.gender_restriction,
        'requires_approval': policy.requires_approval,
        'min_service_days': policy.min_service_days,
        'name': policy.name,
        'description': policy.description,
        'status': policy.status,
        'applies_to_contract_types': list(policy.applies_to_contract_types or []),
        'applies_to_org_units': list(
            policy.applies_to_org_units.values_list('id', flat=True),
        ),
    }


def backfill_version_one(apps, schema_editor):
    """Link legacy entitlements to a backfilled version 1 of their policy.

    For each ``LeaveEntitlement`` that carries a ``policy`` but no
    ``policy_version``, create (idempotently) a version 1 snapshot of that
    policy from its current config and point the entitlement at it. Guarded
    against double-run via ``get_or_create`` keyed on ``(policy, version_number)``
    and the ``policy_version__isnull`` filter.
    """
    LeavePolicy = apps.get_model('people', 'LeavePolicy')
    LeavePolicyVersion = apps.get_model('people', 'LeavePolicyVersion')
    LeaveEntitlement = apps.get_model('people', 'LeaveEntitlement')

    policy_ids = set(
        LeaveEntitlement.objects.filter(
            policy__isnull=False, policy_version__isnull=True,
        ).values_list('policy_id', flat=True)
    )

    for policy_id in policy_ids:
        policy = LeavePolicy.objects.get(pk=policy_id)
        version, _ = LeavePolicyVersion.objects.get_or_create(
            policy=policy,
            version_number=1,
            defaults={
                'effective_from': policy.effective_from or timezone.localdate(),
                'snapshot': _snapshot(policy),
                'change_summary': 'Legacy policy version (backfilled)',
            },
        )
        LeaveEntitlement.objects.filter(
            policy_id=policy_id, policy_version__isnull=True,
        ).update(policy_version=version)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_leaveentitlement_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='people.leavepolicy')),
            ],
            options={
                'verbose_name': 'Leave Policy Version',
                'verbose_name_plural': 'Leave Policy Versions',
                'ordering': ['policy', '-version_number'],
                'unique_together': {('policy', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='policy_version',
            field=models.ForeignKey(blank=True, help_text='Policy version that created this entitlement (provenance; null = legacy/manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.leavepolicyversion'),
        ),
        migrations.RunPython(
            backfill_version_one,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
