# Generated by Django 5.2.3 on 2026-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_leave_policy_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='category',
            field=models.CharField(blank=True, help_text='Grouping bucket for the policy registry (e.g. Leave, Attendance, Travel, Benefits, Conduct)', max_length=100),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of free-form tags for discovery (e.g. ['remote', 'probation'])"),
        ),
    ]
