# Generated by Django 5.2.3 on 2026-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_leave_policy_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='applies_to_kuwaitization',
            field=models.CharField(choices=[('any', 'Any'), ('kuwaiti', 'Kuwaiti only'), ('non_kuwaiti', 'Non-Kuwaiti only')], default='any', help_text='Kuwaitization scope: any / Kuwaiti only / non-Kuwaiti only (GOFSCO 42-day vs 30-day leave)', max_length=16),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applies_to_rotations',
            field=models.JSONField(blank=True, default=list, help_text="List of rotation pattern codes (e.g. ['1/1','2/1']); empty = all rotations (GOFSCO rotation leave)"),
        ),
    ]
