# Generated by Django 5.2.3 (manual — ADR-0027 / NSR-7B).
#
# Bucket-1 soft CharFields / free-text → FK to mdm.ReferenceValue (PROTECT).
# Mirrors people/migrations/0018_leave_type_referencevalue.py:
# rename legacy → nullable FK → RunPython backfill → drop legacy → tighten nulls.
#
# RULE_16: never fabricate ReferenceValues for unknown legacy codes. Map known
# codes; optional fields → null; required fields use an explicit seeded fallback.
# ``loan_installment`` is ensured on payslip_line_type because payroll_service
# already emits that code (NSR-7A seed gap).

import django.db.models.deletion
from django.db import migrations, models


# Codes already used by payroll_service / validation that NSR-7A omitted.
PAYSLIP_EXTRA = [
    ('loan_installment', 'Loan Installment'),
]

# Required-field fallbacks when legacy code has no matching ReferenceValue.
FALLBACKS = {
    'loan_type': 'personal',
    'permission_type': 'personal',
    'cert_type': 'trade',
    'rotation_pattern': 'office',
    'payslip_line_type': 'deduction',
    'compliance_category': 'other',
    'jurisdiction': 'KW',
}


def _by_code(ReferenceValue, set_name):
    return {
        rv.code: rv
        for rv in ReferenceValue.objects.filter(reference_set__name=set_name)
    }


def _lookup(by_code, raw, *, fallback=None):
    if raw is None:
        return fallback
    code = str(raw).strip()
    if not code:
        return fallback
    return by_code.get(code, fallback)


def seed_and_map_bucket1(apps, schema_editor):
    ReferenceSet = apps.get_model('mdm', 'ReferenceSet')
    ReferenceValue = apps.get_model('mdm', 'ReferenceValue')

    Employee = apps.get_model('people', 'Employee')
    Position = apps.get_model('people', 'Position')
    Loan = apps.get_model('people', 'Loan')
    AttendancePermission = apps.get_model('people', 'AttendancePermission')
    Certification = apps.get_model('people', 'Certification')
    RotationSchedule = apps.get_model('people', 'RotationSchedule')
    PayslipLine = apps.get_model('people', 'PayslipLine')
    BenefitType = apps.get_model('people', 'BenefitType')
    ComplianceRule = apps.get_model('people', 'ComplianceRule')

    # Ensure loan_installment exists for payroll (do not invent other values).
    rs = ReferenceSet.objects.filter(name='payslip_line_type').first()
    if rs is not None:
        for idx, (code, label) in enumerate(PAYSLIP_EXTRA):
            ReferenceValue.objects.update_or_create(
                reference_set=rs,
                code=code,
                defaults={'label': label, 'is_active': True, 'sort_order': 200 + idx},
            )

    nat = _by_code(ReferenceValue, 'nationality')
    emp_t = _by_code(ReferenceValue, 'employment_type')
    con_t = _by_code(ReferenceValue, 'contract_type')
    gender = _by_code(ReferenceValue, 'gender')
    rot = _by_code(ReferenceValue, 'rotation_pattern')
    job_f = _by_code(ReferenceValue, 'job_family')
    grade = _by_code(ReferenceValue, 'grade')
    loan_t = _by_code(ReferenceValue, 'loan_type')
    perm_t = _by_code(ReferenceValue, 'permission_type')
    cert_t = _by_code(ReferenceValue, 'cert_type')
    line_t = _by_code(ReferenceValue, 'payslip_line_type')
    ben_c = _by_code(ReferenceValue, 'benefit_category')
    comp_c = _by_code(ReferenceValue, 'compliance_category')
    juris = _by_code(ReferenceValue, 'jurisdiction')

    # Label→code aliases for free-text nationality / gender leftovers.
    nat_by_label = {
        rv.label.strip().lower(): rv for rv in nat.values() if rv.label
    }
    gender_aliases = {
        'm': 'male', 'male': 'male', 'man': 'male',
        'f': 'female', 'female': 'female', 'woman': 'female',
        'other': 'other', 'o': 'other',
    }

    loan_fb = loan_t.get(FALLBACKS['loan_type'])
    perm_fb = perm_t.get(FALLBACKS['permission_type'])
    cert_fb = cert_t.get(FALLBACKS['cert_type'])
    rot_fb = rot.get(FALLBACKS['rotation_pattern'])
    line_fb = line_t.get(FALLBACKS['payslip_line_type'])
    comp_fb = comp_c.get(FALLBACKS['compliance_category'])
    juris_fb = juris.get(FALLBACKS['jurisdiction'])

    for emp in Employee.objects.all():
        # nationality: prefer legacy code, else match free-text label
        n = _lookup(nat, getattr(emp, 'nationality_code_legacy', None))
        if n is None:
            label = (getattr(emp, 'nationality_legacy', None) or '').strip().lower()
            if label:
                n = nat_by_label.get(label) or nat.get(label.upper()) or nat.get(label)
        emp.nationality = n
        emp.employment_type = _lookup(emp_t, getattr(emp, 'employment_type_code_legacy', None))
        emp.contract_type = _lookup(con_t, getattr(emp, 'contract_type_code_legacy', None))

        g_raw = (getattr(emp, 'gender_legacy', None) or '').strip()
        g_code = gender_aliases.get(g_raw.lower(), g_raw.lower() if g_raw else '')
        emp.gender = gender.get(g_code) if g_code else None

        emp.rotation = _lookup(rot, getattr(emp, 'rotation_legacy', None))
        emp.save(update_fields=[
            'nationality', 'employment_type', 'contract_type', 'gender', 'rotation',
        ])

    for pos in Position.objects.all():
        pos.job_family = _lookup(job_f, getattr(pos, 'job_family_code_legacy', None))
        pos.grade = _lookup(grade, getattr(pos, 'grade_legacy', None))
        pos.save(update_fields=['job_family', 'grade'])

    for loan in Loan.objects.all():
        loan.loan_type = _lookup(loan_t, getattr(loan, 'loan_type_legacy', None), fallback=loan_fb)
        loan.save(update_fields=['loan_type'])

    for perm in AttendancePermission.objects.all():
        perm.permission_type = _lookup(
            perm_t, getattr(perm, 'permission_type_legacy', None), fallback=perm_fb,
        )
        perm.save(update_fields=['permission_type'])

    for cert in Certification.objects.all():
        cert.cert_type = _lookup(cert_t, getattr(cert, 'cert_type_legacy', None), fallback=cert_fb)
        cert.save(update_fields=['cert_type'])

    for sched in RotationSchedule.objects.all():
        sched.pattern = _lookup(rot, getattr(sched, 'pattern_legacy', None), fallback=rot_fb)
        sched.save(update_fields=['pattern'])

    for line in PayslipLine.objects.all():
        line.line_type = _lookup(line_t, getattr(line, 'line_type_legacy', None), fallback=line_fb)
        line.save(update_fields=['line_type'])

    for bt in BenefitType.objects.all():
        bt.category = _lookup(ben_c, getattr(bt, 'category_legacy', None))
        bt.save(update_fields=['category'])

    for rule in ComplianceRule.objects.all():
        rule.category = _lookup(
            comp_c, getattr(rule, 'category_legacy', None), fallback=comp_fb,
        )
        rule.jurisdiction = _lookup(
            juris, getattr(rule, 'jurisdiction_legacy', None), fallback=juris_fb,
        )
        rule.save(update_fields=['category', 'jurisdiction'])


def _fk(null=True):
    return models.ForeignKey(
        null=null,
        on_delete=django.db.models.deletion.PROTECT,
        related_name='+',
        to='mdm.referencevalue',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0025_leavepolicy_applies_to_kuwaitization_and_more'),
    ]

    # Same deferred-trigger rationale as 0018_leave_type_referencevalue.
    atomic = False

    operations = [
        # ── Employee: rename legacy columns ──────────────────────────────
        migrations.RenameField(model_name='employee', old_name='nationality', new_name='nationality_legacy'),
        migrations.RenameField(model_name='employee', old_name='nationality_code', new_name='nationality_code_legacy'),
        migrations.RenameField(model_name='employee', old_name='employment_type_code', new_name='employment_type_code_legacy'),
        migrations.RenameField(model_name='employee', old_name='contract_type_code', new_name='contract_type_code_legacy'),
        migrations.RenameField(model_name='employee', old_name='gender', new_name='gender_legacy'),
        migrations.RenameField(model_name='employee', old_name='rotation', new_name='rotation_legacy'),
        migrations.AddField(model_name='employee', name='nationality', field=_fk()),
        migrations.AddField(model_name='employee', name='employment_type', field=_fk()),
        migrations.AddField(model_name='employee', name='contract_type', field=_fk()),
        migrations.AddField(model_name='employee', name='gender', field=_fk()),
        migrations.AddField(model_name='employee', name='rotation', field=_fk()),

        # ── Position ─────────────────────────────────────────────────────
        migrations.RenameField(model_name='position', old_name='job_family_code', new_name='job_family_code_legacy'),
        migrations.RenameField(model_name='position', old_name='grade', new_name='grade_legacy'),
        migrations.AddField(model_name='position', name='job_family', field=_fk()),
        migrations.AddField(model_name='position', name='grade', field=_fk()),

        # ── Loan ─────────────────────────────────────────────────────────
        migrations.RenameField(model_name='loan', old_name='loan_type', new_name='loan_type_legacy'),
        migrations.AddField(model_name='loan', name='loan_type', field=_fk()),

        # ── AttendancePermission ─────────────────────────────────────────
        migrations.RenameField(
            model_name='attendancepermission',
            old_name='permission_type',
            new_name='permission_type_legacy',
        ),
        migrations.AddField(model_name='attendancepermission', name='permission_type', field=_fk()),

        # ── Certification ────────────────────────────────────────────────
        migrations.RenameField(model_name='certification', old_name='cert_type', new_name='cert_type_legacy'),
        migrations.AddField(model_name='certification', name='cert_type', field=_fk()),

        # ── RotationSchedule ─────────────────────────────────────────────
        migrations.RenameField(model_name='rotationschedule', old_name='pattern', new_name='pattern_legacy'),
        migrations.AddField(model_name='rotationschedule', name='pattern', field=_fk()),

        # ── PayslipLine ──────────────────────────────────────────────────
        migrations.RenameField(model_name='payslipline', old_name='line_type', new_name='line_type_legacy'),
        migrations.AddField(model_name='payslipline', name='line_type', field=_fk()),

        # ── BenefitType ──────────────────────────────────────────────────
        migrations.RenameField(model_name='benefittype', old_name='category', new_name='category_legacy'),
        migrations.AddField(model_name='benefittype', name='category', field=_fk()),

        # ── ComplianceRule ───────────────────────────────────────────────
        migrations.RenameField(model_name='compliancerule', old_name='category', new_name='category_legacy'),
        migrations.RenameField(model_name='compliancerule', old_name='jurisdiction', new_name='jurisdiction_legacy'),
        migrations.AddField(model_name='compliancerule', name='category', field=_fk()),
        migrations.AddField(model_name='compliancerule', name='jurisdiction', field=_fk()),

        migrations.RunPython(seed_and_map_bucket1, reverse_code=migrations.RunPython.noop),

        # ── Drop legacy columns ──────────────────────────────────────────
        migrations.RemoveField(model_name='employee', name='nationality_legacy'),
        migrations.RemoveField(model_name='employee', name='nationality_code_legacy'),
        migrations.RemoveField(model_name='employee', name='employment_type_code_legacy'),
        migrations.RemoveField(model_name='employee', name='contract_type_code_legacy'),
        migrations.RemoveField(model_name='employee', name='gender_legacy'),
        migrations.RemoveField(model_name='employee', name='rotation_legacy'),

        migrations.RemoveField(model_name='position', name='job_family_code_legacy'),
        migrations.RemoveField(model_name='position', name='grade_legacy'),

        migrations.RemoveField(model_name='loan', name='loan_type_legacy'),
        migrations.RemoveField(model_name='attendancepermission', name='permission_type_legacy'),
        migrations.RemoveField(model_name='certification', name='cert_type_legacy'),
        migrations.RemoveField(model_name='rotationschedule', name='pattern_legacy'),
        migrations.RemoveField(model_name='payslipline', name='line_type_legacy'),
        migrations.RemoveField(model_name='benefittype', name='category_legacy'),
        migrations.RemoveField(model_name='compliancerule', name='category_legacy'),
        migrations.RemoveField(model_name='compliancerule', name='jurisdiction_legacy'),

        # ── Required FKs non-null (where business requires a value) ──────
        migrations.AlterField(
            model_name='loan', name='loan_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='attendancepermission', name='permission_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='certification', name='cert_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='rotationschedule', name='pattern',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='payslipline', name='line_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='compliancerule', name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
        migrations.AlterField(
            model_name='compliancerule', name='jurisdiction',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='mdm.referencevalue',
            ),
        ),
    ]
