# Generated by Django 5.2.3 on 2026-09-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0026_bucket1_governed_referencevalue_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefittype',
            options={'ordering': ['category__sort_order', 'category__code', 'code'], 'verbose_name': 'Benefit Type', 'verbose_name_plural': 'Benefit Types'},
        ),
        migrations.AlterModelOptions(
            name='compliancerule',
            options={'ordering': ['category__sort_order', 'category__code', 'rule_id', '-effective_date'], 'verbose_name': 'Compliance Rule', 'verbose_name_plural': 'Compliance Rules'},
        ),
        migrations.AlterField(
            model_name='attendancepermission',
            name='permission_type',
            field=models.ForeignKey(help_text="Permission type from ReferenceSet 'permission_type'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='benefittype',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Category from ReferenceSet 'benefit_category'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_type',
            field=models.ForeignKey(help_text="Cert type from ReferenceSet 'cert_type'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='category',
            field=models.ForeignKey(help_text="Category from ReferenceSet 'compliance_category'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='jurisdiction',
            field=models.ForeignKey(help_text="Jurisdiction from ReferenceSet 'jurisdiction' (e.g. KW)", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(blank=True, help_text="Contract type from ReferenceSet 'contract_type'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.ForeignKey(blank=True, help_text="Employment type from ReferenceSet 'employment_type'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, help_text="Gender from ReferenceSet 'gender'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(blank=True, help_text="Nationality from ReferenceSet 'nationality'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rotation',
            field=models.ForeignKey(blank=True, help_text="Rotation pattern from ReferenceSet 'rotation_pattern'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(help_text="Loan type from ReferenceSet 'loan_type'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='line_type',
            field=models.ForeignKey(help_text="Line type from ReferenceSet 'payslip_line_type'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.ForeignKey(blank=True, help_text="Grade from ReferenceSet 'grade'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_family',
            field=models.ForeignKey(blank=True, help_text="Job family from ReferenceSet 'job_family'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
        migrations.AlterField(
            model_name='rotationschedule',
            name='pattern',
            field=models.ForeignKey(help_text="Pattern from ReferenceSet 'rotation_pattern'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue'),
        ),
    ]
