# Generated by Django 5.2.3 on 2026-09-21 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_bucket1_fk_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WpsFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('validated', 'Validated'), ('submitted', 'Submitted')], default='generated', max_length=20)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('csv_bytes', models.BinaryField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_id', models.CharField(blank=True, default='', max_length=64)),
                ('reconciled', models.BooleanField(default=False)),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wps_filing', to='people.payrollrun')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WPS Filing',
                'verbose_name_plural': 'WPS Filings',
            },
        ),
    ]
