# Generated by Django 5.2.3 on 2026-09-21 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_wps_filing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoDPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.PositiveIntegerField()),
                ('process_key', models.CharField(blank=True, max_length=128)),
                ('prepared_at', models.DateTimeField()),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sod_preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SoD preparation',
                'verbose_name_plural': 'SoD preparations',
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='people_sodp_subject_a6cf3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id'), name='people_sodprep_subject_uniq')],
            },
        ),
    ]
