# Generated by Django 5.2.3 on 2026-09-22 13:19

from django.db import migrations, models


def forwards_attendance_status(apps, schema_editor):
    AttendancePermission = apps.get_model('people', 'AttendancePermission')
    AttendancePermission.objects.filter(approved=True).update(status='approved')
    AttendancePermission.objects.filter(approved=False).update(status='pending')


def backwards_attendance_status(apps, schema_editor):
    AttendancePermission = apps.get_model('people', 'AttendancePermission')
    AttendancePermission.objects.filter(status='approved').update(approved=True)
    AttendancePermission.objects.exclude(status='approved').update(approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_sod_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermission',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards_attendance_status, backwards_attendance_status),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('active', 'Active'),
                    ('paid_off', 'Paid Off'),
                    ('cancelled', 'Cancelled'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
    ]
