# Generated by Django 5.2.3 on 2026-09-23 10:00

from django.db import migrations, models
from django.db.models import Count


ACTIVE = ('draft', 'computed', 'validated', 'committed')


def refuse_duplicate_active_periods(apps, schema_editor):
    """Stop before the constraint. Do not delete or rewrite the rows."""
    PayrollRun = apps.get_model('people', 'PayrollRun')
    groups = list(
        PayrollRun.objects.filter(status__in=ACTIVE)
        .values('org_unit_id', 'period_start', 'period_end')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .order_by('org_unit_id', 'period_start')
    )
    if not groups:
        return
    detail = '; '.join(
        f"org={row['org_unit_id']} {row['period_start']}..{row['period_end']} n={row['n']}"
        for row in groups
    )
    raise RuntimeError(
        'Refusing people_payrollrun_one_active_period. Duplicate active payroll '
        'runs exist and were not deleted or rewritten. Keep one run in each '
        f'group by hand, then migrate again. {detail}'
    )


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        ('people', '0030_attendance_status_loan_default_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpsfiling',
            name='receipt_id',
            field=models.CharField(blank=True, default='', help_text='LOCAL-WPS-* is a Carbon export id. PAM/bank receipt is recorded separately.', max_length=64),
        ),
        migrations.AlterField(
            model_name='wpsfiling',
            name='reconciled',
            field=models.BooleanField(default=False, help_text='True only after an external PAM or bank acknowledgement. Local submit does not set this.'),
        ),
        migrations.RunPython(refuse_duplicate_active_periods, noop),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'computed', 'validated', 'committed'])), fields=('org_unit', 'period_start', 'period_end'), name='people_payrollrun_one_active_period'),
        ),
    ]
