# Generated by Django 5.2.3 on 2026-09-06 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('subject_type', models.CharField(blank=True, default='', max_length=120)),
                ('subject_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('sent_back', 'Sent Back'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('current_approver_ids', models.JSONField(blank=True, default=list)),
                ('approver_chain', models.JSONField(blank=True, default=list)),
                ('policy_version', models.CharField(blank=True, max_length=40)),
                ('policy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('signature_ref', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corr_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mdm.referencevalue')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdm.orgunit')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='correspondence/attachments/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='correspondence.correspondence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(max_length=24)),
                ('from_status', models.CharField(blank=True, max_length=16, null=True)),
                ('to_status', models.CharField(blank=True, max_length=16, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='correspondence.correspondence')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('counter', models.PositiveIntegerField(default=0)),
                ('corr_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdm.referencevalue')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='all', max_length=16)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corr_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.referencevalue')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_made', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondence.correspondence')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondence.correspondenceevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('numbering_format', models.CharField(default='{PREFIX}-{YEAR}-{SEQ:04d}', max_length=120)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corr_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdm.referencevalue')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPolicyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('specific_user', 'Specific User'), ('any_admin', 'Any Admin')], max_length=24)),
                ('intent', models.CharField(choices=[('approve', 'Approve'), ('acknowledge', 'Acknowledge'), ('review', 'Review')], default='approve', max_length=16)),
                ('skip_if_self', models.BooleanField(default=False)),
                ('auto_approve', models.BooleanField(default=False)),
                ('can_skip', models.BooleanField(default=False)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='correspondence.workflowpolicy')),
                ('specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['status', 'requester'], name='corresponde_status_b66c50_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['status'], name='corresponde_status_825c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['corr_type'], name='corresponde_corr_ty_33f339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correspondenceevent',
            unique_together={('correspondence', 'seq')},
        ),
        migrations.AlterUniqueTogether(
            name='correspondenceregistry',
            unique_together={('corr_type', 'org_unit', 'year')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='corresponde_user_id_0f3217_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowpolicy',
            unique_together={('corr_type', 'org_unit', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowpolicystep',
            unique_together={('policy', 'order')},
        ),
    ]
