# Generated by Django 5.2.3 on 2026-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_correspondenceregistry_consolidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowpolicystep',
            name='fallback_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('specific_user', 'Specific User'), ('any_admin', 'Any Admin')], default='', help_text='Who approves when nobody holds `role` (an employee with no manager). Left blank, such a request waits for routing rather than passing unapproved.', max_length=24),
        ),
    ]
