"""AI intelligence durable-state models — single ``app_label="ai"`` namespace.

Re-exports the existing workspace models plus the 49 vendored engine tables
(Phase 2). Import surface: ``from ai.models import AIConversation, KgNode, ...``.
"""

from .base import AppScopeMixin, generate_uuid
from .catalog import ModelCatalog
from .workspace import (
    AIArtifact,
    AIConversation,
    AIGeneration,
    AIMessage,
    AIUserProfile,
    ConversationCheckpoint,
)
from .core import (
    AcceptanceReport,
    Agent,
    AgentHandoff,
    AIAnomalyWatch,
    AISubagent,
    AuditLog,
    CognitionSweepRun,
    Conversation,
    ConversationContextRecord,
    CsvUpload,
    Feedback,
    Insight,
    Instance,
    KgEdge,
    KgNode,
    KgProvenance,
    KnowledgeEntity,
    LearningOutcome,
    LLMCallLog,
    MemoryEpisodic,
    MemoryLongTerm,
    Message,
    Notification,
    OpsRun,
    PlanTemplate,
    PlaybookBlock,
    PromptEval,
    PromptVersion,
    PulseUser,
    Run,
    RunArtifact,
    RunSchedule,
    RunStep,
    Skill,
    SkillAdmissionLog,
    SystemSnapshot,
    TaskExecution,
    ToolExecution,
    Trajectory,
    TurnLedgerRow,
    UserKey,
    VectorEmbedding,
)
from .feedback import DqFeedbackEvent
from .knowledge_graph import (
    KgBootstrapRun,
    KgCacheEntry,
    KgDomainPack,
    KgFeedbackRecord,
    KgGoldenPair,
    KgPlanStep,
    KgProactiveInsight,
    KgProactiveTrigger,
    KgQualityScore,
    KgQueryFeedback,
    KgQueryPlan,
    KgRecoveryLog,
    KgReviewItem,
    KnowledgeEdge,
    KnowledgeNode,
)

__all__ = [
    "AIArtifact",
    "AIConversation",
    "AIGeneration",
    "AIMessage",
    "AIUserProfile",
    "ConversationCheckpoint",
    "DqFeedbackEvent",
    "AppScopeMixin",
    "generate_uuid",
    "ModelCatalog",
    # core
    "AcceptanceReport",
    "Agent",
    "AgentHandoff",
    "AIAnomalyWatch",
    "AuditLog",
    "CognitionSweepRun",
    "Conversation",
    "ConversationContextRecord",
    "CsvUpload",
    "Feedback",
    "Insight",
    "Instance",
    "KgEdge",
    "KgNode",
    "KgProvenance",
    "KnowledgeEntity",
    "LearningOutcome",
    "LLMCallLog",
    "MemoryEpisodic",
    "MemoryLongTerm",
    "Message",
    "Notification",
    "OpsRun",
    "PlanTemplate",
    "PlaybookBlock",
    "PromptEval",
    "PromptVersion",
    "PulseUser",
    "Run",
    "RunArtifact",
    "RunSchedule",
    "RunStep",
    "Skill",
    "SkillAdmissionLog",
    "SystemSnapshot",
    "TaskExecution",
    "ToolExecution",
    "Trajectory",
    "TurnLedgerRow",
    "UserKey",
    "VectorEmbedding",
    # knowledge_graph
    "KgBootstrapRun",
    "KgCacheEntry",
    "KgDomainPack",
    "KgFeedbackRecord",
    "KgGoldenPair",
    "KgPlanStep",
    "KgProactiveInsight",
    "KgProactiveTrigger",
    "KgQualityScore",
    "KgQueryFeedback",
    "KgQueryPlan",
    "KgRecoveryLog",
    "KgReviewItem",
    "KnowledgeEdge",
    "KnowledgeNode",
]
