"""AI intelligence durable-state models — single ``app_label="ai"`` namespace.

Re-exports the existing workspace models plus the 49 vendored engine tables
(Phase 2). Import surface: ``from ai.models import AIConversation, KgNode, ...``.
"""

from .base import AppScopeMixin, generate_uuid
from .catalog import ModelCatalog
from .workspace import AIArtifact, AIConversation, AIGeneration, AIMessage
from .core import (
    Agent,
    AgentHandoff,
    AuditLog,
    CognitionSweepRun,
    Conversation,
    ConversationContextRecord,
    CsvUpload,
    Feedback,
    Insight,
    Instance,
    KgEdge,
    KgNode,
    KgProvenance,
    KnowledgeEntity,
    LLMCallLog,
    MemoryEpisodic,
    MemoryLongTerm,
    Message,
    Notification,
    OpsRun,
    PlaybookBlock,
    PromptEval,
    PromptVersion,
    PulseUser,
    Run,
    RunStep,
    Skill,
    SkillAdmissionLog,
    SystemSnapshot,
    TaskExecution,
    ToolExecution,
    Trajectory,
    TurnLedgerRow,
    UserKey,
    VectorEmbedding,
)
from .knowledge_graph import (
    KgBootstrapRun,
    KgCacheEntry,
    KgDomainPack,
    KgFeedbackRecord,
    KgGoldenPair,
    KgPlanStep,
    KgProactiveInsight,
    KgProactiveTrigger,
    KgQualityScore,
    KgQueryFeedback,
    KgQueryPlan,
    KgRecoveryLog,
    KgReviewItem,
    KnowledgeEdge,
    KnowledgeNode,
)

__all__ = [
    "AIArtifact",
    "AIConversation",
    "AIGeneration",
    "AIMessage",
    "AppScopeMixin",
    "generate_uuid",
    "ModelCatalog",
    # core
    "Agent",
    "AgentHandoff",
    "AuditLog",
    "CognitionSweepRun",
    "Conversation",
    "ConversationContextRecord",
    "CsvUpload",
    "Feedback",
    "Insight",
    "Instance",
    "KgEdge",
    "KgNode",
    "KgProvenance",
    "KnowledgeEntity",
    "LLMCallLog",
    "MemoryEpisodic",
    "MemoryLongTerm",
    "Message",
    "Notification",
    "OpsRun",
    "PlaybookBlock",
    "PromptEval",
    "PromptVersion",
    "PulseUser",
    "Run",
    "RunStep",
    "Skill",
    "SkillAdmissionLog",
    "SystemSnapshot",
    "TaskExecution",
    "ToolExecution",
    "Trajectory",
    "TurnLedgerRow",
    "UserKey",
    "VectorEmbedding",
    # knowledge_graph
    "KgBootstrapRun",
    "KgCacheEntry",
    "KgDomainPack",
    "KgFeedbackRecord",
    "KgGoldenPair",
    "KgPlanStep",
    "KgProactiveInsight",
    "KgProactiveTrigger",
    "KgQualityScore",
    "KgQueryFeedback",
    "KgQueryPlan",
    "KgRecoveryLog",
    "KgReviewItem",
    "KnowledgeEdge",
    "KnowledgeNode",
]
