"""
GHG Protocol Inventory Report PDF generator.

Uses WeasyPrint to generate a printable PDF with:
- Organizational boundary statement
- Methodology description
- Scope 1/2/3 totals including Scope 2 dual breakdown
- Base year comparison
- Verification status
"""


def generate_inventory_pdf(report_data):
    """
    Generate a PDF bytes object from inventory report data.

    Requires: weasyprint (pip install weasyprint)

    Args:
        report_data: dict from inventory_report endpoint

    Returns:
        bytes: PDF content
    """
    from weasyprint import HTML

    period = report_data['reporting_period']
    boundary = report_data['boundary_statement']
    scope = report_data['scope_totals_tco2e']
    base = report_data['base_year_comparison']
    quality = report_data['avg_data_quality_tier']

    base_section = ''
    if base:
        arrow = '↓' if base['change_pct'] < 0 else '↑'
        base_section = f'''
        <h2>Base Year Comparison</h2>
        <table>
            <tr><th>Base Year</th><td>{base['year']}</td></tr>
            <tr><th>Base Year Emissions</th><td>{base['total_tco2e']} tCO₂e</td></tr>
            <tr><th>Current Emissions</th><td>{base['current_tco2e']} tCO₂e</td></tr>
            <tr><th>Change</th><td>{arrow} {abs(base['change_pct'])}%</td></tr>
            <tr><th>Recalculation Policy</th><td>{base['recalculation_policy']}</td></tr>
        </table>
        '''

    html_str = f'''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{report_data['title']}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #1a5276; border-bottom: 2px solid #1a5276; padding-bottom: 8px; }}
            h2 {{ color: #2c3e50; margin-top: 24px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background: #f2f2f2; }}
            .meta {{ color: #666; font-size: 0.9em; }}
            .footer {{ margin-top: 40px; border-top: 1px solid #ccc; padding-top: 8px; font-size: 0.8em; color: #999; }}
        </style>
    </head>
    <body>
        <h1>{report_data['title']}</h1>
        <p class="meta">
            Generated: {report_data['generated_at']}<br>
            Period: {period['name']} ({period['start_date']} to {period['end_date']})<br>
            Status: {period['status']}
        </p>

        <h2>Organizational Boundary</h2>
        <p><strong>{boundary}</strong></p>
        <p>{report_data['methodology']}</p>

        <h2>Emissions Summary</h2>
        <table>
            <tr><th>Scope</th><th>Emissions (tCO₂e)</th></tr>
            <tr><td>Scope 1 — Direct</td><td>{scope.get(1, 0):,.2f}</td></tr>
            <tr><td>Scope 2 — Indirect (Energy)</td><td>{scope.get(2, 0):,.2f}</td></tr>
            <tr><td>  ↳ Location-Based</td><td>{report_data['scope2_location_tco2e']:,.2f}</td></tr>
            <tr><td>  ↳ Market-Based</td><td>{report_data['scope2_market_tco2e']:,.2f}</td></tr>
            <tr><td>Scope 3 — Value Chain</td><td>{scope.get(3, 0):,.2f}</td></tr>
            <tr><th>Total</th><th>{report_data['total_tco2e']:,.2f}</th></tr>
        </table>
        {base_section}
        <h2>Data Quality</h2>
        <table>
            <tr><th>Calculations</th><td>{report_data['calculation_count']}</td></tr>
            <tr><th>Average Data Quality Tier</th><td>{quality} (IPCC Tier scale 1–3)</td></tr>
        </table>

        <h2>Verification</h2>
        <p>Status: {report_data['verification_status']}</p>
        {f"<p>Notes: {report_data['verification_notes']}</p>" if report_data.get('verification_notes') else ""}

        <div class="footer">
            Generated by Carbon Data Trust Platform — GHG Protocol Corporate Standard
        </div>
    </body>
    </html>
    '''

    return HTML(string=html_str).write_pdf()
