"""Staff Index-job orchestration for the aast-med content engine.

The plugin "Index this course" button posts here through
``ai.moodle_host_api.MoodleIndexView``. This module is the one place that turns
one staff Index request into the content-engine artifacts:

* **Extra files** — uploaded ``.txt/.md/.json`` bytes are read through the shared
  reader registry and written to ``bank/course-extra-13`` (still staff-only,
  verbatim, cited as ``extra:<name>``).
* **Chunk index** — ``content_engine.index`` over the pack passage bank, saved
  to ``domain_packs/aast-med/index/<shortname>.jsonl``. Keyword layer only;
  semantic stays default-OFF.
* **Knowledge graph** — ``content_engine.graph`` from the raw bank rows, saved
  to ``domain_packs/aast-med/graph/<shortname>.jsonl``. Additive and never
  required for teaching; every edge carries a real passage_ref.
* **Drive** — default-OFF; only runs when the caller asks and the environment
  enables it. It never touches the network from a Chat turn.

Nothing here is imported at module load by a turn path: the view imports it
lazily inside the POST handler, and the builders import ``ai.moodle_bank``
lazily, so importing this module keeps the engine free of Django and of the
content engine.

Shipping note — the index is a BUILD ARTIFACT
---------------------------------------------
``domain_packs/aast-med/index/<shortname>.jsonl`` is generated by this staff
Index job (``run_index(name, {"build": ["index"]})``) and is regenerated on
install and after any change to the pack bank; it is never hand-edited. The
committed files are **vendored** so a fresh checkout can answer topic questions
before the job runs, but the job stays the source of truth: a rebuild from the
same pack bank is byte-identical (deterministic chunk order + term-sorted
postings, no wall-clock, no hash-seed dependence). When the bank changes,
re-run the Index job and vendor the regenerated bytes — do not commit an index
that disagrees with a fresh build.
"""
from __future__ import annotations

import hashlib
import os
from datetime import datetime, timezone
from pathlib import Path

from ai.content_engine import acquire, ingest
from ai.moodle_bank import listed_shortnames, write_extra_index

_PACK = Path(__file__).resolve().parents[2] / "domain_packs" / "aast-med"

#: Caller-overridable artifact roots (monkeypatched in tests).
_INDEX_ROOT = _PACK / "index"
_GRAPH_ROOT = _PACK / "graph"
_OCR_ROOT = _PACK / "bank" / "ocr-pending"
#: Append-only, auditable human sign-off records. One file per course; a
#: sign-off line is only ever written by an explicit staff call.
_OCR_SIGNOFF_ROOT = _PACK / "bank" / "ocr-signoff"


def index_roots() -> dict[str, Path]:
    return {
        "index": _INDEX_ROOT,
        "graph": _GRAPH_ROOT,
        "ocr": _OCR_ROOT,
        "ocr_signoff": _OCR_SIGNOFF_ROOT,
    }


def _extra_indexed(shortname: str, payload: dict) -> tuple[int, str]:
    """Write the extra index from raw file bytes when present, else passages."""
    files = payload.get("files") or []
    if isinstance(files, list) and files:
        extras = ingest.extra_payload_from_files(files)
        return write_extra_index(shortname, extras), "readers"
    extras = payload.get("extras") or []
    if isinstance(extras, list) and extras:
        return write_extra_index(shortname, extras), "passages"
    return 0, "none"


def _text_sha256(text: str) -> str:
    """Stable digest of the exact quote a sign-off covers."""
    return hashlib.sha256(str(text or "").encode("utf-8")).hexdigest()


def ocr_passage_id(shortname: str, row: dict) -> str:
    """Deterministic id for one pending OCR passage (source ref + locator)."""
    ref = str(row.get("ref") or row.get("filename") or "").strip()
    locator = str(row.get("locator") or "").strip()
    return f"{shortname}:ocr:{ref}:{locator}"


def record_ocr_pending(shortname: str, rows: list[dict], *, root: str | os.PathLike[str] | None = None) -> int:
    """Persist non-citable OCR text awaiting the recorded human sign-off.

    Arabic scanned content is stored here (never in the citable bank) with an
    explicit ``pending_signoff`` status, so it can be reviewed and cleared
    without any risk of it becoming a verbatim cite first. Each row is tagged
    with the deterministic ``passage_id`` a sign-off record must name.
    """
    if shortname not in listed_shortnames():
        return 0
    path = Path(root) if root is not None else _OCR_ROOT
    path.mkdir(parents=True, exist_ok=True)
    import json

    lines: list[str] = []
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        text = str(row.get("text") or "").strip()
        if not text:
            continue
        lines.append(
            json.dumps(
                {
                    "course": shortname,
                    "passage_id": ocr_passage_id(shortname, row),
                    "filename": str(row.get("filename") or ""),
                    "ref": str(row.get("ref") or ""),
                    "locator": str(row.get("locator") or ""),
                    "text": text,
                    "citable": False,
                    "status": "pending_signoff",
                    "signoff": str(row.get("signoff") or "arabic"),
                },
                ensure_ascii=False,
            )
        )
    (path / f"{shortname}.jsonl").write_text(
        "\n".join(lines) + ("\n" if lines else ""), encoding="utf-8"
    )
    return len(lines)


def _read_jsonl(path: Path) -> list[dict]:
    import json

    if not path.is_file():
        return []
    out: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("{"):
            out.append(json.loads(line))
    return out


def load_ocr_pending(shortname: str, *, root: str | os.PathLike[str] | None = None) -> list[dict]:
    """Read the stored pending-OCR rows for one course (never citable as-is)."""
    base = Path(root) if root is not None else _OCR_ROOT
    return _read_jsonl(base / f"{shortname}.jsonl")


def load_ocr_signoffs(shortname: str, *, root: str | os.PathLike[str] | None = None) -> list[dict]:
    """Read the recorded human sign-off lines for one course."""
    base = Path(root) if root is not None else _OCR_SIGNOFF_ROOT
    return _read_jsonl(base / f"{shortname}.jsonl")


def record_ocr_signoff(
    shortname: str,
    *,
    passage_ids: list[str],
    source_doc: str,
    who: str,
    when: str | None = None,
    note: str = "",
    root: str | os.PathLike[str] | None = None,
    pending_root: str | os.PathLike[str] | None = None,
) -> dict:
    """Record a staff human sign-off of exact Arabic OCR passages.

    Staff-initiated and auditable: it requires a named ``who``, a
    ``source_doc`` (the document the reviewer read), and one or more
    ``passage_ids``. Only ids that exist in the pending store are recorded; an
    unknown id is reported and never signed. Nothing here is automatic — the
    function must be called explicitly with the exact ids and writes an
    append-only line carrying the quote's sha256, so a later edit of the stored
    text invalidates the sign-off instead of silently quoting something else.
    """
    name = str(shortname or "").strip()
    if name not in listed_shortnames():
        return {"ok": False, "error": "off_list", "recorded": 0, "unknown": [], "path": None}

    signer = str(who or "").strip()
    source = str(source_doc or "").strip()
    ids = [str(pid).strip() for pid in (passage_ids or []) if str(pid).strip()]
    if not signer:
        return {"ok": False, "error": "missing_who", "recorded": 0, "unknown": [], "path": None}
    if not source:
        return {"ok": False, "error": "missing_source_doc", "recorded": 0, "unknown": [], "path": None}
    if not ids:
        return {"ok": False, "error": "missing_passage_ids", "recorded": 0, "unknown": [], "path": None}

    pending = {
        str(row.get("passage_id") or ocr_passage_id(name, row)): row
        for row in load_ocr_pending(name, root=pending_root)
    }
    unknown = [pid for pid in ids if pid not in pending]
    valid = [pid for pid in ids if pid in pending]

    signoff_root = Path(root) if root is not None else _OCR_SIGNOFF_ROOT
    signoff_root.mkdir(parents=True, exist_ok=True)
    path = signoff_root / f"{name}.jsonl"

    import json

    already = {
        str(rec.get("passage_id") or "")
        for rec in load_ocr_signoffs(name, root=signoff_root)
    }
    recorded = 0
    with open(path, "a", encoding="utf-8") as fh:
        for pid in valid:
            if pid in already:
                continue
            fh.write(
                json.dumps(
                    {
                        "course": name,
                        "action": "sign_off",
                        "passage_id": pid,
                        "text_sha256": _text_sha256(str(pending[pid].get("text") or "")),
                        "who": signer,
                        "when": when or datetime.now(timezone.utc).isoformat(),
                        "source_doc": source,
                        "note": str(note or ""),
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )
            already.add(pid)
            recorded += 1
    return {"ok": True, "recorded": recorded, "unknown": unknown, "path": str(path)}


def signed_ocr_rows(
    shortname: str,
    *,
    pending_root: str | os.PathLike[str] | None = None,
    signoff_root: str | os.PathLike[str] | None = None,
) -> list[dict]:
    """Pending OCR rows with ``citable`` flipped ONLY where a sign-off matches.

    A row becomes citable only when a recorded sign-off names its exact
    ``passage_id`` *and* the stored quote's sha256 still matches the signed
    digest. Every other row stays ``citable=False`` / ``pending_signoff``, so
    unsigned Arabic can never leak into a cite and a sign-off cannot cross over
    to different text or a different course.
    """
    name = str(shortname or "").strip()
    pending = load_ocr_pending(name, root=pending_root)
    signoffs: dict[str, dict] = {}
    for rec in load_ocr_signoffs(name, root=signoff_root):
        if str(rec.get("action") or "") == "sign_off":
            signoffs[str(rec.get("passage_id") or "")] = rec

    rows: list[dict] = []
    for row in pending:
        pid = str(row.get("passage_id") or ocr_passage_id(name, row))
        rec = signoffs.get(pid)
        signed = bool(rec) and str(rec.get("text_sha256") or "") == _text_sha256(row.get("text"))
        out = dict(row)
        out["passage_id"] = pid
        out["citable"] = signed
        out["status"] = "signed_off" if signed else "pending_signoff"
        if signed:
            out["signoff_ref"] = {
                "who": rec.get("who"),
                "when": rec.get("when"),
                "source_doc": rec.get("source_doc"),
            }
        rows.append(out)
    return rows


def ocr_signoff_status(
    shortname: str,
    *,
    pending_root: str | os.PathLike[str] | None = None,
    signoff_root: str | os.PathLike[str] | None = None,
) -> dict:
    """Counts + the exact citable passage ids after consuming sign-offs."""
    rows = signed_ocr_rows(name := str(shortname or "").strip(), pending_root=pending_root, signoff_root=signoff_root)
    signed = [row for row in rows if row.get("citable")]
    return {
        "course": name,
        "pending": len(rows) - len(signed),
        "signed_off": len(signed),
        "citable_passage_ids": [row["passage_id"] for row in signed],
    }


def signed_ocr_passages(
    shortname: str,
    *,
    pending_root: str | os.PathLike[str] | None = None,
    signoff_root: str | os.PathLike[str] | None = None,
) -> dict[str, dict]:
    """Signed OCR rows as additive passage dicts for the chunk index.

    These are consumed only by the staff Index job and merged into the
    *keyword index* (additive, never a door). An unsigned passage never appears.
    """
    name = str(shortname or "").strip()
    out: dict[str, dict] = {}
    for row in signed_ocr_rows(name, pending_root=pending_root, signoff_root=signoff_root):
        if not row.get("citable"):
            continue
        pid = f"{name}:ocr-signed:{row['passage_id']}"
        out[pid] = {
            "id": pid,
            "course": name,
            "kind": "ocr",
            "activity_id": None,
            "name": str(row.get("filename") or row.get("ref") or "ocr"),
            "text": str(row.get("text") or ""),
        }
    return out


def _drive_results(shortname: str, payload: dict) -> list[dict]:
    """Attempt each unread Drive ref through the default-OFF acquire path."""
    refs = payload.get("drive_refs")
    if not isinstance(refs, list) or not refs:
        if not payload.get("drive"):
            return []
        refs = ingest.unread_drive_refs(shortname)
    results: list[dict] = []
    for ref in refs:
        job = acquire.drive_acquire(
            str(ref),
            trigger=acquire.INDEX_TRIGGER,
            reader=ingest.read_path,
        )
        results.append(
            {
                "ref": job.get("ref") or str(ref),
                "status": job.get("status"),
                "error": job.get("error"),
                "local_path": job.get("local_path"),
            }
        )
    return results


def run_index(shortname: str, payload: dict | None = None) -> dict:
    """Run one staff Index job for one listed course. Never touches a turn path."""
    payload = payload if isinstance(payload, dict) else {}
    name = str(shortname or "").strip()
    if name not in listed_shortnames():
        return {
            "ok": False,
            "error": "off_list",
            "shortname": name,
            "indexed": 0,
            "skipped": ["drive", "youtube"],
        }

    indexed, source = _extra_indexed(name, payload)
    requested = payload.get("build")
    build_requested = set(requested) if isinstance(requested, (list, tuple, set)) else set()

    result: dict = {"ok": True, "indexed": indexed, "extra_source": source}

    if "index" in build_requested:
        result["index"] = ingest.build_course_index(
            name,
            index_root=_INDEX_ROOT,
            extra_passages=signed_ocr_passages(name),
        )
    if "graph" in build_requested:
        result["graph"] = ingest.build_course_graph(name, graph_root=_GRAPH_ROOT)
    if "ocr" in build_requested:
        # Consume recorded human sign-offs: only signed ids become citable.
        result["ocr"] = ocr_signoff_status(name)

    drive = _drive_results(name, payload)
    if drive:
        result["drive"] = drive
        result["skipped"] = ["youtube"]
    else:
        result["skipped"] = ["drive", "youtube"]
    web = _web_results(name, payload)
    if web:
        result["web"] = web
    return result


def _web_results(shortname: str, payload: dict) -> list[dict]:
    """Attempt each web/media ref through the default-OFF remote capture path."""
    refs = payload.get("web_refs")
    if not isinstance(refs, list) or not refs:
        return []
    results: list[dict] = []
    for ref in refs:
        job = acquire.web_acquire(
            str(ref),
            trigger=acquire.INDEX_TRIGGER,
            reader=ingest.read_path,
        )
        results.append(
            {
                "ref": job.get("ref") or str(ref),
                "status": job.get("status"),
                "error": job.get("error"),
                "local_path": job.get("local_path"),
            }
        )
    return results


__all__ = [
    "run_index",
    "record_ocr_pending",
    "record_ocr_signoff",
    "load_ocr_pending",
    "load_ocr_signoffs",
    "signed_ocr_rows",
    "signed_ocr_passages",
    "ocr_signoff_status",
    "ocr_passage_id",
    "index_roots",
]
