#!/usr/bin/env python3
"""Build Nibras agentic QA workbook (3 sheets: Employee, HR, Manager)."""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

OUT = Path(__file__).with_name("Nibras-Agentic-QA-Checklist.xlsx")

HEADERS = [
    "ID",
    "Area",
    "Surface",
    "Priority",
    "Scenario (EN)",
    "Scenario (AR)",
    "Steps / Utterance (EN)",
    "Steps / Utterance (AR)",
    "Expected (EN)",
    "Expected (AR)",
    "Persona",
    "Pass / Fail",
    "Notes",
]

THIN = Border(
    left=Side(style="thin", color="CBD5E1"),
    right=Side(style="thin", color="CBD5E1"),
    top=Side(style="thin", color="CBD5E1"),
    bottom=Side(style="thin", color="CBD5E1"),
)

# (id, area, surface, priority, scen_en, scen_ar, steps_en, steps_ar, exp_en, exp_ar, persona)

EMPLOYEE = [
    # ── Setup / login ──────────────────────────────────────────────────────
    ("E-001", "Setup", "Browser", "P0",
     "Login as regular employee",
     "تسجيل دخول موظف عادي",
     "Open app → login emp_1067 / mozafNibrasPa_132",
     "افتح التطبيق → دخول emp_1067 / mozafNibrasPa_132",
     "Lands on My / Pulse; employee name visible; no People admin nav",
     "يفتح My/Pulse؛ يظهر اسم الموظف؛ بدون قائمة People الإدارية",
     "emp_1067"),
    ("E-002", "Setup", "Browser", "P0",
     "Wrong password is rejected",
     "رفض كلمة مرور خاطئة",
     "Login emp_1067 with wrong password",
     "دخول emp_1067 بكلمة مرور خاطئة",
     "Clear error; no session created",
     "رسالة خطأ واضحة؛ لا جلسة",
     "emp_1067"),
    ("E-003", "Setup", "Browser", "P1",
     "Password autofill trap (11 vs 12 chars)",
     "فخ التعبئة التلقائية لكلمة المرور",
     "Clear password field; type AdminPa_132 vs mozafNibrasPa_132 manually",
     "امسح حقل كلمة المرور واكتب يدوياً",
     "Employee password works; do not use EduOS/Nibras admin passwords",
     "كلمة مرور الموظف تعمل؛ لا تستخدم كلمات مرور الأدمن",
     "emp_1067"),

    # ── Profile / identity reads ───────────────────────────────────────────
    ("E-010", "Profile", "Pulse Chat", "P0",
     "Who am I (EN)",
     "من أنا (إنجليزي)",
     "Who am I?",
     "Who am I?",
     "Returns own name, employee no, org unit, manager — grounded from get_my_profile",
     "يعيد الاسم ورقم الموظف والوحدة والمدير من get_my_profile",
     "emp_1067"),
    ("E-011", "Profile", "Pulse Chat", "P0",
     "Who am I (AR)",
     "من أنا (عربي)",
     "من أنا؟ بياناتي",
     "من أنا؟ بياناتي",
     "Same grounded profile in Arabic reply; no invented fields",
     "نفس البيانات الحقيقية بالعربي؛ بلا حقول مخترعة",
     "emp_1067"),
    ("E-012", "Profile", "My App", "P0",
     "My dashboard shows profile card",
     "لوحة My تعرض بطاقة الملف",
     "Open /my",
     "افتح /my",
     "Profile summary matches get_my_profile",
     "الملخص يطابق get_my_profile",
     "emp_1067"),
    ("E-013", "Profile", "Pulse Chat", "P1",
     "Ask for basic salary via profile (not payslip)",
     "السؤال عن الراتب الأساسي",
     "What is my basic salary? / راتبي الأساسي؟",
     "راتبي الأساسي؟",
     "Answer from profile if CBAC allows; never invent; never use list_my_payslips for basic pay",
     "من الملف إن سُمح؛ بدون اختراع؛ لا يستخدم قسائم الراتب للراتب الأساسي",
     "emp_1067"),

    # ── Leave balance ──────────────────────────────────────────────────────
    ("E-020", "Leave · Read", "Pulse Chat", "P0",
     "Leave balance (EN)",
     "رصيد الإجازة (إنجليزي)",
     "How much leave do I have left?",
     "How much leave do I have left?",
     "Calls get_my_leave_balance; shows entitled/used/pending/remaining by type",
     "يستدعي get_my_leave_balance ويعرض الرصيد حسب النوع",
     "emp_1067"),
    ("E-021", "Leave · Read", "Pulse Chat", "P0",
     "Leave balance (AR)",
     "رصيد الإجازة (عربي)",
     "رصيد اجازاتي",
     "رصيد اجازاتي",
     "Same tool; Arabic labels for leave types (سنوية/عارضة/مرضية)",
     "نفس الأداة؛ تسميات عربية لأنواع الإجازة",
     "emp_1067"),
    ("E-022", "Leave · Read", "Pulse Chat", "P1",
     "Self-heal: leave_balance entity miss → get_my_leave_balance",
     "التعافي الذاتي لرصيد الإجازة",
     "Ask balance in a way that might trigger get_entity_details('leave_balance')",
     "اسأل عن الرصيد بصيغة عامة",
     "Must NOT dead-end with Entity not found; repairs to live balance API",
     "لا يتوقف عند Entity not found؛ يصلح إلى واجهة الرصيد",
     "emp_1067"),
    ("E-023", "Leave · Read", "My App", "P0",
     "Leave page balance cards",
     "بطاقات الرصيد في صفحة الإجازة",
     "Open /my/leave",
     "افتح /my/leave",
     "Balance cards match chat numbers",
     "البطاقات تطابق أرقام المحادثة",
     "emp_1067"),
    ("E-024", "Leave · Read", "Pulse Chat", "P0",
     "List my leave history",
     "سجل إجازاتي",
     "Show my leave / اجازاتي",
     "اجازاتي",
     "list_my_leave only (own records); never org-wide leave list",
     "list_my_leave فقط؛ لا قائمة إجازات المؤسسة",
     "emp_1067"),

    # ── Leave submit happy paths ───────────────────────────────────────────
    ("E-030", "Leave · Submit", "Pulse Chat", "P0",
     "Annual leave tomorrow (EN) — Chat handoff only",
     "إجازة سنوية غداً EN — توجيه فقط",
     "I want one day annual leave tomorrow.",
     "I want one day annual leave tomorrow.",
     "G2: no pending_exec. Direct to Agent process and/or My. No Chat Confirm for host write.",
     "لا pending_exec. توجيه Agent أو My. بلا تأكيد Chat للكتابة",
     "emp_1067"),
    ("E-031", "Leave · Submit", "Pulse Chat", "P0",
     "Annual leave tomorrow (AR) — Chat must NOT stage",
     "إجازة عادية غداً — Chat لا يُجهّز كتابة",
     "اريد اجازة, ليوم واحد غدا, عادي.",
     "اريد اجازة, ليوم واحد غدا, عادي.",
     "G2/ADR-0046: NO pending_exec. Handoff to Agent (leave.request.lifecycle) and/or My /my/leave. May draft/advise. Banner alone after staging = FAIL (staging should not happen).",
     "لا pending_exec. توجيه إلى Agent أو My. المسودة مسموحة. التجهيز في Chat = فشل G2",
     "emp_1067"),
    ("E-031b", "Leave · Submit", "Pulse Agent", "P0",
     "Annual leave tomorrow via Agent process",
     "إجازة عادية غداً عبر Agent",
     "Switch to Agent → plan/run leave for myself tomorrow annual 1 day → confirm on Run",
     "Agent → خطة إجازة غداً عادية يوم واحد → تأكيد في Run",
     "Stages submit_my_leave; Confirm on Agent Run/drawer; then Correspondence awaiting manager — not auto-approved",
     "يُجهّز في Agent؛ تأكيد Run؛ مراسلة بانتظار المدير",
     "emp_1067"),
    ("E-031c", "Leave · Submit", "My App", "P0",
     "Annual leave tomorrow via My ESS (host Plane A)",
     "إجازة عبر My (مسار المضيف)",
     "/my/leave → new request annual tomorrow 1 day → submit",
     "/my/leave → طلب سنوية غداً يوم → تقديم",
     "Host submit + Correspondence submitted; no Pulse Chat pending_exec required",
     "تقديم مضيف + مراسلة submitted",
     "emp_1067"),
    ("E-032", "Leave · Submit", "Pulse Agent", "P0",
     "Confirm staged leave on Agent Run",
     "تأكيد الإجازة في Agent Run",
     "After Agent stages leave: Approve on Run / drawer",
     "بعد تجهيز Agent: اعتمد في Run",
     "Executes host write; Correspondence submitted awaiting manager — not Chat bubble Confirm",
     "ينفّذ؛ مراسلة submitted؛ ليس تأكيد فقاعة Chat",
     "emp_1067"),
    ("E-033", "Leave · Submit", "Pulse Agent", "P1",
     "Agent affirmation / Approve after proposal",
     "تأكيد Agent بعد العرض",
     "On Agent Run consent: Approve (or allowed steer affirmation)",
     "في Run: اعتمد",
     "Only Agent consent completes the Pulse-originated write",
     "موافقة Agent فقط تُكمل الكتابة من Pulse",
     "emp_1067"),
    ("E-034", "Leave · Submit", "Pulse Agent", "P0",
     "Emergency leave via عارضة (Agent)",
     "إجازة عارضة عبر Agent",
     "Agent: اريد اجازة عارضة غدا يوم واحد → confirm on Run",
     "Agent: اريد اجازة عارضة غدا يوم واحد → تأكيد Run",
     "Resolves emergency; stages in Agent; Confirm on Run — Chat must not stage",
     "emergency؛ تجهيز Agent؛ Chat لا يُجهّز",
     "emp_1067"),
    ("E-035", "Leave · Submit", "Pulse Chat", "P0",
     "Sick leave synonym مرضية",
     "إجازة مرضية",
     "اجازة مرضية يومين من بكرة",
     "اجازة مرضية يومين من بكرة",
     "leave_type=sick; dates from بكرة; days=2",
     "sick؛ من بكرة؛ يومان",
     "emp_1067"),
    ("E-036", "Leave · Submit", "Pulse Chat", "P0",
     "Named calendar date: 1 أكتوبر القادم",
     "تاريخ مسمّى: 1 أكتوبر القادم",
     "اريد تقديم طلب اجازه عادية لمدة يوم واحد. 1 اكتوبر القادم",
     "اريد تقديم طلب اجازه عادية لمدة يوم واحد. 1 اكتوبر القادم",
     "start_date = next Oct 1 (current/next year, NOT 2023); grounded via write_slots",
     "تاريخ 1 أكتوبر القادم (ليس 2023)",
     "emp_1067"),
    ("E-037", "Leave · Submit", "Pulse Chat", "P1",
     "Multi-turn: type then date then affirm",
     "محادثة متعددة الأدوار",
     "1) اريد اجازة 2) عادي 3) غدا يوم واحد 4) ايوة",
     "1) اريد اجازة 2) عادي 3) غدا يوم واحد 4) ايوة",
     "Asks ONE missing piece at a time OR stages when complete; final ايوة confirms",
     "يسأل عن الناقص واحداً واحداً أو يُجهّز عند الاكتمال",
     "emp_1067"),
    ("E-038", "Leave · Submit", "Pulse Chat", "P0",
     "Must NOT deflect mutation",
     "عدم رفض التقديم",
     "اريد اجازة, ليوم واحد غدا, عادي.",
     "اريد اجازة, ليوم واحد غدا, عادي.",
     "Never: cannot submit / complete confirmation in host system first / use another channel",
     "ممنوع: لا أستطيع التقديم / أكمل التأكيد في النظام أولاً",
     "emp_1067"),
    ("E-039", "Leave · Submit", "Pulse Agent", "P0",
     "Agent plan leave.request.lifecycle for myself",
     "خطة Agent لطلب إجازة",
     "Create task / plan: submit annual leave tomorrow for myself",
     "اعمل task / خطة: إجازة عادية غداً لنفسي",
     "Plan binds submit_my_leave (not create_leave_record); step consent drawer; confirm stages then executes",
     "تربط submit_my_leave؛ درج موافقة؛ تأكيد ثم تنفيذ",
     "emp_1067"),
    ("E-040", "Leave · Submit", "Pulse Agent", "P0",
     "Agent step detail drawer (not blank form)",
     "درج تفاصيل الخطوة (بدون نموذج فارغ)",
     "Select awaiting-consent leave step on Run timeline",
     "اختر خطوة الموافقة في الجدول الزمني",
     "Collapsible side drawer; summary when fields complete OR one simple question if missing — no blank multi-field form on timeline",
     "درج جانبي؛ ملخص أو سؤال واحد؛ بلا نموذج فارغ على الخط الزمني",
     "emp_1067"),
    ("E-041", "Leave · Submit", "My App", "P0",
     "Submit leave from My UI",
     "تقديم إجازة من My",
     "/my or /my/leave → New leave request → annual, tomorrow, 1 day → submit",
     "/my أو /my/leave → طلب جديد → سنوية، غداً، يوم",
     "Creates LeaveRecord + Correspondence; status submitted; visible in /my/requests",
     "يُنشئ السجل والمراسلة؛ submitted؛ يظهر في طلباتي",
     "emp_1067"),
    ("E-042", "Leave · Submit", "My App", "P1",
     "Track request after submit",
     "متابعة الطلب بعد التقديم",
     "Open /my/requests → open latest leave",
     "افتح /my/requests → آخر إجازة",
     "Shows reference no, status submitted/in_review, approver chain with Manager (or HR fallback)",
     "رقم مرجعي، حالة، سلسلة موافقة",
     "emp_1067"),

    # ── Leave denials / edges ──────────────────────────────────────────────
    ("E-050", "Leave · Edge", "Pulse Chat", "P0",
     "Insufficient balance",
     "رصيد غير كافٍ",
     "Request more days than remaining for a type",
     "اطلب أياماً أكثر من المتبقي",
     "Host 400 insufficient_balance; recovery message with remaining + suggestion; nothing submitted",
     "insufficient_balance؛ رسالة مع المتبقي؛ لم يُقدَّم شيء",
     "emp_1067"),
    ("E-051", "Leave · Edge", "Pulse Chat", "P0",
     "Overlap with existing leave",
     "تداخل مع إجازة موجودة",
     "Request dates that overlap an existing approved/pending leave",
     "تواريخ تتداخل مع إجازة موجودة",
     "error_kind=overlap; hints with overlapping range; nothing submitted",
     "overlap؛ تلميحات بالتداخل؛ لم يُقدَّم شيء",
     "emp_1067"),
    ("E-052", "Leave · Edge", "Pulse Chat", "P0",
     "Unknown leave type",
     "نوع إجازة غير معروف",
     "Request leave type purple / نوع وهمي",
     "إجازة purple",
     "invalid_leave_type with allowed_types hints; recovery asks to pick a type",
     "invalid_leave_type مع الأنواع المسموحة",
     "emp_1067"),
    ("E-053", "Leave · Edge", "Pulse Chat", "P0",
     "Past date far beyond backdate window",
     "تاريخ قديم جداً",
     "If model stages 2023-10-01 without grounding, host must reject OR write_slots rolls forward before stage",
     "تاريخ 2023 أو قديم جداً",
     "Either rolled to next occurrence at staging OR host invalid_dates (>30 days past)",
     "إما يُصحَّح للأمام أو يُرفض invalid_dates",
     "emp_1067"),
    ("E-054", "Leave · Edge", "Pulse Chat", "P1",
     "Missing piece: ask one question",
     "ناقص معلومة: سؤال واحد",
     "اريد اجازة (no type/date)",
     "اريد اجازة",
     "Asks ONE short question (type OR date) — not a blank multi-field form dump",
     "سؤال قصير واحد؛ بلا نموذج متعدد الحقول فارغ",
     "emp_1067"),
    ("E-055", "Leave · Edge", "Pulse Chat", "P1",
     "Decline / cancel staged confirmation",
     "رفض بطاقة التأكيد",
     "Stage leave then Decline on card",
     "جهّز ثم ارفض البطاقة",
     "Nothing written; pending cleared; polite acknowledgement",
     "لا كتابة؛ أُلغي الانتظار",
     "emp_1067"),
    ("E-056", "Leave · Edge", "Pulse Chat", "P1",
     "ايه alone is NOT yes (Egyptian what?)",
     "ايه وحدها ليست تأكيداً",
     "After a proposal: ايه",
     "بعد عرض: ايه",
     "Must NOT treat as affirmation; may clarify or re-ask",
     "ليست تأكيداً؛ قد يوضح أو يعيد السؤال",
     "emp_1067"),
    ("E-057", "Leave · Edge", "Pulse Chat", "P0",
     "No auto-approve of manager workflow",
     "عدم الموافقة التلقائية على سير العمل",
     "After successful leave submit as emp_1067 (has manager emp_1712)",
     "بعد تقديم ناجح",
     "Correspondence status=submitted (not approved); Manager step NOT Skipped(auto); awaits emp_1712",
     "submitted وليس approved؛ خطوة المدير ليست SKIPPED AUTO",
     "emp_1067"),
    ("E-058", "Leave · Edge", "Pulse Chat", "P1",
     "Balance check then continue to submit",
     "رصيد ثم متابعة التقديم",
     "1) رصيد 2) عارضة لو في رصيد 3) continue to stage",
     "رصيد ثم عارضة لو متاح",
     "May check balance first but MUST NOT stop at balance when user wants to submit",
     "يجوز فحص الرصيد لكن لا يتوقف عنده إذا أراد التقديم",
     "emp_1067"),

    # ── Loans ──────────────────────────────────────────────────────────────
    ("E-070", "Loan", "Pulse Chat", "P0",
     "List my loans",
     "قائمة قروضي",
     "Show my loans / قروضي",
     "قروضي",
     "list_my_loans own only",
     "list_my_loans فقط",
     "emp_1067"),
    ("E-071", "Loan", "Pulse Chat", "P0",
     "Submit emergency loan (AR)",
     "طلب قرض طوارئ",
     "اريد قرض طوارئ بمبلغ … يبدأ … لمدة … شهر",
     "اريد قرض طوارئ …",
     "Stages submit_my_loan (not leave); consent card; corr manager then finance",
     "submit_my_loan؛ موافقة؛ مدير ثم مالية",
     "emp_1067"),
    ("E-072", "Loan", "Pulse Chat", "P0",
     "Submit loan (EN) with slots",
     "طلب قرض بالإنجليزي",
     "I want an emergency loan of 2000 starting next month for 6 months",
     "I want an emergency loan of 2000 starting next month for 6 months",
     "loan_type governed; start_date future-grounded; confirm card shows summary",
     "نوع محكوم؛ تاريخ مستقبلي؛ ملخص على البطاقة",
     "emp_1067"),
    ("E-073", "Loan", "Pulse Chat", "P1",
     "Wrong tool: leave vs loan",
     "أداة خاطئة: إجازة بدل قرض",
     "Ask for a loan clearly",
     "اطلب قرضاً بوضوح",
     "Must call submit_my_loan — never submit_my_leave",
     "يجب submit_my_loan وليس leave",
     "emp_1067"),
    ("E-074", "Loan", "My App", "P1",
     "New request loan_request from My",
     "طلب قرض من My",
     "/my → New Request → Loan",
     "/my → طلب جديد → قرض",
     "Creates loan correspondence; appears in /my/requests",
     "مراسلة قرض؛ تظهر في طلباتي",
     "emp_1067"),
    ("E-075", "Loan", "Pulse Chat", "P1",
     "Missing loan principal → one question",
     "ناقص مبلغ القرض",
     "اريد قرض طوارئ (no amount)",
     "اريد قرض طوارئ",
     "Asks for principal (or required slot) once — does not invent amount",
     "يسأل عن المبلغ؛ لا يخترع",
     "emp_1067"),

    # ── Attendance permission ──────────────────────────────────────────────
    ("E-080", "Attendance", "Pulse Chat", "P0",
     "Submit short-hours permission (AR)",
     "إذن حضور ساعات",
     "إذن حضور ساعتين غداً شخصي",
     "إذن حضور ساعتين غداً شخصي",
     "submit_my_attendance_permission; type personal|medical|official|emergency; consent",
     "submit_my_attendance_permission؛ موافقة",
     "emp_1067"),
    ("E-081", "Attendance", "Pulse Chat", "P0",
     "Submit attendance permission (EN)",
     "إذن حضور (إنجليزي)",
     "I need a short-hours attendance permission tomorrow for personal reasons",
     "I need a short-hours attendance permission tomorrow for personal reasons",
     "Stages correct API; not leave tool",
     "الأداة الصحيحة؛ ليست إجازة",
     "emp_1067"),
    ("E-082", "Attendance", "My App", "P0",
     "Attendance page list + request",
     "صفحة الإذن قائمة + طلب",
     "Open /my/attendance → request → submit",
     "افتح /my/attendance",
     "History shows own rows; new request creates corr awaiting manager",
     "السجل شخصي؛ الطلب ينتظر المدير",
     "emp_1067"),
    ("E-083", "Attendance", "Pulse Chat", "P1",
     "List my attendance permissions",
     "اذونات الحضور الخاصة بي",
     "اذونات الحضور / my attendance permissions",
     "اذونات الحضور",
     "list_my_attendance_permissions only",
     "قائمة ذاتية فقط",
     "emp_1067"),

    # ── Payslips ───────────────────────────────────────────────────────────
    ("E-090", "Payslip", "Pulse Chat", "P0",
     "Show my payslips",
     "قسائم راتبي",
     "Show my payslip / قسيمة راتبي",
     "قسيمة راتبي",
     "list_my_payslips; only committed/validated lines; CBAC-honest if empty",
     "قسائم معتمدة فقط؛ صدق CBAC إن فارغ",
     "emp_1067"),
    ("E-091", "Payslip", "My App", "P1",
     "Dashboard payslip card",
     "بطاقة القسيمة في اللوحة",
     "Open /my dashboard",
     "افتح /my",
     "Payslip section matches chat data",
     "يطابق بيانات المحادثة",
     "emp_1067"),

    # ── Profile change / other corr ────────────────────────────────────────
    ("E-100", "Profile change", "My App", "P1",
     "Request profile change",
     "طلب تعديل بيانات",
     "/my → New Request → Profile change → safe field (e.g. phone)",
     "/my → طلب تعديل بيانات",
     "Correspondence → HR approve path; spoof salary/org/manager rejected",
     "يذهب لـ HR؛ رفض تزوير راتب/وحدة/مدير",
     "emp_1067"),
    ("E-101", "Correspondence", "My App", "P2",
     "Internal memo (if org_unit set)",
     "مذكرة داخلية",
     "New Request → Internal memo",
     "طلب → مذكرة داخلية",
     "Requires org unit; any_admin acknowledge path",
     "يتطلب وحدة؛ مسار any_admin",
     "emp_1067"),
    ("E-102", "Correspondence", "My App", "P0",
     "Cancel own draft/submitted when allowed",
     "إلغاء طلبي",
     "Open own request → Cancel if available",
     "افتح طلبي → إلغاء",
     "Status cancelled; managers notified if pending",
     "cancelled؛ إشعار إن وُجد موافِق",
     "emp_1067"),

    # ── Memory / advisory / guards ─────────────────────────────────────────
    ("E-110", "Memory", "Pulse Chat", "P1",
     "Learn a fact (confirm)",
     "تعلّم معلومة",
     "Remember that I prefer annual leave on Thursdays",
     "تذكر أني أفضل الإجازة السنوية يوم الخميس",
     "Proposes learn_fact → user confirm → stored; never claims memory unavailable",
     "يقترح ثم يؤكد؛ لا يقول الذاكرة غير متاحة",
     "emp_1067"),
    ("E-111", "Advisory", "Pulse Chat", "P1",
     "Explain leave process (read-only)",
     "شرح عملية الإجازة",
     "How does leave approval work? / كيف تتم الموافقة على الإجازة؟",
     "كيف تتم الموافقة على الإجازة؟",
     "Advisory answer; no silent write; may stage only if user asks to submit",
     "إجابة إرشادية؛ بلا كتابة صامتة",
     "emp_1067"),
    ("E-112", "Guard", "Pulse Chat", "P0",
     "Out of scope: carbon / emissions",
     "خارج النطاق: انبعاثات",
     "What is our carbon footprint?",
     "ما هو أثرنا الكربوني؟",
     "Topic guard refuses; Nibras HR scope only",
     "الرفض حسب الحارس؛ نطاق موارد بشرية فقط",
     "emp_1067"),
    ("E-113", "Guard", "Pulse Chat", "P1",
     "Cannot access other employee's leave",
     "لا يرى إجازة موظف آخر",
     "Show leave for emp_1001 / رصيد فلان",
     "رصيد إجازة موظف آخر",
     "Denied or scoped to self; no cross-employee leak",
     "مرفوض أو ذاتي فقط؛ بلا تسريب",
     "emp_1067"),
    ("E-114", "Guard", "Pulse Chat", "P1",
     "Cannot run payroll as employee",
     "لا يشغّل الرواتب كموظف",
     "Compute payroll for this month",
     "احسب رواتب هذا الشهر",
     "Refuse / no access; payroll is HR Agent surface",
     "رفض؛ الرواتب لـ HR",
     "emp_1067"),
    ("E-115", "RTL", "Pulse Chat", "P1",
     "Arabic reply quality",
     "جودة الرد بالعربية",
     "Any Arabic leave question",
     "أي سؤال إجازة بالعربي",
     "Readable Arabic; no raw method/path jargon in user text (RULE_23)",
     "عربي مقروء؛ بلا jargon مسارات API",
     "emp_1067"),
    ("E-116", "Consent", "Pulse Chat", "P0",
     "Staged body visible on confirm card",
     "محتوى الطلب ظاهر على البطاقة",
     "Stage leave with type+dates+days",
     "جهّز إجازة كاملة",
     "Card shows human summary (type, dates, days) — not empty body / not POST /path",
     "ملخص بشري؛ ليس body فارغ أو POST/مسار",
     "emp_1067"),
    ("E-117", "Consent", "Pulse Agent", "P1",
     "Discuss plan then Fork/Replan only when asked",
     "مناقشة الخطة ثم Fork عند الطلب",
     "DISCUSSION ONLY then later نعم كمل / عدل الخطة",
     "مناقشة ثم كمل / عدل",
     "Discussion does not mutate plan until Fork/Replan; affirmation after edit offer resumes correctly",
     "المناقشة لا تغيّر الخطة حتى Fork؛ التأكيد يستأنف",
     "emp_1067"),
]

HR = [
    ("H-001", "Setup", "Browser", "P0",
     "Login as brand admin / HR",
     "دخول أدمن/HR",
     "Login admin / AdmNibras_132 (or ahmed / AdminPa_132 for superuser)",
     "دخول admin / AdmNibras_132 أو ahmed",
     "People app visible; can open /people",
     "تطبيق People ظاهر",
     "admin"),
    ("H-002", "Setup", "Browser", "P0",
     "Superuser ahmed password",
     "كلمة مرور ahmed",
     "ahmed / AdminPa_132 (11 chars — clear autofill)",
     "ahmed / AdminPa_132",
     "Logs in; is_superuser capabilities",
     "دخول ناجح بصلاحيات كاملة",
     "ahmed"),

    # People home / employees
    ("H-010", "Employees", "People App", "P0",
     "People home loads",
     "صفحة People الرئيسية",
     "Open /people",
     "افتح /people",
     "Modules: employees, leave, payroll, loans, policies (soft counts)",
     "الوحدات تظهر مع الأعداد",
     "admin"),
    ("H-011", "Employees", "People App", "P0",
     "Employee list search",
     "بحث قائمة الموظفين",
     "/people/employees → search 1067",
     "/people/employees → ابحث 1067",
     "Finds Bilagot / emp_1067; manager column shows emp_1712 if assigned",
     "يجد الموظف والمدير إن وُجد",
     "admin"),
    ("H-012", "Employees", "People App", "P0",
     "Employee 360 profile",
     "ملف 360",
     "Open /people/employees/:id for emp_1067",
     "افتح ملف emp_1067",
     "Tabs load: Profile, Leave, Pay (lazy), Requests; no crash",
     "التبويبات تعمل بلا انهيار",
     "admin"),
    ("H-013", "Employees", "People App", "P1",
     "Filter unassigned manager",
     "تصفية بلا مدير",
     "Employees → filter Unassigned manager",
     "تصفية بدون مدير",
     "Lists employees with manager NULL",
     "يعرض من بلا مدير",
     "admin"),
    ("H-014", "Employees", "People App", "P0",
     "Create employee (wizard)",
     "إنشاء موظف",
     "New employee → fill required → save",
     "موظف جديد → احفظ",
     "Employee created; appears in list",
     "يُنشأ ويظهر في القائمة",
     "admin"),
    ("H-015", "Employees", "People App", "P1",
     "Update employee + activate",
     "تحديث وتفعيل موظف",
     "Edit hire → set active / join date",
     "عدّل وفعّل",
     "update_employee saves; activation reflected",
     "يُحفظ التفعيل",
     "admin"),
    ("H-016", "Employees", "People App", "P1",
     "Assign manager to employee",
     "تعيين مدير لموظف",
     "Set manager on a previously unassigned employee",
     "عيّن مديراً لموظف بلا مدير",
     "Manager saved; subsequent ESS leave from that emp routes to manager (not HR fallback unless vacant)",
     "يُحفظ؛ طلبات ESS تذهب للمدير",
     "admin"),
    ("H-017", "Employees", "Pulse Agent", "P0",
     "Agent onboarding lifecycle",
     "دورة توظيف عبر Agent",
     "Plan employee.onboarding.lifecycle: create then activate",
     "خطة توظيف: إنشاء ثم تفعيل",
     "Binds create_employee / update_employee with consent — never submit_my_leave",
     "create/update_employee بموافقة؛ ليست إجازة",
     "ahmed"),
    ("H-018", "Employees", "Pulse Chat", "P1",
     "Analyze headcount (read)",
     "تحليل عدد الموظفين",
     "How many employees by department? / عدد الموظفين حسب القسم؟",
     "عدد الموظفين حسب القسم؟",
     "analyze_employees / aggregate; grounded numbers; no invent",
     "أرقام من الأدوات؛ بلا اختراع",
     "ahmed"),

    # Leave admin
    ("H-030", "Leave admin", "People App", "P0",
     "Leave records list",
     "قائمة سجلات الإجازة",
     "Open /people/leave",
     "افتح /people/leave",
     "Org leave records + entitlements UI loads",
     "السجلات والاستحقاقات تظهر",
     "admin"),
    ("H-031", "Leave admin", "People App", "P1",
     "Create leave record on behalf (admin)",
     "إنشاء إجازة نيابة",
     "Create leave for named employee via People UI",
     "أنشئ إجازة لموظف مسمّى",
     "create_leave_record path; distinct from ESS submit_my_leave",
     "مسار إداري مختلف عن ESS",
     "admin"),
    ("H-032", "Leave admin", "People App", "P0",
     "Edit entitlements",
     "تعديل الاستحقاقات",
     "Set annual entitlement days for an employee/year",
     "عدّل أيام الاستحقاق السنوي",
     "Saved; ESS balance reflects change",
     "يُحفظ؛ رصيد ESS يتحدث",
     "admin"),
    ("H-033", "Leave admin", "Pulse Chat", "P1",
     "HR lists leave for an employee",
     "HR يسرد إجازات موظف",
     "Show leave records for employee 1067",
     "اعرض إجازات الموظف 1067",
     "Uses list_leave_records / get_employee scoped — not list_my_leave",
     "أدوات إدارية وليست list_my_leave",
     "ahmed"),
    ("H-034", "Leave admin", "People App", "P1",
     "Leave type aliases in MDM",
     "مرادفات نوع الإجازة في MDM",
     "/people/config or Reference → leave_type emergency aliases include عارضة",
     "التحقق من aliases لـ emergency",
     "عارضة/طارئة/casual present; ensure_leave_type_aliases idempotent",
     "المرادفات موجودة",
     "admin"),

    # Loans admin
    ("H-040", "Loans admin", "People App", "P0",
     "Loans list + installments",
     "قائمة القروض والأقساط",
     "Open /people/loans",
     "افتح /people/loans",
     "Loans and schedules visible",
     "القروض والجداول تظهر",
     "admin"),
    ("H-041", "Loans admin", "Pulse Chat", "P1",
     "List org loans",
     "قروض المؤسسة",
     "List open loans",
     "اعرض القروض المفتوحة",
     "list_loans (admin), not list_my_loans",
     "list_loans إداري",
     "ahmed"),

    # Payroll
    ("H-050", "Payroll", "People App", "P0",
     "Payroll runs page",
     "صفحة دورات الرواتب",
     "Open /people/payroll",
     "افتح /people/payroll",
     "Runs list; can open a run",
     "القائمة والتفاصيل تعمل",
     "admin"),
    ("H-051", "Payroll", "People App", "P0",
     "Compute → validate → commit (SoD)",
     "احسب → تحقق → اعتماد",
     "On a draft run: compute, validate, then commit with different approver if SoD required",
     "احسب ثم تحقق ثم اعتمد",
     "Status advances draft→computed→validated→committed; SoD preparer≠approver enforced",
     "تتقدم الحالات؛ فصل الواجبات إن وُجد",
     "ahmed"),
    ("H-052", "Payroll", "Pulse Agent", "P0",
     "Agent payroll.run.lifecycle",
     "دورة رواتب عبر Agent",
     "Plan/run compute_payroll_run → validate → commit with consent each step",
     "خطة رواتب مع موافقة لكل خطوة",
     "Each mutation stages consent; never auto-commits",
     "كل كتابة بموافقة؛ لا اعتماد تلقائي",
     "ahmed"),
    ("H-053", "Payroll", "People App", "P1",
     "Payslip lines for a run",
     "بنود القسائم لدورة",
     "Open /people/payslip filtered by run",
     "افتح القسائم حسب الدورة",
     "list_payslip_lines matches run",
     "يطابق الدورة",
     "admin"),
    ("H-054", "Payroll", "Pulse Chat", "P1",
     "Explain payroll status (read)",
     "شرح حالة الرواتب",
     "What is the status of the latest payroll run?",
     "ما حالة آخر دورة رواتب؟",
     "list/get_payroll_run grounded; no silent commit",
     "قراءة فقط؛ بلا اعتماد صامت",
     "ahmed"),

    # GOSI / WPS
    ("H-060", "GOSI/WPS", "Pulse Agent", "P0",
     "Generate → validate → submit SIF",
     "توليد ثم تحقق ثم إرسال SIF",
     "After committed payroll: generate_gosi_wps_sif → validate → submit (consent each)",
     "بعد اعتماد الرواتب: توليد SIF",
     "Happy path; 409 if payroll not committed",
     "نجاح؛ 409 إن لم تُعتمد الرواتب",
     "ahmed"),
    ("H-061", "GOSI/WPS", "People App", "P1",
     "WPS export from payroll UI",
     "تصدير WPS من الواجهة",
     "Payroll run → export WPS",
     "دورة رواتب → تصدير",
     "File/export generated for committed run",
     "ملف للدورة المعتمدة",
     "admin"),

    # Attendance admin / policies
    ("H-070", "Attendance admin", "People App", "P1",
     "Deep-link attendance admin",
     "حضور إداري (رابط مباشر)",
     "Open /people/attendance if available",
     "افتح /people/attendance",
     "List/create/approve permission ops fallback works; prefer ESS+manager path in prod",
     "يعمل كمسار تشغيلي احتياطي",
     "admin"),
    ("H-071", "Policies", "People App", "P0",
     "Workflow policies visible",
     "سياسات سير العمل",
     "Open /people/policies",
     "افتح /people/policies",
     "Leave policy shows manager step + fallback_role=hr",
     "خطوة مدير + احتياطي HR",
     "admin"),
    ("H-072", "Policies", "People App", "P1",
     "Positions CRUD",
     "المناصب",
     "Open /people/positions → create/edit",
     "المناصب → أنشئ/عدّل",
     "Saves; list refreshes",
     "يُحفظ",
     "admin"),
    ("H-073", "Config", "People App", "P1",
     "Reference data / compensation config",
     "بيانات مرجعية / تعويضات",
     "Open /people/config",
     "افتح /people/config",
     "Reference sets editable; leave_type governed",
     "المراجع قابلة للتعديل",
     "admin"),

    # HR as approver (fallback / profile_change)
    ("H-080", "Approvals", "Team / Inbox", "P0",
     "HR approves profile_change",
     "HR يعتمد تعديل بيانات",
     "Employee submits profile_change → login as admin/HR → approve in inbox/team",
     "موظف يطلب تعديل → HR يعتمد",
     "Status approved; employee sees update path complete",
     "معتمد؛ الموظف يرى اكتمال المسار",
     "admin"),
    ("H-081", "Approvals", "Team / Inbox", "P0",
     "HR fallback when manager vacant",
     "احتياطي HR عند غياب المدير",
     "As employee WITHOUT manager submit leave → admin/ahmed receive as HR fallback",
     "موظف بلا مدير يقدّم إجازة → HR",
     "Chain routed_via=fallback acting_role=hr; NOT auto-approved; admin can Approve",
     "fallback إلى HR؛ ليس موافقة تلقائية",
     "admin"),
    ("H-082", "Approvals", "Team / Inbox", "P1",
     "Routing gap notification if no fallback fill",
     "إشعار فجوة التوجيه",
     "If policy unrouted and no HR holders: admins get routing_gap notice",
     "إن لم يوجد موافق",
     "Notification type routing_gap naming the role",
     "إشعار routing_gap",
     "admin"),
    ("H-083", "Approvals", "Pulse Chat", "P1",
     "HR must not auto-approve without consent",
     "HR لا يعتمد تلقائياً بدون موافقة",
     "Ask Agent to approve all pending leave",
     "اعتمد كل الإجازات المعلقة",
     "Requires explicit act + consent; no bulk silent approve",
     "يحتاج فعلاً صريحاً وموافقة؛ بلا اعتماد صامت جماعي",
     "ahmed"),

    # Certifications / misc
    ("H-090", "Certifications", "People App", "P2",
     "Certifications module",
     "الشهادات",
     "Open /people/certifications",
     "افتح الشهادات",
     "List/CRUD loads without error",
     "يعمل بلا خطأ",
     "admin"),
    ("H-091", "Guard", "Pulse Chat", "P0",
     "HR chat still refuses carbon topic",
     "HR يرفض موضوع الكربون",
     "Calculate CO2 emissions for fleet",
     "احسب انبعاثات الأسطول",
     "Topic guard refuse",
     "رفض حسب الحارس",
     "ahmed"),
    ("H-092", "Nav", "Pulse Agent", "P1",
     "Agent opens People pages",
     "Agent يفتح صفحات People",
     "Open employees / payroll / leave in People",
     "افتح الموظفين / الرواتب / الإجازات",
     "Navigation to /people/* succeeds",
     "التنقل ينجح",
     "ahmed"),
]

MANAGER = [
    ("M-001", "Setup", "Browser", "P0",
     "Login as manager of emp_1067",
     "دخول مدير emp_1067",
     "Login emp_1712 / mozafNibrasPa_132",
     "دخول emp_1712 / mozafNibrasPa_132",
     "Team app accessible; inbox may show pending items",
     "تطبيق Team متاح",
     "emp_1712"),
    ("M-002", "Setup", "Browser", "P0",
     "Alternate manager pair emp_1001→emp_1399",
     "زوج بديل emp_1001→emp_1399",
     "Login emp_1399 / mozafNibrasPa_132",
     "دخول emp_1399",
     "Can see Team inbox for reports including emp_1001",
     "يرى صندوق فريقه",
     "emp_1399"),

    # Inbox
    ("M-010", "Inbox", "Team App", "P0",
     "Team inbox lists only my approvals",
     "صندوق الموافقات لي فقط",
     "Open /team",
     "افتح /team",
     "Only items where user ∈ current_approver_ids; empty if none",
     "فقط ما أنت موافق عليه حالياً",
     "emp_1712"),
    ("M-011", "Inbox", "Team App", "P0",
     "Open request detail",
     "تفاصيل الطلب",
     "Open /team/:id for a leave from emp_1067",
     "افتح طلب إجازة من emp_1067",
     "Summary, workflow graph/stepper, timeline visible",
     "ملخص ورسم سير العمل والخط الزمني",
     "emp_1712"),
    ("M-012", "Inbox", "Team App", "P1",
     "Graph shows Manager current (not SKIPPED AUTO)",
     "الرسم يوضح المدير الحالي",
     "Inspect workflow graph on submitted leave",
     "افحص رسم سير العمل",
     "Manager node = current/pending; NOT Skipped (auto) when manager exists",
     "عقدة المدير حالية؛ ليست تخطي تلقائي",
     "emp_1712"),

    # Approve leave
    ("M-020", "Approve leave", "Team App", "P0",
     "Approve leave from report",
     "اعتماد إجازة مرؤوس",
     "Prep: emp_1067 submits leave → as emp_1712 Approve (comment optional)",
     "بعد تقديم emp_1067 → اعتمد",
     "Status → approved; employee /my/requests shows Approved; leave recorded",
     "معتمد؛ الموظف يرى Approved",
     "emp_1712"),
    ("M-021", "Approve leave", "Team App", "P0",
     "Reject leave with comment",
     "رفض إجازة مع تعليق",
     "Reject → require comment",
     "رفض مع تعليق إلزامي",
     "Status rejected; comment on timeline; CommentRequired if empty",
     "مرفوض؛ التعليق إلزامي",
     "emp_1712"),
    ("M-022", "Approve leave", "Team App", "P0",
     "Send back leave with comment",
     "إرجاع إجازة مع تعليق",
     "Send back → comment required",
     "إرجاع مع تعليق",
     "Status sent_back; employee can resubmit",
     "أُرجع؛ يمكن إعادة التقديم",
     "emp_1712"),
    ("M-023", "Approve leave", "Team App", "P1",
     "Archive terminal request",
     "أرشفة طلب منتهٍ",
     "After approved/rejected → Archive",
     "بعد الاعتماد/الرفض → أرشفة",
     "Status archived",
     "مؤرشف",
     "emp_1712"),
    ("M-024", "Approve leave", "Pulse Chat", "P1",
     "Manager asks pending for me",
     "المدير يسأل عن المعلق",
     "What's pending for my approval? / ما المعلق لدي؟",
     "ما المعلق لدي؟",
     "Lists or guides to /team; no approving without explicit act+consent",
     "يعرض أو يوجّه لـ /team؛ بلا اعتماد صامت",
     "emp_1712"),

    # SoD / self
    ("M-030", "SoD", "Team App", "P0",
     "Cannot approve own leave",
     "لا يعتمد إجازته",
     "As emp_1712 submit own leave then try to approve it",
     "قدّم إجازتك ثم حاول الاعتماد",
     "skip_if_self / NotActorError; not silently approved by self",
     "تخطي ذاتي أو رفض؛ بلا اعتماد ذاتي",
     "emp_1712"),
    ("M-031", "SoD", "Team App", "P0",
     "Outsider cannot approve",
     "غريب لا يعتمد",
     "Login unrelated emp without being current_approver → open URL → Approve",
     "موظف غير موافق → حاول الاعتماد",
     "NotActorError / 403",
     "مرفوض",
     "emp_1009"),

    # Loans / attendance
    ("M-040", "Approve loan", "Team App", "P0",
     "Manager approves loan step 1",
     "المدير يعتمد خطوة القرض 1",
     "emp_1067 submits loan → emp_1712 Approve",
     "بعد قرض emp_1067 → اعتمد",
     "Advances to finance step (not fully approved yet unless finance auto)",
     "ينتقل لخطوة المالية",
     "emp_1712"),
    ("M-041", "Approve loan", "Team App", "P1",
     "Manager without finance cannot finish loan",
     "مدير بلا مالية لا يُنهي القرض",
     "After manager approve, try second approve as same manager if not finance",
     "حاول اعتماد الخطوة الثانية بلا صلاحية مالية",
     "NotActorError until finance-capable user acts",
     "مرفوض حتى مستخدم مالية",
     "emp_1712"),
    ("M-042", "Approve attendance", "Team App", "P0",
     "Approve attendance permission",
     "اعتماد إذن حضور",
     "Employee submits attendance permission → manager Approve",
     "بعد إذن حضور → اعتمد",
     "Approved; ESS attendance list shows status",
     "معتمد؛ يظهر للموظف",
     "emp_1712"),

    # HR fallback visibility for manager
    ("M-050", "Routing", "Team App", "P1",
     "When HR stood in, acting role shown",
     "عند احتياطي HR يظهر الدور",
     "Inspect a request that used fallback_role=hr",
     "افحص طلباً عبر fallback",
     "Stepper/graph shows HR (acting_role), not claiming Manager approved",
     "يظهر HR وليس ادعاء موافقة المدير",
     "admin"),
    ("M-051", "Routing", "Team App", "P1",
     "After manager assigned, unrouted request becomes actionable",
     "بعد تعيين مدير يصبح الطلب قابلاً للتنفيذ",
     "Unrouted leave → HR assigns manager → manager Approves",
     "طلب بلا توجيه → تعيين مدير → اعتماد",
     "_reroute fills current_approver_ids; approve succeeds",
     "يُعاد التوجيه؛ الاعتماد ينجح",
     "emp_1712"),

    # Team awareness
    ("M-060", "Team awareness", "Pulse Chat", "P1",
     "Who is on my team?",
     "من في فريقي؟",
     "Who reports to me? / من مرؤوسي؟",
     "من مرؤوسي؟",
     "Grounded list of reports if capability allows; else honest deny",
     "قائمة مرؤوسين أو رفض صادق",
     "emp_1712"),
    ("M-061", "Team awareness", "Team App", "P1",
     "Empty inbox UX",
     "صندوق فارغ",
     "When no pending approvals",
     "لا موافقات معلقة",
     "Clear empty state — not error",
     "حالة فارغة واضحة وليست خطأ",
     "emp_1712"),

    # Cross E2E
    ("M-070", "E2E", "Multi", "P0",
     "Full leave journey EN",
     "رحلة إجازة كاملة EN",
     "1) emp_1067 Pulse: annual tomorrow 2) confirm 3) emp_1712 /team Approve 4) emp_1067 sees Approved",
     "1) موظف يقدّم 2) يؤكد 3) مدير يعتمد 4) موظف يرى Approved",
     "End-to-end green; no SKIPPED AUTO; dates ISO future; reference_no present",
     "نجاح كامل؛ بلا تخطي تلقائي؛ تاريخ صحيح",
     "emp_1067 + emp_1712"),
    ("M-071", "E2E", "Multi", "P0",
     "Full leave journey AR",
     "رحلة إجازة كاملة AR",
     "1) اريد اجازة ليوم واحد غدا عادي 2) ايوة 3) المدير يعتمد 4) طلباتي = معتمد",
     "نفس الرحلة بالعربي",
     "Same as M-070 with Arabic utterances and UI",
     "نفس النجاح بالعربية",
     "emp_1067 + emp_1712"),
    ("M-072", "E2E", "Multi", "P0",
     "Full loan journey",
     "رحلة قرض كاملة",
     "Employee submit loan → manager approve → finance approve → loan active",
     "موظف → مدير → مالية → نشط",
     "Both steps required; employee list_my_loans shows active",
     "خطوتان؛ القرض يظهر نشطاً",
     "emp_1067 + emp_1712 + finance"),
    ("M-073", "E2E", "Multi", "P0",
     "Full attendance permission journey",
     "رحلة إذن حضور كاملة",
     "Employee submit → manager approve → visible on /my/attendance",
     "موظف → مدير → يظهر في الصفحة",
     "Approved end-to-end",
     "نجاح كامل",
     "emp_1067 + emp_1712"),
    ("M-074", "E2E", "Multi", "P1",
     "Agent plan leave then manager approve",
     "خطة Agent ثم اعتماد المدير",
     "emp_1067 Agent plan submit leave → confirm step → emp_1712 Approve",
     "خطة ثم تأكيد ثم اعتماد",
     "Agent consent ≠ manager approval; both gates required",
     "موافقة Agent ≠ موافقة المدير؛ كلاهما مطلوب",
     "emp_1067 + emp_1712"),
]


def style_header(ws):
    fill = PatternFill("solid", fgColor="0F766E")
    font = Font(bold=True, color="FFFFFF", name="Calibri", size=11)
    for col, _ in enumerate(HEADERS, 1):
        cell = ws.cell(1, col)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
        cell.border = THIN
    ws.row_dimensions[1].height = 32
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}1"


def write_sheet(wb, title, rows, legend_fill):
    ws = wb.create_sheet(title)
    for c, h in enumerate(HEADERS, 1):
        ws.cell(1, c, h)
    style_header(ws)

    zebra = PatternFill("solid", fgColor="F0FDFA")
    p0 = PatternFill("solid", fgColor="FEF3C7")
    wrap = Alignment(wrap_text=True, vertical="top")

    for r_i, row in enumerate(rows, 2):
        for c_i, val in enumerate(row, 1):
            cell = ws.cell(r_i, c_i, val)
            cell.border = THIN
            cell.alignment = wrap
            if r_i % 2 == 0:
                cell.fill = zebra
            if c_i == 4 and val == "P0":
                cell.fill = p0
                cell.font = Font(bold=True, color="92400E")

    widths = [8, 16, 14, 9, 34, 28, 42, 36, 42, 36, 18, 12, 24]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    for r in range(2, len(rows) + 2):
        ws.row_dimensions[r].height = 48

    dv = DataValidation(
        type="list",
        formula1='"Pass,Fail,Blocked,Skip"',
        allow_blank=True,
    )
    ws.add_data_validation(dv)
    dv.add(f"L2:L{len(rows) + 1}")

    # Legend row at bottom
    legend_row = len(rows) + 3
    ws.cell(legend_row, 1, "Legend").font = Font(bold=True)
    ws.cell(legend_row + 1, 1, "P0 = must pass for go-live · P1 = important · P2 = nice-to-have")
    ws.cell(legend_row + 2, 1, "Surfaces: Pulse Chat | Pulse Agent | My App | People App | Team App | Multi")
    ws.cell(legend_row + 3, 1,
            "Creds: emp_* / mozafNibrasPa_132 · admin / AdmNibras_132 · ahmed / AdminPa_132")
    ws.cell(legend_row + 4, 1,
            "Cast: Employee emp_1067 → Manager emp_1712 · Alt emp_1001 → emp_1399 · HR admin/ahmed")
    for offset in range(5):
        ws.cell(legend_row + offset, 1).fill = legend_fill

    return ws


def write_cover(wb):
    ws = wb.create_sheet("00 · Cover & How to run", 0)
    ws["A1"] = "Nibras · Agentic QA Checklist"
    ws["A1"].font = Font(bold=True, size=18, color="0F766E")
    ws["A2"] = "Employee ESS / Pulse · HR People · Manager Team — EN + AR scenarios"
    ws["A3"] = "Generated for local-dev brand nibras / nibras_dev"

    lines = [
        "",
        "HOW TO RUN",
        "1. Brand: ./manage.sh brand nibras  (ensure ensure_nibras_admins if login fails)",
        "2. Backend + frontend up (e.g. :8009 / :5179)",
        "3. Use the cast below — never invent passwords",
        "4. Work sheet by sheet; mark Pass/Fail in column L",
        "5. For Multi E2E rows, keep two browsers or private windows (employee + manager)",
        "",
        "CAST (DEV)",
        "Role | Username | Password",
        "Employee (with manager) | emp_1067 | mozafNibrasPa_132",
        "Manager of 1067 | emp_1712 | mozafNibrasPa_132",
        "Employee alt | emp_1001 | mozafNibrasPa_132",
        "Manager alt | emp_1399 | mozafNibrasPa_132",
        "Brand admin / HR | admin | AdmNibras_132",
        "Platform superuser | ahmed | AdminPa_132",
        "",
        "FOCUS AREAS (recent fixes)",
        "• Consent staging: tool call = proposal; confirm card required (RULE_21)",
        "• No mutation deflection ('do it in the system elsewhere')",
        "• Leave synonyms: عارضة→emergency, سنوية→annual, مرضية→sick",
        "• Date grounding: غدا/بكرة/1 أكتوبر القادم — not year 2023",
        "• Affirmation: ايوة/نعم/تمام — ايه alone is NOT yes",
        "• Approval gate: never SKIPPED(AUTO) just because manager list empty",
        "• HR fallback_role when manager vacant; acting_role shown on graph",
        "• Agent drawer: summary or one question — no blank multi-field form",
        "",
        "SHEETS",
        "01 Employee — ESS / Pulse / My (leave, loan, attendance, payslip, guards)",
        "02 HR — People app + Pulse Agent payroll/GOSI/onboarding + HR approvals",
        "03 Manager — Team inbox approve/reject/send-back + multi-user E2E",
        "",
        "Pass criteria for a row: Expected (EN/AR) fully met; no console/server 500; no invented numbers.",
    ]
    for i, line in enumerate(lines, 5):
        ws.cell(i, 1, line)
        if line.startswith("HOW") or line.startswith("CAST") or line.startswith("FOCUS") or line.startswith("SHEETS"):
            ws.cell(i, 1).font = Font(bold=True, size=12, color="0F766E")
    ws.column_dimensions["A"].width = 110


def main():
    wb = Workbook()
    # remove default
    wb.remove(wb.active)
    write_cover(wb)
    write_sheet(wb, "01 · Employee ESS-Pulse", EMPLOYEE, PatternFill("solid", fgColor="ECFDF5"))
    write_sheet(wb, "02 · HR People", HR, PatternFill("solid", fgColor="EFF6FF"))
    write_sheet(wb, "03 · Manager Team", MANAGER, PatternFill("solid", fgColor="FFF7ED"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUT)
    print(f"Wrote {OUT}")
    print(f"  Employee rows: {len(EMPLOYEE)}")
    print(f"  HR rows:       {len(HR)}")
    print(f"  Manager rows:  {len(MANAGER)}")
    print(f"  Total cases:   {len(EMPLOYEE) + len(HR) + len(MANAGER)}")


if __name__ == "__main__":
    main()
