# Generated by Django 5.2.3 on 2026-09-24 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=80)),
                ('subject_id', models.CharField(db_index=True, max_length=160)),
                ('reason', models.TextField()),
                ('granted_by', models.CharField(max_length=120)),
                ('until', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['until'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=80)),
                ('subject_id', models.CharField(db_index=True, max_length=160)),
                ('tier', models.CharField(db_index=True, max_length=40)),
                ('track', models.CharField(blank=True, default='', max_length=40)),
                ('commit', models.CharField(db_index=True, max_length=40)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], max_length=12)),
                ('evidence_class', models.CharField(choices=[('configured', 'Configured'), ('executed', 'Executed'), ('enforcement-verified', 'Enforcement Verified'), ('fault-demonstrated', 'Fault Demonstrated'), ('unknown', 'Unknown'), ('conflict', 'Conflict')], max_length=24)),
                ('source', models.TextField(blank=True, default='')),
                ('runner', models.CharField(default='local', max_length=40)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['subject_id', 'check_id', '-at'], name='excellence__subject_543092_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tier', models.CharField(db_index=True, max_length=40)),
                ('track', models.CharField(blank=True, default='', max_length=40)),
                ('subject_id', models.CharField(db_index=True, max_length=160)),
                ('commit', models.CharField(max_length=40)),
                ('level', models.PositiveSmallIntegerField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('date', 'subject_id'), name='excellence_snapshot_day_subject')],
            },
        ),
    ]
