# Generated by Django 5.2.3 on 2026-09-24 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excellence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectors', models.JSONField(default=list)),
                ('tier', models.CharField(blank=True, default='', max_length=40)),
                ('track', models.CharField(blank=True, default='', max_length=40)),
                ('run_apps', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=12)),
                ('requested_by', models.CharField(max_length=120)),
                ('commit', models.CharField(blank=True, default='', max_length=40)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
