# Generated by Django 5.2.3 on 2026-09-18 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pack_id', models.CharField(max_length=120)),
                ('profile_version', models.PositiveIntegerField(default=1)),
                ('pipeline_snapshot', models.JSONField(blank=True, default=dict)),
                ('run_manifest', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('needs_review', 'Needs review'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gate_decision', models.CharField(choices=[('auto', 'Auto (formative advisory)'), ('review', 'Needs human review'), ('withhold', 'Withhold')], default='review', max_length=20)),
                ('mean_confidence', models.FloatField(blank=True, null=True)),
                ('coaching', models.JSONField(blank=True, default=dict)),
                ('advisory_bands', models.JSONField(blank=True, default=dict)),
                ('released', models.BooleanField(default=False, help_text='Summative marks require explicit release (HITL).')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_edit_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentProfileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='validated', max_length=20)),
                ('discipline', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=80)),
                ('level', models.CharField(blank=True, default='', max_length=80)),
                ('mode', models.CharField(default='formative', max_length=20)),
                ('lct_device_ref', models.JSONField(blank=True, default=dict)),
                ('rubric_pack_ref', models.JSONField(blank=True, default=dict)),
                ('pipeline_config', models.JSONField(blank=True, default=dict)),
                ('hitl_config', models.JSONField(blank=True, default=dict)),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('source_path', models.CharField(blank=True, default='', max_length=512)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['discipline', 'pack_id', '-version'],
                'unique_together': {('pack_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradevance_courses', to='mdm.orgunit')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('formative', 'Formative'), ('summative', 'Summative'), ('calibration', 'Calibration')], default='formative', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('profile_pack_id', models.CharField(max_length=120)),
                ('profile_version', models.PositiveIntegerField(default=1)),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('pipeline_config_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen at publish — runtime MUST honor (RULE_32).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='gradevance.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='gradevance.analysisrun')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edit_kind', models.CharField(choices=[('segment_boundary', 'Segment boundary'), ('lct_code', 'LCT code'), ('rubric_score', 'Rubric score'), ('coaching', 'Coaching'), ('other', 'Other')], max_length=32)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_edits', to='gradevance.analysisrun')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='gradevance.reviewitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('start_word', models.PositiveIntegerField()),
                ('end_word', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('stage_guess', models.CharField(blank=True, default='', max_length=32)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='gradevance.analysisrun')),
            ],
            options={
                'ordering': ['run_id', 'ordinal'],
                'unique_together': {('run', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='LCTCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=16)),
                ('numeric', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('engine', 'Engine'), ('expert', 'Expert')], default='engine', max_length=16)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='gradevance.segment')),
            ],
            options={
                'ordering': ['segment_id', 'dimension'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_student_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('analyzed', 'Analyzed')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='gradevance.assignment')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gradevance_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gradevance.submission'),
        ),
        migrations.CreateModel(
            name='WaveProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wave', to='gradevance.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='RubricEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_id', models.CharField(max_length=80)),
                ('band', models.CharField(blank=True, default='', max_length=8)),
                ('score_0_100', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence_bindings', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('engine', 'Engine'), ('expert', 'Expert')], default='engine', max_length=16)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='gradevance.analysisrun')),
            ],
            options={
                'ordering': ['run_id', 'criterion_id'],
                'unique_together': {('run', 'criterion_id', 'source')},
            },
        ),
    ]
