# Generated by Django 5.2.3 on 2026-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradevance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricevaluation',
            name='band',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
