# Generated by Django 5.2.3 on 2026-09-18 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradevance', '0002_widen_rubric_band'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='entry_code',
            field=models.CharField(blank=True, default='', help_text='Optional join code for manual student enrollment.', max_length=64),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching assistant'), ('instructor', 'Instructor')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('code', 'Entry code'), ('nrps', 'NRPS')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gradevance.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradevance_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_id', 'role', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='gradevance_enrollment_course_user_uniq')],
            },
        ),
    ]
