# Generated by Django 5.2.3 on 2026-09-28 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('typed_object', 'Typed object'), ('data_product', 'Data product')], max_length=20)),
                ('target_key', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('mapped', 'Mapped'), ('smoked', 'Smoked'), ('committed', 'Committed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('file', models.FileField(blank=True, default='', upload_to='inbound/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('encoding', models.CharField(blank=True, default='', max_length=32)),
                ('delimiter', models.CharField(blank=True, default=',', max_length=4)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('sample', models.JSONField(blank=True, default=list)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('smoke', models.JSONField(blank=True, default=dict)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_committed', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=20)),
                ('target_key', models.CharField(max_length=80)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_key', 'name'],
                'unique_together': {('name', 'target_key')},
            },
        ),
    ]
