# Generated by Django 5.2.3 on 2026-08-18 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_adopt_datasets'),
        ('dataschema', '0005_add_dq_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_url', models.CharField(max_length=500)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnkey_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TurnKeyModelLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turnkey_model_id', models.CharField(max_length=200)),
                ('turnkey_model_name', models.CharField(blank=True, max_length=200)),
                ('turnkey_version_id', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(choices=[('training', 'Training dataset'), ('inference', 'Inference input schema')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered in TurnKey'), ('promoted', 'Promoted to production'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnkey_links', to='catalog.datasetversion')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnkey_links', to=settings.AUTH_USER_MODEL)),
                ('turnkey_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnkey.turnkeyconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('prediction', models.JSONField()),
                ('actual', models.JSONField(blank=True, null=True)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
                ('input_data_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='dataschema.datarow')),
                ('model_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='turnkey.turnkeymodellink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnkey_alert_id', models.CharField(max_length=200, unique=True)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('dq_job_triggered', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_drift_alerts', to=settings.AUTH_USER_MODEL)),
                ('model_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_alerts', to='turnkey.turnkeymodellink')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
