# Generated by Django 5.2.3 on 2026-07-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0001_initial'),
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='reference_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_fields', to='mdm.referenceset'),
        ),
    ]
