# Generated by Django 5.2.3 on 2026-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0004_datatable_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='dq_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
