"""Host identifiers. The engine holds the key. The pack holds the name.

A set of these is built when it is used. Import-time hashing would freeze
the empty string from an unbound pack.
"""
from __future__ import annotations

from ai.engine.pack_vocab import LV

ID_GET_MY_LEAVE_BALANCE = LV("t_rx_id_get_my_leave_balance")
ID_LIST_MY_LEAVE = LV("t_rx_id_list_my_leave")
ID_LIST_MY_LOANS = LV("t_rx_id_list_my_loans")
ID_LIST_MY_PAYSLIPS = LV("t_rx_id_list_my_payslips")
ID_LIST_MY_ATTENDANCE = LV("t_rx_id_list_my_attendance")
ID_LIST_LEAVE_ENTITLEMENTS = LV("t_rx_id_list_leave_entitlements")
ID_LIST_LEAVE_RECORDS = LV("t_rx_id_list_leave_records")
ID_LIST_LOANS = LV("t_rx_id_list_loans")
ID_LIST_PAYSLIP_LINES = LV("t_rx_id_list_payslip_lines")
ID_LIST_LOAN_INSTALLMENTS = LV("t_rx_id_list_loan_installments")
ID_LIST_ATTENDANCE_PERMISSIONS = LV("t_rx_id_list_attendance_permissions")
ID_LIST_MY_ATTENDANCE_PERMISSIONS = LV("t_rx_id_list_my_attendance_permissions")
ID_LIST_ATTENDANCE = LV("t_rx_id_list_attendance")
ID_GET_LEAVE_BALANCE = LV("t_rx_id_get_leave_balance")
ID_SUBMIT_MY_LEAVE = LV("t_rx_id_submit_my_leave")
ID_SUBMIT_MY_LOAN = LV("t_rx_id_submit_my_loan")
ID_SUBMIT_MY_ATTENDANCE_PERMISSION = LV("t_rx_id_submit_my_attendance_permission")
ID_SUBMIT_MY_PROFILE_CHANGE = LV("t_rx_id_submit_my_profile_change")
ID_CREATE_LEAVE_RECORD = LV("t_rx_id_create_leave_record")
ID_CREATE_ATTENDANCE_PERMISSION = LV("t_rx_id_create_attendance_permission")
ID_CREATE_EMPLOYEE = LV("t_rx_id_create_employee")
ID_UPDATE_EMPLOYEE = LV("t_rx_id_update_employee")
ID_GET_EMPLOYEE = LV("t_rx_id_get_employee")
ID_GET_MY_PROFILE = LV("t_rx_id_get_my_profile")
ID_LIST_EMPLOYEES = LV("t_rx_id_list_employees")
ID_ANALYZE_EMPLOYEES = LV("t_rx_id_analyze_employees")
ID_APPROVE_ATTENDANCE_PERMISSION = LV("t_rx_id_approve_attendance_permission")
ID_LIST_MY_CAPABILITIES = LV("t_rx_id_list_my_capabilities")
ID_GET_CALCULATION_SUMMARY = LV("t_rx_id_get_calculation_summary")
ID_LIST_ORG_UNITS = LV("t_rx_id_list_org_units")
ID_SUBMIT_MY_PREFIX = LV("t_rx_id_submit_my_prefix")
ID_LEAVE_HISTORY = LV("t_rx_id_leave_history")
ID_LOAN_HISTORY = LV("t_rx_id_loan_history")
ID_NO_BALANCE = LV("t_rx_id_no_balance_configured")
ID_NO_LEAVE_REQUESTS = LV("t_rx_id_no_leave_requests")
ID_NO_LOANS = LV("t_rx_id_no_loans")
ID_NO_PAYSLIPS = LV("t_rx_id_no_payslips")
ID_NO_ATTENDANCE_ROWS = LV("t_rx_id_no_attendance_rows")
ID_NO_ATTENDANCE_PERMISSIONS = LV("t_rx_id_no_attendance_permissions")
ID_EMPTY_LEAVE_HISTORY = LV("t_rx_id_ess_empty_leave_history")
ID_EMPTY_LOAN_HISTORY = LV("t_rx_id_ess_empty_loan_history")
ID_EMPTY_PAYSLIP = LV("t_rx_id_ess_empty_payslip")
ID_LEAVE_REQUEST = LV("t_rx_id_leave_request")
ID_LOAN_REQUEST = LV("t_rx_id_loan_request")
ID_ATTENDANCE_PERMISSION = LV("t_rx_id_attendance_permission")
ID_LEAVE_TYPE = LV("t_rx_id_leave_type")
ID_LOAN_TYPE = LV("t_rx_id_loan_type")
ID_PERMISSION_TYPE = LV("t_rx_id_permission_type")
ID_PRINCIPAL = LV("t_rx_id_principal")
ID_SCOPE_PERMISSIONS = LV("t_rx_id_scope_permissions")
ID_CAP_COMPENSATION = LV("t_rx_id_cap_compensation")
ID_CAP_VIEW_PREFIX = LV("t_rx_id_cap_view_prefix")
ID_CAP_VIEW_COMP = LV("t_rx_id_cap_view_comp")
ID_ENUM_ANNUAL = LV("t_rx_id_enum_annual")
ID_ENUM_SICK = LV("t_rx_id_enum_sick")
ID_ENUM_EMERGENCY = LV("t_rx_id_enum_emergency")
ID_ENUM_UNPAID = LV("t_rx_id_enum_unpaid")
ID_ENUM_MATERNITY = LV("t_rx_id_enum_maternity")
ID_ENUM_HOUSING = LV("t_rx_id_enum_housing")
ID_ENUM_CAR = LV("t_rx_id_enum_car")
ID_ENUM_PERSONAL = LV("t_rx_id_enum_personal")
ID_ENUM_OFFICIAL = LV("t_rx_id_enum_official")
ID_ENUM_MEDICAL = LV("t_rx_id_enum_medical")
