# Generated by Django 5.2.3 on 2026-09-13 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code unique within the scheme', max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope_type', models.CharField(choices=[('company', 'Company'), ('org_unit', 'Org Unit'), ('koc_contract', 'KOC Contract'), ('employee', 'Employee'), ('position', 'Position'), ('custom', 'Custom')], default='company', max_length=20)),
                ('formula_type', models.CharField(help_text='Key into evaluator registry (registered by domain apps)', max_length=80)),
                ('formula_params', models.JSONField(blank=True, default=dict, help_text='Evaluator-specific parameters (e.g. quota thresholds, reference codes)')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], default='major', max_length=10)),
                ('citation', models.CharField(blank=True, help_text='Source article / section', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheme', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RegulationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('authority', models.CharField(blank=True, help_text='Issuing authority (e.g. KOC, Ministry of Labour, IASB)', max_length=200)),
                ('version', models.CharField(blank=True, help_text='Revision / year', max_length=40)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Assessment date (the "as of" date for findings)')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Aggregate stats: {total, compliant, non_compliant, partial, error}')),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='regulations.auditprogram')),
                ('run_by', models.ForeignKey(blank=True, help_text='Null = automated/scheduled run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_date', '-run_at'],
            },
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='obligations',
            field=models.ManyToManyField(blank=True, related_name='programs', to='regulations.obligation'),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('company', 'Company'), ('org_unit', 'Org Unit'), ('koc_contract', 'KOC Contract'), ('employee', 'Employee'), ('position', 'Position'), ('custom', 'Custom')], max_length=20)),
                ('scope_id', models.PositiveIntegerField(help_text='PK of the evaluated entity')),
                ('scope_label', models.CharField(blank=True, help_text='Denormalized display name', max_length=255)),
                ('result', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partial', 'Partial'), ('na', 'Not Applicable'), ('error', 'Evaluator Error')], db_index=True, max_length=15)),
                ('computed_value', models.JSONField(default=dict, help_text='Evaluator output: {actual, expected, delta, detail, …}')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='regulations.auditrun')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='regulations.obligation')),
            ],
            options={
                'ordering': ['run', 'obligation', 'scope_type', 'scope_id'],
            },
        ),
        migrations.AddField(
            model_name='obligation',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='regulations.regulationscheme'),
        ),
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted_risk', 'Accepted Risk')], db_index=True, default='open', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remediation', to='regulations.auditfinding')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['run', 'result'], name='regulations_run_id_576d49_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['obligation', 'result'], name='regulations_obligat_18c711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obligation',
            unique_together={('scheme', 'code')},
        ),
    ]
