# Generated by Django 5.2.3 on 2026-07-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataschema', '0002_datafield_reference_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('table', 'Table'), ('field', 'Field')], default='field', max_length=10)),
                ('rule_type', models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('allowed_values', 'Allowed Values'), ('range', 'Range'), ('regex', 'Regex')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='error', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dq_rules', to='dataschema.datafield')),
                ('data_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dq_rules', to='dataschema.datatable')),
            ],
        ),
        migrations.CreateModel(
            name='DQResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=True)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sample_failures', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dq.dqrule')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('null_count', models.PositiveIntegerField(default=0)),
                ('distinct_count', models.PositiveIntegerField(default=0)),
                ('completeness_pct', models.FloatField(default=0)),
                ('uniqueness_pct', models.FloatField(default=0)),
                ('min_value', models.CharField(blank=True, max_length=255)),
                ('max_value', models.CharField(blank=True, max_length=255)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('top_values', models.JSONField(blank=True, default=list)),
                ('profiled_at', models.DateTimeField(auto_now_add=True)),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_field_profiles', to='dataschema.datafield')),
            ],
            options={
                'ordering': ['-profiled_at'],
            },
        ),
        migrations.CreateModel(
            name='TableProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('completeness_pct', models.FloatField(default=0)),
                ('profiled_at', models.DateTimeField(auto_now_add=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_table_profiles', to='dataschema.datatable')),
            ],
            options={
                'ordering': ['-profiled_at'],
            },
        ),
    ]
