# Generated by Django 5.2.3 on 2026-07-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dqrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dqrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dq_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
