# Generated by Django 5.2.3 on 2026-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0003_add_performance_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dqresult',
            name='dqresult_time_rule_idx',
        ),
        migrations.RemoveIndex(
            model_name='dqresult',
            name='dqresult_passed_idx',
        ),
        migrations.AlterField(
            model_name='dqrule',
            name='rule_type',
            field=models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('allowed_values', 'Allowed Values'), ('range', 'Range'), ('regex', 'Regex'), ('reference_integrity', 'Reference Integrity')], max_length=20),
        ),
    ]
