# Generated by Django 5.2.3 on 2026-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0004_remove_dqresult_dqresult_time_rule_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqrule',
            name='rule_type',
            field=models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('allowed_values', 'Allowed Values'), ('range', 'Range'), ('regex', 'Regex'), ('reference_integrity', 'Reference Integrity'), ('threshold', 'Threshold')], max_length=20),
        ),
    ]
