# Generated by Django 5.2.3 on 2026-08-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0004_datatable_is_locked'),
        ('dq', '0005_alter_dqrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_profile_enabled', models.BooleanField(default=False, help_text='When enabled, new/modified tables are profiled automatically')),
                ('freshness_threshold_hours', models.PositiveIntegerField(default=24, help_text='Tables not profiled within this window are considered stale')),
                ('volume_anomaly_pct', models.PositiveSmallIntegerField(default=25, help_text='Row count change % that triggers a volume anomaly alert')),
                ('sample_size', models.PositiveIntegerField(default=1000, help_text='Max rows sampled for top_values/distribution analysis')),
            ],
            options={
                'verbose_name': 'DQ Profile Config',
            },
        ),
        migrations.AddField(
            model_name='tableprofile',
            name='distinct_counts',
            field=models.JSONField(blank=True, default=dict, help_text='{field_name: distinct_count} per column'),
        ),
        migrations.AddField(
            model_name='tableprofile',
            name='max_values',
            field=models.JSONField(blank=True, default=dict, help_text='{field_name: max_value} per column'),
        ),
        migrations.AddField(
            model_name='tableprofile',
            name='mean_values',
            field=models.JSONField(blank=True, default=dict, help_text='{field_name: mean_value} per column (numeric only)'),
        ),
        migrations.AddField(
            model_name='tableprofile',
            name='min_values',
            field=models.JSONField(blank=True, default=dict, help_text='{field_name: min_value} per column'),
        ),
        migrations.AddField(
            model_name='tableprofile',
            name='null_counts',
            field=models.JSONField(blank=True, default=dict, help_text='{field_name: null_count} per column'),
        ),
        migrations.AddIndex(
            model_name='tableprofile',
            index=models.Index(fields=['data_table', '-profiled_at'], name='dq_tablepro_data_ta_37bb16_idx'),
        ),
    ]
