# Generated by Django 5.2.3 on 2026-08-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0004_datatable_is_locked'),
        ('dq', '0006_phase1_7_profiling_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_schema', models.JSONField(help_text='{field_name: {type, is_nullable, position}} per column')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_snapshots', to='dataschema.datatable')),
            ],
            options={
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Column Added'), ('dropped', 'Column Dropped'), ('modified', 'Column Modified')], max_length=10)),
                ('field_name', models.CharField(max_length=255)),
                ('old_definition', models.JSONField(blank=True, help_text='Old column definition (or None if added)', null=True)),
                ('new_definition', models.JSONField(blank=True, help_text='New column definition (or None if dropped)', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_changes', to='dataschema.datatable')),
                ('snapshot_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='dq.schemasnapshot')),
                ('snapshot_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='dq.schemasnapshot')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FreshnessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_max_age_hours', models.PositiveIntegerField(default=24, help_text='Maximum age of data before it is considered stale')),
                ('last_data_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of the newest row in this table', null=True)),
                ('is_fresh', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshness_checks', to='dataschema.datatable')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['data_table', '-checked_at'], name='dq_freshnes_data_ta_71407e_idx'), models.Index(fields=['is_fresh', '-checked_at'], name='dq_freshnes_is_fres_7f6c5b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schemasnapshot',
            index=models.Index(fields=['data_table', '-snapshot_at'], name='dq_schemasn_data_ta_92076b_idx'),
        ),
        migrations.AddIndex(
            model_name='schemachange',
            index=models.Index(fields=['data_table', '-detected_at'], name='dq_schemach_data_ta_6b4633_idx'),
        ),
        migrations.AddIndex(
            model_name='schemachange',
            index=models.Index(fields=['change_type', '-detected_at'], name='dq_schemach_change__21dde9_idx'),
        ),
    ]
