# Generated by Django 5.2.3 on 2026-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0007_phase1_8_freshness_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqrule',
            name='rule_type',
            field=models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('allowed_values', 'Allowed Values'), ('range', 'Range'), ('regex', 'Regex'), ('reference_integrity', 'Reference Integrity'), ('threshold', 'Threshold'), ('nl_check', 'NL Check')], max_length=20),
        ),
    ]
