# Generated by Django 5.2.3 on 2026-08-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0004_datatable_is_locked'),
        ('dq', '0008_alter_dqrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFieldAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['data_table__name', 'data_field__name'],
            },
        ),
        migrations.CreateModel(
            name='RuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for UI badge (e.g. #6366f1)', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='dqrule',
            name='data_field',
        ),
        migrations.RemoveField(
            model_name='dqrule',
            name='data_table',
        ),
        migrations.RemoveField(
            model_name='dqrule',
            name='scope',
        ),
        migrations.AddField(
            model_name='dqresult',
            name='data_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dq_results', to='dataschema.datafield'),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='description',
            field=models.TextField(blank=True, help_text='What this rule checks and why'),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='rule_level',
            field=models.CharField(choices=[('field_validation', 'Field Validation'), ('business_rule', 'Business Rule')], default='field_validation', max_length=20),
        ),
        migrations.AlterField(
            model_name='dqrule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='dqresult',
            index=models.Index(fields=['rule', '-run_at'], name='dq_dqresult_rule_id_68407c_idx'),
        ),
        migrations.AddIndex(
            model_name='dqresult',
            index=models.Index(fields=['data_field', '-run_at'], name='dq_dqresult_data_fi_fdb245_idx'),
        ),
        migrations.AddField(
            model_name='rulefieldassignment',
            name='data_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_assignments', to='dataschema.datafield'),
        ),
        migrations.AddField(
            model_name='rulefieldassignment',
            name='data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_assignments', to='dataschema.datatable'),
        ),
        migrations.AddField(
            model_name='rulefieldassignment',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assignments', to='dq.dqrule'),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rules', to='dq.ruletag'),
        ),
        migrations.AddConstraint(
            model_name='rulefieldassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('data_field__isnull', False)), fields=('rule', 'data_field'), name='unique_rule_field'),
        ),
        migrations.AddConstraint(
            model_name='rulefieldassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('data_field__isnull', True)), fields=('rule', 'data_table'), name='unique_rule_table'),
        ),
    ]
