# Generated by Django 5.2.3 on 2026-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0009_decouple_rules_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dqprofileconfig',
            name='auto_profile_enabled',
        ),
        migrations.RemoveField(
            model_name='dqprofileconfig',
            name='sample_size',
        ),
        migrations.AlterField(
            model_name='dqprofileconfig',
            name='volume_anomaly_pct',
            field=models.PositiveSmallIntegerField(default=25, help_text='Row count change % that triggers a volume anomaly alert (wired in DQ Phase 4)'),
        ),
        migrations.AlterField(
            model_name='freshnesscheck',
            name='expected_max_age_hours',
            field=models.PositiveIntegerField(default=24, help_text='Snapshot of the global threshold at check time; per-table thresholds not yet supported'),
        ),
    ]
