# Generated by Django 5.2.3 on 2026-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0010_remove_dqprofileconfig_auto_profile_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqrule',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-delete when results exist'),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='definition',
            field=models.JSONField(blank=True, default=dict, help_text='Full v1 rule definition JSON (source of truth)'),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='dimension',
            field=models.CharField(choices=[('completeness', 'Completeness'), ('validity', 'Validity'), ('accuracy', 'Accuracy'), ('consistency', 'Consistency'), ('timeliness', 'Timeliness'), ('uniqueness', 'Uniqueness'), ('integrity', 'Integrity'), ('reasonability', 'Reasonability')], default='validity', help_text='DAMA DMBOK2 data quality dimension', max_length=20),
        ),
        migrations.AddField(
            model_name='dqrule',
            name='version',
            field=models.IntegerField(default=1, help_text='Monotonic rule version'),
        ),
    ]
