# Generated by Django 5.2.3 on 2026-08-10 09:53

from django.db import migrations


def wrap_existing_rules(apps, schema_editor):
    """Build v1 JSON definition for every existing DQRule from its
    RuleFieldAssignment rows and denormalized fields."""
    DQRule = apps.get_model('dq', 'DQRule')
    RuleFieldAssignment = apps.get_model('dq', 'RuleFieldAssignment')
    DataTable = apps.get_model('dataschema', 'DataTable')
    DataField = apps.get_model('dataschema', 'DataField')

    for rule in DQRule.objects.all().select_related():
        if rule.definition:
            continue  # already wrapped

        # Resolve table and field names from M2M assignments
        assignments = RuleFieldAssignment.objects.filter(rule=rule).select_related('data_table', 'data_field')
        bindings = []
        for assn in assignments:
            binding = {
                'table': assn.data_table.name if assn.data_table and assn.data_table.name else '',
            }
            if assn.data_field and assn.data_field.name:
                binding['field'] = assn.data_field.name
            bindings.append(binding)

        if not bindings:
            bindings = [{'table': 'unknown'}]

        # Map rule_level choices to v1 schema level
        level_map = {
            'field_validation': 'field',
            'business_rule': 'business',
        }
        level = level_map.get(rule.rule_level, 'field')

        # Default dimension: nl_check → accuracy, everything else → validity
        dimension = 'accuracy' if rule.rule_type == 'nl_check' else 'validity'

        definition = {
            'schema_version': 1,
            'name': rule.name or '',
            'description': rule.description or '',
            'level': level,
            'dimension': dimension,
            'type': rule.rule_type,
            'severity': rule.severity or 'error',
            'active': rule.is_active,
            'bindings': bindings,
            'params': rule.params or {},
            'enforcement': {
                'on_write': False,
                'on_import': 'flag',
            },
        }

        # Use update() to skip save() validation
        DQRule.objects.filter(pk=rule.pk).update(
            definition=definition,
            dimension=dimension,
            version=1,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0011_v2_add_definition_dimension'),
    ]

    operations = [
        migrations.RunPython(wrap_existing_rules, reverse_code=noop),
    ]
