# Generated by Django 5.2.3 on 2026-08-11 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0005_add_dq_flags'),
        ('dq', '0012_v2_wrap_existing_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DQJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('rule_run', 'Rule Run'), ('profile', 'Profile'), ('freshness', 'Freshness'), ('schema', 'Schema'), ('nl_check', 'NL Check'), ('suggest', 'Suggest')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Job inputs (e.g. prompt, unavailable_streak for Pulse jobs)')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Job summary (counts for rule runs, profile summary, Pulse result)')),
                ('pulse_task_id', models.CharField(blank=True, default='', help_text='Pulse task id for nl_check/suggest jobs (polled via GET /tasks/{id})', max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0–100')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dq_jobs', to=settings.AUTH_USER_MODEL)),
                ('data_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dq_jobs', to='dataschema.datatable')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dq.dqrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'job_type'], name='dq_dqjob_status_2ab4eb_idx'), models.Index(fields=['created_at'], name='dq_dqjob_created_24b3f1_idx')],
            },
        ),
    ]
