# Generated by Django 5.2.3 on 2026-08-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0005_add_dq_flags'),
        ('dq', '0013_dqjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dqresult',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped_unavailable', 'Skipped — Pulse Unavailable')], default='passed', help_text='passed|failed|skipped_unavailable (fail-visible, Phase 4)', max_length=20),
        ),
        migrations.AlterField(
            model_name='dqjob',
            name='job_type',
            field=models.CharField(choices=[('rule_run', 'Rule Run'), ('profile', 'Profile'), ('freshness', 'Freshness'), ('schema', 'Schema'), ('nl_check', 'NL Check'), ('suggest', 'Suggest'), ('anomaly', 'Anomaly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dqresult',
            name='passed',
            field=models.BooleanField(blank=True, default=None, help_text='True/False verdict; null when the rule could not be evaluated (status=skipped_unavailable — Pulse down, Phase 4 fail-visible)', null=True),
        ),
        migrations.AlterField(
            model_name='dqrule',
            name='rule_type',
            field=models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('allowed_values', 'Allowed Values'), ('range', 'Range'), ('regex', 'Regex'), ('reference_integrity', 'Reference Integrity'), ('threshold', 'Threshold'), ('nl_check', 'NL Check'), ('anomaly_detect', 'Anomaly Detect')], max_length=20),
        ),
        migrations.CreateModel(
            name='DQAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(help_text='e.g. row_count, null_pct:<field>, sum(kwh)', max_length=255)),
                ('group_key', models.JSONField(blank=True, help_text='e.g. {"building": "alamein"} — when the anomaly is scoped to a group', null=True)),
                ('expected_range', models.JSONField(blank=True, default=dict, help_text='{"low": ..., "high": ...} expected baseline from Pulse')),
                ('observed', models.FloatField(help_text='Observed value that triggered the anomaly')),
                ('score', models.FloatField(default=0.0, help_text='Deviation magnitude (e.g. z-score / std-devs from baseline)')),
                ('explanation', models.TextField(blank=True, default='', help_text='Pulse-written human explanation (LLM writes this only)')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='warn', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_anomalies', to='dataschema.datatable')),
                ('job', models.ForeignKey(blank=True, help_text='anomaly job that produced this anomaly', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='dq.dqjob')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['data_table', '-detected_at'], name='dq_dqanomal_data_ta_dd14c9_idx'), models.Index(fields=['severity', '-detected_at'], name='dq_dqanomal_severit_f206db_idx')],
            },
        ),
        migrations.CreateModel(
            name='DQSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Complete v1 rule definition (rule_schema) — becomes the DQRule on accept')),
                ('rationale', models.TextField(blank=True, default='', help_text='Why Pulse suggested this rule (Pulse-written explanation)')),
                ('confidence', models.FloatField(blank=True, help_text='Pulse confidence in the suggestion (0–1)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dq_suggestions', to=settings.AUTH_USER_MODEL)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_suggestions', to='dataschema.datatable')),
                ('job', models.ForeignKey(blank=True, help_text='dq.suggest job that produced this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='dq.dqjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dq_dqsugges_status_73bfb8_idx'), models.Index(fields=['data_table', '-created_at'], name='dq_dqsugges_data_ta_79bc6f_idx')],
            },
        ),
    ]
