# Generated by Django 5.2.3 on 2026-08-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0015_map_existing_dqresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text="Django app+model label, e.g. 'people.Employee'", max_length=255)),
                ('field_name', models.CharField(blank=True, help_text='Concrete field on the model; blank = model/row-level rule', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_assignments', to='dq.dqrule')),
            ],
            options={
                'ordering': ['model_label', 'field_name'],
                'unique_together': {('rule', 'model_label', 'field_name')},
            },
        ),
    ]
