# Generated by Django 5.2 on 2026-02-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_tenant'),
        ('core', '0003_module_scope'),
        ('dataschema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GWP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_name', models.CharField(help_text="e.g., 'Methane'", max_length=100)),
                ('gas_formula', models.CharField(help_text="Chemical formula, e.g., 'CH4'", max_length=50)),
                ('gwp_ar5_100yr', models.DecimalField(blank=True, decimal_places=2, help_text='GWP from IPCC AR5 (100-year horizon)', max_digits=10, null=True)),
                ('gwp_ar6_100yr', models.DecimalField(blank=True, decimal_places=2, help_text='GWP from IPCC AR6 (100-year horizon)', max_digits=10, null=True)),
                ('gwp_ar5_20yr', models.DecimalField(blank=True, decimal_places=2, help_text='GWP from IPCC AR5 (20-year horizon)', max_digits=10, null=True)),
                ('gwp_ar6_20yr', models.DecimalField(blank=True, decimal_places=2, help_text='GWP from IPCC AR6 (20-year horizon)', max_digits=10, null=True)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this gas')),
            ],
            options={
                'verbose_name': 'Global Warming Potential',
                'verbose_name_plural': 'Global Warming Potentials',
                'ordering': ['gas_name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g., 'US Grid Average 2024'", max_length=200)),
                ('code', models.CharField(help_text="Unique code, e.g., 'US_GRID_2024'", max_length=50, unique=True)),
                ('category', models.CharField(choices=[('electricity', 'Electricity Grid'), ('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('fugitive', 'Fugitive Emissions'), ('process', 'Process Emissions'), ('transport', 'Transportation'), ('waste', 'Waste'), ('water', 'Water'), ('materials', 'Materials/Products')], max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text="e.g., 'Natural Gas'", max_length=100)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Indirect (Energy)'), (3, 'Scope 3 - Value Chain')])),
                ('factor_value', models.DecimalField(decimal_places=10, help_text='Emission factor value (kg CO2e per activity unit)', max_digits=20)),
                ('factor_unit', models.CharField(default='kg CO2e', help_text="e.g., 'kg CO2e'", max_length=50)),
                ('activity_unit', models.CharField(help_text="e.g., 'kWh', 'liter', 'km'", max_length=50)),
                ('co2_factor', models.DecimalField(blank=True, decimal_places=10, help_text='CO2 component of the emission factor', max_digits=20, null=True)),
                ('ch4_factor', models.DecimalField(blank=True, decimal_places=10, help_text='CH4 component (in CO2e)', max_digits=20, null=True)),
                ('n2o_factor', models.DecimalField(blank=True, decimal_places=10, help_text='N2O component (in CO2e)', max_digits=20, null=True)),
                ('country', models.CharField(blank=True, help_text="e.g., 'United States'", max_length=100)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-3, e.g., 'USA'", max_length=3)),
                ('region', models.CharField(blank=True, help_text="e.g., 'California'", max_length=100)),
                ('source', models.CharField(help_text="Data source, e.g., 'EPA eGRID 2024'", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='URL to source documentation')),
                ('valid_from', models.DateField(help_text='Start date of validity period')),
                ('valid_to', models.DateField(blank=True, help_text='End date of validity period (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or methodology details')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this factor is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'country_code'], name='emissions_e_categor_ae6cc4_idx'), models.Index(fields=['scope'], name='emissions_e_scope_be794b_idx'), models.Index(fields=['code'], name='emissions_e_code_f5753d_idx'), models.Index(fields=['is_active'], name='emissions_e_is_acti_54cc7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'FY 2025', 'Q1 2025'", max_length=100)),
                ('start_date', models.DateField(help_text='Start date of the reporting period')),
                ('end_date', models.DateField(help_text='End date of the reporting period')),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Data Entry'), ('locked', 'Locked for Review'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('is_baseline', models.BooleanField(default=False, help_text='Is this the baseline period for comparisons?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reporting_periods', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: specific project (if null, applies to all tenant projects)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.project')),
                ('tenant', models.ForeignKey(help_text='Tenant this period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_value', models.DecimalField(decimal_places=6, help_text='The activity amount (e.g., kWh, liters, km)', max_digits=20)),
                ('activity_unit', models.CharField(help_text='Unit of activity', max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=6, help_text='Total CO2 equivalent emissions in kg', max_digits=20)),
                ('co2_kg', models.DecimalField(blank=True, decimal_places=6, help_text='CO2 emissions in kg', max_digits=20, null=True)),
                ('ch4_kg', models.DecimalField(blank=True, decimal_places=6, help_text='CH4 emissions in kg CO2e', max_digits=20, null=True)),
                ('n2o_kg', models.DecimalField(blank=True, decimal_places=6, help_text='N2O emissions in kg CO2e', max_digits=20, null=True)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Indirect (Energy)'), (3, 'Scope 3 - Value Chain')], help_text='GHG Protocol scope (1, 2, or 3)')),
                ('category', models.CharField(help_text='Emission category', max_length=50)),
                ('reporting_year', models.PositiveIntegerField(help_text='Year for this emission data')),
                ('reporting_month', models.PositiveSmallIntegerField(blank=True, help_text='Month (1-12) if available', null=True)),
                ('activity_date', models.DateField(blank=True, help_text='Date when the activity occurred', null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_method', models.CharField(default='auto', help_text="Method used: 'auto', 'manual', 'import', etc.", max_length=100)),
                ('calculated_by', models.ForeignKey(blank=True, help_text='User who triggered this calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_row', models.ForeignKey(help_text='The source data row for this calculation', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='dataschema.datarow')),
                ('module', models.ForeignKey(help_text='The module (data collection unit) for this calculation', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.module')),
                ('project', models.ForeignKey(help_text='The project this calculation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.project')),
                ('emission_factor', models.ForeignKey(help_text='The emission factor applied for this calculation', on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
                ('reporting_period', models.ForeignKey(blank=True, help_text='The reporting period/cycle this calculation belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='emissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Emission Calculation',
                'verbose_name_plural': 'Emission Calculations',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='emissions_r_tenant__54a7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['status'], name='emissions_r_status_962227_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['project', 'scope', 'reporting_year'], name='emissions_c_project_f4484e_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['module', 'reporting_year'], name='emissions_c_module__6d3b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['category', 'reporting_year'], name='emissions_c_categor_e6fff5_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['reporting_period'], name='emissions_c_reporti_6a8caa_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['activity_date'], name='emissions_c_activit_b75063_idx'),
        ),
    ]
