# Generated by Django 5.2 on 2026-02-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0001_initial'),
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Keywords for smart matching with DataFields, e.g., ['electricity', 'grid', 'kwh']"),
        ),
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_selector_mapping', models.JSONField(blank=True, help_text="Mapping from field value to EmissionFactor code, e.g., {'USA': 'US_GRID_AVG'}", null=True)),
                ('rule_type', models.CharField(choices=[('direct', 'Direct Multiplication'), ('unit_convert', 'With Unit Conversion'), ('formula', 'Custom Formula')], default='direct', max_length=20)),
                ('unit_conversion_factor', models.DecimalField(decimal_places=10, default=1, help_text='Multiply activity value by this before applying emission factor', max_digits=20)),
                ('custom_formula', models.TextField(blank=True, help_text='Future: Python expression for complex calculations')),
                ('name', models.CharField(help_text='Descriptive name for this rule', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_calculate', models.BooleanField(default=True, help_text='Automatically calculate when data is saved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_field', models.ForeignKey(help_text='The field containing activity data (e.g., kWh, liters)', on_delete=django.db.models.deletion.CASCADE, related_name='calculation_rules_as_activity', to='dataschema.datafield')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_table', models.ForeignKey(help_text='The data table this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='calculation_rules', to='dataschema.datatable')),
                ('date_field', models.ForeignKey(blank=True, help_text='Optional: field containing the date of activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_rules_as_date', to='dataschema.datafield')),
                ('emission_factor', models.ForeignKey(help_text='The emission factor to apply', on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules', to='emissions.emissionfactor')),
                ('factor_selector_field', models.ForeignKey(blank=True, help_text='Optional: field that determines which emission factor to use', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_rules_as_selector', to='dataschema.datafield')),
                ('output_field', models.ForeignKey(blank=True, help_text='Optional: field to store calculated CO2e (if null, stored in Calculation model only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_rules_as_output', to='dataschema.datafield')),
            ],
            options={
                'verbose_name': 'Calculation Rule',
                'verbose_name_plural': 'Calculation Rules',
                'ordering': ['data_table', 'name'],
                'indexes': [models.Index(fields=['data_table', 'is_active'], name='emissions_c_data_ta_4a1847_idx')],
            },
        ),
    ]
