# Generated by Django 5.2.3 on 2026-07-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_unique_together_remove_project_tenant'),
        ('emissions', '0002_add_calculation_rule_and_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportingperiod',
            name='emissions_r_tenant__54a7a7_idx',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: specific project (if null, applies to all projects)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['project', 'start_date', 'end_date'], name='emissions_r_project_72c631_idx'),
        ),
    ]
