# Generated by Django 5.2.3 on 2026-07-03 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_unique_together_alter_feedback_options_and_more'),
        ('dataschema', '0002_datafield_reference_set'),
        ('emissions', '0003_remove_reportingperiod_emissions_r_tenant__54a7a7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calculation',
            name='emissions_c_project_f4484e_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportingperiod',
            name='emissions_r_project_72c631_idx',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='project',
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['module', 'scope', 'reporting_year'], name='emissions_c_module__59827c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='emissions_r_start_d_244558_idx'),
        ),
    ]
