# Generated by Django 5.2.3 on 2026-07-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_remove_calculation_emissions_c_project_f4484e_idx_and_more'),
        ('mdm', '0004_reference_set_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'FY 2026 Smart Village Annual Report'", max_length=200)),
                ('custom_start', models.DateField(blank=True, null=True)),
                ('custom_end', models.DateField(blank=True, null=True)),
                ('ghg_scopes', models.JSONField(default=list, help_text='List of GHG scope numbers to include, e.g., [1, 2, 3]. Empty = all.')),
                ('categories', models.JSONField(default=list, help_text='List of category codes to include. Empty = all.')),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10)),
                ('grouping', models.CharField(choices=[('scope', 'By GHG Scope'), ('category', 'By Category'), ('module', 'By Module'), ('month', 'By Month')], default='scope', max_length=20)),
                ('include_dq_status', models.BooleanField(default=True)),
                ('include_unverified', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_configs', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, help_text='Scope to this org_unit subtree (null = all accessible)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.orgunit')),
                ('reporting_period', models.ForeignKey(blank=True, help_text='If null, use custom_start / custom_end', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
