# Generated by Django 5.2.3 on 2026-07-29 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_reportconfig'),
        ('mdm', '0006_remove_referenceset_refset_active_domain_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Data Entry'), ('locked', 'Locked for Review'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SBTiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_year', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('target_type', models.CharField(choices=[('absolute', 'Absolute Reduction'), ('intensity', 'Intensity Reduction')], max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3'), ('1+2', 'Scope 1+2'), ('1+2+3', 'Scope 1+2+3')], max_length=20)),
                ('reduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbti_targets', to='mdm.orgunit')),
            ],
            options={
                'ordering': ['-base_year'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='emissions.reportingperiod')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporting_period', 'verifier')},
            },
        ),
    ]
