# Generated by Django 5.2.3 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0004_datatable_is_locked'),
        ('emissions', '0006_reportingperiod_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('single', 'Single Rule'), ('batch', 'Batch')], max_length=10)),
                ('table_ids', models.JSONField(blank=True, help_text='List of table IDs for batch runs', null=True)),
                ('recalculate', models.BooleanField(default=False)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_rule', models.ForeignKey(blank=True, help_text='Rule executed (null for batch)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.calculationrule')),
                ('data_table', models.ForeignKey(blank=True, help_text='DataTable targeted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataschema.datatable')),
                ('reporting_period', models.ForeignKey(blank=True, help_text='Reporting period for this run', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.reportingperiod')),
                ('triggered_by', models.ForeignKey(help_text='User who triggered this calculation run', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['-triggered_at'], name='emissions_c_trigger_dc4b39_idx'), models.Index(fields=['triggered_by', '-triggered_at'], name='emissions_c_trigger_428616_idx'), models.Index(fields=['reporting_period'], name='emissions_c_reporti_27560d_idx')],
            },
        ),
    ]
