# Generated by Django 5.2.3 on 2026-08-06 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_alter_exportaudit_exported_by'),
        ('mdm', '0006_remove_referenceset_refset_active_domain_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='emission_factor_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the emission factor values used at calculation time', null=True),
        ),
        migrations.AddField(
            model_name='calculation',
            name='factor_applied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the emission factor was applied', null=True),
        ),
        migrations.AddField(
            model_name='calculation',
            name='scope2_method',
            field=models.CharField(blank=True, choices=[('location_based', 'Location-Based'), ('market_based', 'Market-Based')], help_text='For Scope 2 calculations: which method produced this result', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='data_quality_tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — Default/IER factors'), (2, 'Tier 2 — Country-specific factors'), (3, 'Tier 3 — Facility-specific / direct measurement')], default=1, help_text='IPCC data quality tier for the activity data feeding this rule'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='scope2_calculation_method',
            field=models.CharField(choices=[('location_based', 'Location-Based'), ('market_based', 'Market-Based'), ('dual', 'Both (Location + Market)')], default='location_based', help_text='Scope 2 calculation method per GHG Protocol: location-based (grid avg), market-based (contractual), or both', max_length=20),
        ),
        migrations.CreateModel(
            name='BaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Base year (e.g., 2024)')),
                ('recalculation_policy', models.CharField(choices=[('significant_only', 'Recalculate only for significant changes'), ('all_changes', 'Recalculate for all structural changes'), ('never', 'Fixed base year — do not recalculate')], default='significant_only', help_text='Policy for when base year emissions should be recalculated', max_length=30)),
                ('significance_threshold_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Significance threshold (%) that triggers recalculation', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Rationale for base year selection')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.OneToOneField(help_text='Reporting period serving as the base year', on_delete=django.db.models.deletion.PROTECT, related_name='base_year', to='emissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Base Year',
                'verbose_name_plural': 'Base Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'AASTMT Equity Share Boundary'", max_length=200)),
                ('consolidation_approach', models.CharField(choices=[('equity_share', 'Equity Share'), ('financial_control', 'Financial Control'), ('operational_control', 'Operational Control')], default='operational_control', help_text='GHG Protocol consolidation approach', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Narrative description of entities/assets included/excluded')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boundaries', to=settings.AUTH_USER_MODEL)),
                ('included_org_units', models.ManyToManyField(blank=True, help_text='Org units within this boundary', related_name='organizational_boundaries', to='mdm.orgunit')),
            ],
            options={
                'verbose_name': 'Organizational Boundary',
                'verbose_name_plural': 'Organizational Boundaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='organizational_boundary',
            field=models.ForeignKey(blank=True, help_text='Organizational boundary for this reporting period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_periods', to='emissions.organizationalboundary'),
        ),
        migrations.CreateModel(
            name='RecalculationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('structural_change', 'Structural Change'), ('methodology_change', 'Methodology Change'), ('error_correction', 'Error Correction'), ('threshold_exceeded', 'Significance Threshold Exceeded')], max_length=30)),
                ('description', models.TextField(help_text='Description of the event that triggered recalculation')),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Measured variance from base year (%)', max_digits=5, null=True)),
                ('resolution_status', models.CharField(choices=[('open', 'Open — Requires Recalculation'), ('in_progress', 'In Progress'), ('recalculated', 'Recalculated'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('base_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalculation_triggers', to='emissions.baseyear')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recalculation Trigger',
                'verbose_name_plural': 'Recalculation Triggers',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='baseyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('year',), name='unique_active_base_year'),
        ),
        migrations.AddIndex(
            model_name='organizationalboundary',
            index=models.Index(fields=['consolidation_approach'], name='emissions_o_consoli_8cdb35_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalboundary',
            index=models.Index(fields=['is_active'], name='emissions_o_is_acti_859c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='recalculationtrigger',
            index=models.Index(fields=['base_year', 'resolution_status'], name='emissions_r_base_ye_b3ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='recalculationtrigger',
            index=models.Index(fields=['trigger_type'], name='emissions_r_trigger_f32e4b_idx'),
        ),
    ]
