# Generated by GitHub Copilot — BUG-02 fix: backfill Phase 2 GHG Protocol fields
# on legacy calculations (scope2_method, emission_factor_snapshot, factor_applied_at).
from django.db import migrations


def backfill_phase2_fields(apps, schema_editor):
    """Non-destructive backfill of Phase 2 fields for legacy Calculation rows.

    - scope2_method: default to 'location_based' for Scope 2 calcs (GHG Protocol
      location-based is the default method when no contractual data is used).
    - emission_factor_snapshot: mirror the currently-linked EmissionFactor into
      the same snapshot structure used by Calculation.create_from_data_row().
    - factor_applied_at: fall back to the calculation's calculated_at timestamp.
    """
    Calculation = apps.get_model('emissions', 'Calculation')

    calcs = (
        Calculation.objects
        .filter(emission_factor_snapshot__isnull=True)
        .select_related('emission_factor')
    )
    updated = 0
    for calc in calcs.iterator(chunk_size=500):
        ef = calc.emission_factor
        snapshot = {
            'factor_id': ef.id,
            'factor_code': ef.code,
            'factor_name': ef.name,
            'factor_value': str(ef.factor_value),
            'factor_unit': ef.factor_unit,
            'activity_unit': ef.activity_unit,
            'source': ef.source,
            'valid_from': str(ef.valid_from) if ef.valid_from else None,
            'valid_to': str(ef.valid_to) if ef.valid_to else None,
            'co2_factor': str(ef.co2_factor) if ef.co2_factor else None,
            'ch4_factor': str(ef.ch4_factor) if ef.ch4_factor else None,
            'n2o_factor': str(ef.n2o_factor) if ef.n2o_factor else None,
            'snapshot_at': calc.calculated_at.isoformat() if calc.calculated_at else None,
        }
        calc.emission_factor_snapshot = snapshot
        if calc.scope == 2 and not calc.scope2_method:
            calc.scope2_method = 'location_based'
        if calc.factor_applied_at is None:
            calc.factor_applied_at = calc.calculated_at
        calc.save(update_fields=[
            'emission_factor_snapshot', 'scope2_method', 'factor_applied_at',
        ])
        updated += 1
    return updated


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0011_phase2_ghg_protocol'),
    ]

    operations = [
        migrations.RunPython(backfill_phase2_fields, reverse_code=migrations.RunPython.noop),
    ]
