# Generated by Django 5.2.3 on 2026-08-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0012_datafield_masking_strategy'),
        ('emissions', '0012_phase2_backfill'),
        ('mdm', '0006_remove_referenceset_refset_active_domain_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('scope3_category', models.PositiveSmallIntegerField(blank=True, help_text='Scope 3 category 1-15; null for scope 1/2', null=True)),
                ('source_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sources_created', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sources', to='mdm.orgunit')),
            ],
            options={
                'verbose_name': 'Inventory Source',
                'verbose_name_plural': 'Inventory Sources',
                'ordering': ['scope', 'scope3_category', 'source_name'],
            },
        ),
        migrations.CreateModel(
            name='CoverageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('collect_data', 'Collect Data'), ('improve_quality', 'Improve Data Quality'), ('obtain_verification', 'Obtain Verification'), ('formalize_exclusion', 'Formalize Exclusion')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_actions_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_actions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='emissions.inventorysource')),
            ],
            options={
                'verbose_name': 'Coverage Action',
                'verbose_name_plural': 'Coverage Actions',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySourceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('covered', 'Covered'), ('excluded', 'Excluded')], default='declared', max_length=20)),
                ('data_quality_tier', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tier 1 — Audited'), (2, 'Tier 2 — Verified'), (3, 'Tier 3 — Calculated'), (4, 'Tier 4 — Estimated'), (5, 'Tier 5 — Proxy')], help_text='PCAF data quality score 1-5 (1=best)', null=True)),
                ('exclusion_reason', models.CharField(blank=True, choices=[('not_material', 'Not Material'), ('insufficient_data', 'Insufficient Data'), ('out_of_boundary', 'Outside Operational Boundary'), ('other', 'Other')], max_length=30, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_tables', models.ManyToManyField(blank=True, related_name='inventory_source_statuses', to='dataschema.datatable')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_source_statuses', to='emissions.reportingperiod')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='emissions.inventorysource')),
            ],
            options={
                'verbose_name': 'Inventory Source Status',
                'verbose_name_plural': 'Inventory Source Statuses',
                'ordering': ['reporting_period', 'source__scope', 'source__scope3_category'],
            },
        ),
        migrations.CreateModel(
            name='CoverageGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3'), ('1+2', 'Scope 1+2'), ('1+2+3', 'Scope 1+2+3')], max_length=20)),
                ('target_coverage_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_quality_tier', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tier 1 — Audited'), (2, 'Tier 2 — Verified'), (3, 'Tier 3 — Calculated'), (4, 'Tier 4 — Estimated'), (5, 'Tier 5 — Proxy')], help_text="Minimum PCAF tier for a source to count as 'covered'", null=True)),
                ('completeness_definition', models.CharField(choices=[('absolute', 'Absolute'), ('materiality_bounded', 'Materiality-Bounded')], default='materiality_bounded', max_length=30)),
                ('target_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_goals_created', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_goals', to='mdm.orgunit')),
                ('sbti_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_goals', to='emissions.sbtitarget')),
            ],
            options={
                'verbose_name': 'Coverage Goal',
                'verbose_name_plural': 'Coverage Goals',
                'ordering': ['-target_year', 'scope'],
                'indexes': [models.Index(fields=['org_unit', 'scope', 'status'], name='emissions_c_org_uni_9e683e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventorysource',
            index=models.Index(fields=['org_unit', 'scope', 'is_active'], name='emissions_i_org_uni_097092_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorysource',
            constraint=models.UniqueConstraint(fields=('org_unit', 'scope', 'scope3_category', 'source_name'), name='uniq_inventory_source_binding'),
        ),
        migrations.AddIndex(
            model_name='coverageaction',
            index=models.Index(fields=['source', 'status'], name='emissions_c_source__24ae3b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysourcestatus',
            index=models.Index(fields=['reporting_period', 'status'], name='emissions_i_reporti_a46629_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorysourcestatus',
            constraint=models.UniqueConstraint(fields=('source', 'reporting_period'), name='uniq_source_period_status'),
        ),
    ]
