# Generated by Django 5.2.3 on 2026-10-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_inventorysource_scope2_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurer_name', models.CharField(blank=True, default='', max_length=200)),
                ('engagement_type', models.CharField(blank=True, default='', max_length=20)),
                ('standard', models.CharField(blank=True, default='', max_length=40)),
                ('opinion_date', models.DateField(blank=True, null=True)),
                ('statement_id', models.CharField(blank=True, default='', max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurance_engagements', to='emissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Assurance engagement',
                'verbose_name_plural': 'Assurance engagements',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractualScope2Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('emission_factor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contractual_scope2', to='emissions.emissionfactor')),
                ('grid_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emissions.emissionfactor')),
            ],
            options={
                'verbose_name': 'Contractual Scope 2 factor',
                'verbose_name_plural': 'Contractual Scope 2 factors',
            },
        ),
    ]
