# Generated by Django 5.2.3 on 2026-10-02 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschema', '0012_datafield_masking_strategy'),
        ('emissions', '0015_campus_intake_factors'),
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3'), ('1+2', 'Scope 1+2'), ('1+2+3', 'Scope 1+2+3')], max_length=20)),
                ('scope3_category', models.PositiveSmallIntegerField(blank=True, help_text='Scope 3 category 1-15; null for scope 1/2', null=True)),
                ('name', models.CharField(max_length=200)),
                ('goal_kind', models.CharField(choices=[('percent', 'Percent of required streams'), ('absolute', 'Absolute')], default='percent', max_length=20)),
                ('goal_value', models.DecimalField(decimal_places=4, help_text='Percent (0-100) when goal_kind is percent; an amount when absolute', max_digits=14)),
                ('goal_unit', models.CharField(blank=True, default='', help_text='Unit for an absolute goal (kg, kWh, litre, tonne); blank for percent', max_length=40)),
                ('min_quality_tier', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tier 1 — Audited'), (2, 'Tier 2 — Verified'), (3, 'Tier 3 — Calculated'), (4, 'Tier 4 — Estimated'), (5, 'Tier 5 — Proxy')], help_text='Minimum PCAF tier for a stream to count toward this target', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_goal', models.ForeignKey(blank=True, help_text='Optional link to the policy CoverageGoal. A target never promotes it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='emissions.coveragegoal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_targets_created', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_targets', to='mdm.orgunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_targets_owned', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_targets', to='emissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Coverage Target',
                'verbose_name_plural': 'Coverage Targets',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('bind_data_product', 'Bind a Data Product contract'), ('complete_rows', 'Complete rows through a month'), ('fill_gap', 'Fill a named gap'), ('secure_factor', 'Secure a missing factor'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('through_month', models.DateField(blank=True, help_text='complete_rows: first day of the month rows must reach', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('data_table', models.ForeignKey(blank=True, help_text='bind_data_product / complete_rows evidence: the bound contract table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_tasks', to='dataschema.datatable')),
                ('factor', models.ForeignKey(blank=True, help_text='secure_factor evidence: the distinct factor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_tasks', to='emissions.emissionfactor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_tasks_owned', to=settings.AUTH_USER_MODEL)),
                ('stream_source', models.ForeignKey(blank=True, help_text='fill_gap / complete_rows evidence: the named stream', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_tasks', to='emissions.inventorysource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emissions.coveragetarget')),
            ],
            options={
                'verbose_name': 'Coverage Task',
                'verbose_name_plural': 'Coverage Tasks',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='coveragetarget',
            index=models.Index(fields=['reporting_period', 'status'], name='emissions_c_reporti_f69fba_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragetarget',
            index=models.Index(fields=['org_unit', 'scope'], name='emissions_c_org_uni_1e05ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='coveragetarget',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'org_unit', 'scope', 'scope3_category', 'name'), name='uniq_coverage_target_binding', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='coveragetarget',
            constraint=models.CheckConstraint(condition=models.Q(('goal_value__gte', 0)), name='coverage_target_goal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coveragetarget',
            constraint=models.CheckConstraint(condition=models.Q(('goal_kind', 'absolute'), ('goal_value__lte', 100), _connector='OR'), name='coverage_target_percent_lte_100'),
        ),
        migrations.AddIndex(
            model_name='coveragetask',
            index=models.Index(fields=['target', 'status'], name='emissions_c_target__61e027_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragetask',
            index=models.Index(fields=['target', 'task_type'], name='emissions_c_target__2d6d09_idx'),
        ),
    ]
