# Generated by Django 5.2.3 on 2026-10-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_coveragetarget_coveragetask_and_more'),
        ('mdm', '0007_orgunit_manager_employee_id_alter_orgunit_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragetarget',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="The campus (mdm.OrgUnit with org_type='campus') this target belongs to. org_unit stays the unit progress keys on; it is the campus or one of its real descendants. This field never replaces the progress key.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_target_campuses', to='mdm.orgunit'),
        ),
    ]
