# Generated by Django 5.2.3 on 2026-08-12 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('app_identifier', models.CharField(blank=True, help_text="Domain app scope (e.g. 'emissions'). None = platform-level.", max_length=50, null=True)),
                ('conversation_type', models.CharField(choices=[('chat', 'Chat'), ('dq_validate', 'DQ Validate'), ('dq_suggest', 'DQ Suggest'), ('nl_query', 'NL Query')], default='chat', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('needs_input', 'Needs Input'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scope_json', models.JSONField(blank=True, default=dict, help_text='Frozen copy of user Scope at conversation creation time (audit trail).')),
                ('task_payload_json', models.JSONField(blank=True, default=dict, help_text='Original task payload (rule_id, table_name, rows, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=15)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Optional: confidence, suggestions, follow_up_questions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
