# Generated by Django 5.2.3 on 2026-08-14 00:26

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auditlog_conversation_conversationcontextrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitionSweepRun',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('task_name', models.TextField(db_index=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.TextField(default='pending')),
                ('last_duration_ms', models.IntegerField(default=0)),
                ('run_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
