# Generated by Django 5.2.3 on 2026-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_cognitionsweeprun'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='correction_text',
            field=models.TextField(blank=True, default='', help_text="User's correction when outcome='corrected'."),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='outcome',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('corrected', 'Corrected'), ('ignored', 'Ignored')], default=None, help_text='User judgement on this AI message (learning signal).', max_length=20, null=True),
        ),
    ]
