# Generated by Django 5.2.3 on 2026-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aimessage_correction_text_aimessage_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='learned_at',
            field=models.DateTimeField(blank=True, default=None, help_text="Set once this message's outcome has been consumed by the learning job.", null=True),
        ),
    ]
