# Generated by Django 5.2.3 on 2026-08-16 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aimessage_learned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='context_snapshot_json',
            field=models.JSONField(blank=True, default=dict, help_text='Last-assembled context budget telemetry.'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Denormalized sort/group key from the latest AIMessage.', null=True),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Rolling compaction summary of older turns (written in Sprint 15).'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='parent_message_id',
            field=models.UUIDField(blank=True, default=None, help_text='Which message this edited/regenerated/replaced.', null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='provider_model',
            field=models.CharField(blank=True, default='', help_text='Model that answered (transparency).', max_length=64),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='token_usage_json',
            field=models.JSONField(blank=True, default=dict, help_text='Per-turn usage: model, prompt/completion/total tokens, cost, latency.'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'is_archived', 'is_pinned', '-last_message_at'], name='ai_conv_user_org_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'app_identifier'], name='ai_conv_user_app_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_msg_conv_time_idx'),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='ai.aiconversation'),
        ),
    ]
