# Generated by Django 5.2.3 on 2026-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aigeneration_aiconversation_context_snapshot_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='last_summarized_message_id',
            field=models.UUIDField(blank=True, default=None, help_text='Latest AIMessage id included when the rolling summary was last generated.', null=True),
        ),
    ]
