# Generated by Django 5.2.3 on 2026-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_aiartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the user last opened/resumed this conversation (drives the >24h resume catch-up summary).', null=True),
        ),
    ]
