# Generated by Django 5.2.3 on 2026-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_add_conversation_last_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='conversation_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('dq_validate', 'DQ Validate'), ('dq_suggest', 'DQ Suggest'), ('nl_query', 'NL Query'), ('anomaly', 'Anomaly'), ('investigate', 'Investigate'), ('nl_rule_test', 'NL Rule Test'), ('report_draft', 'Report Draft')], default='chat', max_length=30),
        ),
    ]
