# Generated by Django 5.2.3 on 2026-08-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_aiconversation_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='context_signature',
            field=models.CharField(blank=True, default='', help_text='Opaque hash of the context window (message-id vector + model + profile) at generation time. Never stores message text.', max_length=64),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. Deleted messages are excluded from context assembly but rendered dimmed in the thread.'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='User turn this reply answers (thread structure for delete-descendants).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ai.aimessage'),
        ),
    ]
