# Generated by Django 5.2.3 on 2026-08-18 10:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_aimessage_context_signature_aimessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='Stable slug. Never changes across version bumps — historical usage attribution resolves against this id.', max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='User-facing one-liner shown in the model picker.')),
                ('tier', models.CharField(choices=[('fast', 'Fast'), ('balanced', 'Balanced'), ('brain', 'Brain')], default='balanced', help_text='User-facing bucket: fast (cheap) / balanced / brain (smart, expensive).', max_length=20)),
                ('version', models.CharField(blank=True, default='', help_text='Concrete provider version (server-side only; never exposed as raw routing).', max_length=64)),
                ('context_window', models.PositiveIntegerField(default=128000, help_text='Maximum context window in tokens.')),
                ('input_cost_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='USD cost per 1M input tokens (single source of truth for pricing).', max_digits=10)),
                ('output_cost_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='USD cost per 1M output tokens (single source of truth for pricing).', max_digits=10)),
                ('deprecated', models.BooleanField(default=False, help_text='Retired models stay in the catalog for attribution but are hidden from new selection in the UI.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='User-facing capability flags (e.g. vision, function_calling). Never raw provider routing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, default=None, help_text='Replacement model (retirement path).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='ai.modelcatalog')),
            ],
            options={
                'verbose_name': 'Model Catalog',
                'verbose_name_plural': 'Model Catalog',
                'ordering': ['deprecated', 'input_cost_per_1m', 'model_id'],
                'indexes': [models.Index(fields=['tier', 'deprecated'], name='ai_mcat_tier_dep_idx')],
            },
        ),
    ]
