# Generated by Django 5.2.3 on 2026-08-18 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_seed_model_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_token_limit', models.BigIntegerField(default=1000000, help_text='Monthly token budget (soft warning at 80%, hard stop at 100%).')),
                ('quota_reset_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-28) the monthly token quota resets.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI User Profile',
                'verbose_name_plural': 'AI User Profiles',
            },
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Set once at completion; the aggregation window key (period).', null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='USD cost computed from ModelCatalog rates (never ad hoc).', max_digits=12),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='model_id',
            field=models.CharField(blank=True, default='', help_text='Stable ModelCatalog.model_id slug (usage attribution).', max_length=64),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='aigeneration',
            index=models.Index(fields=['conversation', 'status', 'completed_at'], name='ai_gen_conv_status_done_idx'),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
