# Generated by Django 5.2.3 on 2026-08-18 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_aiuserprofile_aigeneration_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuserprofile',
            name='auto_title',
            field=models.BooleanField(default=True, help_text='Auto-title conversations from the first user message.'),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='default_model_id',
            field=models.ForeignKey(blank=True, help_text='Durable per-user default model (Phase 20-A catalog FK). Resolved AFTER the domain manifest default and BEFORE any per-message override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.modelcatalog'),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='memory_enabled',
            field=models.BooleanField(default=True, help_text="Inject the user's long-term memory tier (T4) into turns."),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='temperature',
            field=models.FloatField(default=0.3, help_text='Default chat sampling temperature (0.0-2.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='usage_alert_threshold',
            field=models.PositiveSmallIntegerField(default=80, help_text='Soft-warning percent of the monthly token limit (1-100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
