# Generated by Django 5.2.3 on 2026-08-19 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_aiuserprofile_auto_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-chosen checkpoint name (unique per conversation).', max_length=120)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note about this checkpoint.')),
                ('snapshot_json', models.JSONField(blank=True, default=dict, help_text='The assembled context bundle: {messages, budget, kg_entities, context_signature, summary, message_boundary_id}.')),
                ('message_boundary_id', models.UUIDField(blank=True, default=None, help_text='AIMessage id at the checkpoint boundary (fork seeds up to and including this message).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='ai.aiconversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation Checkpoint',
                'verbose_name_plural': 'AI Conversation Checkpoints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='ai_checkpoint_conv_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'name'), name='ai_checkpoint_conv_name_uniq')],
            },
        ),
    ]
