# Generated by Django 5.2.3 on 2026-08-21 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_conversationcheckpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DqFeedbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('suggest_accepted', 'Suggestion Accepted'), ('suggest_rejected', 'Suggestion Rejected'), ('rule_corrected', 'Rule Corrected'), ('result_always_pass', 'Result Always-Pass'), ('result_false_positive', 'Result False-Positive'), ('drift_detected', 'Drift Detected')], max_length=24)),
                ('signal_type', models.CharField(help_text='Engine signal taxonomy: explicit_positive | explicit_negative | correction | retire_candidate | drift', max_length=20)),
                ('quality_score', models.FloatField(default=0.7)),
                ('source', models.CharField(choices=[('suggest', 'Suggest'), ('nl_check', 'NL Check'), ('result', 'DQ Result'), ('drift', 'Drift')], max_length=16)),
                ('suggestion_id', models.BigIntegerField(blank=True, null=True)),
                ('rule_id', models.BigIntegerField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, default='', max_length=255)),
                ('table_id', models.BigIntegerField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, default='', max_length=255)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_id', models.CharField(blank=True, default='', help_text='AIMessage uuid (str) when the signal originates in the AI workspace.', max_length=64)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full context: suggestion definition, rule params, result stats, drift details.')),
                ('correction_text', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('effect', models.JSONField(blank=True, default=dict)),
                ('revert_payload', models.JSONField(blank=True, default=dict)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DQ Feedback Event',
                'verbose_name_plural': 'DQ Feedback Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'applied_at'], name='ai_dqfeedba_event_t_7b7875_idx'), models.Index(fields=['rule_id', 'applied_at'], name='ai_dqfeedba_rule_id_a5ff33_idx'), models.Index(fields=['table_id', 'applied_at'], name='ai_dqfeedba_table_i_be0de6_idx')],
            },
        ),
    ]
