# Generated by Django 5.2.3 on 2026-08-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_plan_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='ai_artifacts/%Y/%m/')),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai.run')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
