# Generated by Django 5.2.3 — W6-E F-29: RunSchedule model.

import django.db.models.deletion
from django.db import migrations, models

import ai.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0020_runartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunSchedule",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        default=ai.models.base.generate_uuid,
                    ),
                ),
                ("instance_id", models.TextField(db_index=True)),
                (
                    "host_user_id",
                    models.CharField(
                        max_length=255, null=True, blank=True, db_index=True
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(null=True, blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="ai.plantemplate",
                    ),
                ),
                ("plan_json", models.JSONField(null=True, blank=True)),
                ("cron_expr", models.TextField(null=True, blank=True)),
                ("run_at", models.DateTimeField(null=True, blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(null=True, blank=True)),
                ("next_run_at", models.DateTimeField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["next_run_at"],
            },
        ),
    ]
