# Generated by Django 5.2.3 on 2026-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0022_acceptancereport_learningoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorylongterm',
            name='memory_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
