# Generated by Django 5.2.3 on 2026-09-03 12:31

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0024_anomaly_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISubagent',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('parent_conversation_id', models.TextField(db_index=True)),
                ('name', models.TextField()),
                ('brief', models.TextField()),
                ('scope_restriction', models.JSONField(blank=True, null=True)),
                ('tool_budget', models.IntegerField(blank=True, null=True)),
                ('tool_allowlist_json', models.JSONField(blank=True, null=True)),
                ('is_worker', models.BooleanField(default=True)),
                ('status', models.TextField(default='pending')),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('result_detail', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
