# Generated by Django 5.2.3 on 2026-09-05 13:04

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0025_aisubagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkObjective',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('instance_id', models.TextField(db_index=True)),
                ('conversation_id', models.TextField(db_index=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_user', 'Waiting for User'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('latest_run_id', models.TextField(blank=True, null=True)),
                ('latest_summary', models.TextField(blank=True, default='')),
                ('pending_question', models.TextField(blank=True, default='')),
                ('evidence_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['instance_id', 'host_user_id', 'status'], name='ai_workobje_instanc_94c1cc_idx')],
            },
        ),
    ]
