# Generated by Django 5.2.3 on 2026-09-05 13:10

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0026_add_workobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('instance_id', models.TextField(db_index=True)),
                ('conversation_id', models.TextField(db_index=True)),
                ('turn_id', models.TextField(db_index=True)),
                ('objective_id', models.TextField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('carbon_api', 'Carbon Platform API'), ('web_search', 'Web Search'), ('knowledge_graph', 'Knowledge Graph'), ('memory', 'Agent Memory')], max_length=30)),
                ('source_identifier', models.TextField()),
                ('query_description', models.TextField()),
                ('content_json', models.JSONField()),
                ('coverage', models.CharField(choices=[('complete', 'Complete for scope'), ('partial', 'Partial'), ('sampled', 'Sampled'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('limitations', models.TextField(blank=True, default='')),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-retrieved_at'],
                'indexes': [models.Index(fields=['instance_id', 'conversation_id', 'turn_id'], name='ai_evidence_instanc_02a7cb_idx'), models.Index(fields=['objective_id'], name='ai_evidence_objecti_8a6eca_idx')],
            },
        ),
    ]
