# Generated by Django 5.2.3 on 2026-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0028_skill_gate_status_default_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuserprofile',
            name='pref_depth',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('normal', 'Normal'), ('expert', 'Expert')], default='normal', help_text='Durable response depth preference (GAP-4).', max_length=16),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='pref_format',
            field=models.CharField(choices=[('bullets', 'Bullets'), ('prose', 'Prose'), ('mixed', 'Mixed')], default='mixed', help_text='Durable response format preference (GAP-4).', max_length=16),
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='pref_verbosity',
            field=models.CharField(choices=[('brief', 'Brief'), ('normal', 'Normal'), ('verbose', 'Verbose')], default='normal', help_text='Durable communication verbosity preference (GAP-4).', max_length=16),
        ),
    ]
