# Generated by Django 5.2.3 on 2026-09-13 00:10

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0029_aiuserprofile_pref_depth_aiuserprofile_pref_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDecisionRow',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('principal', models.TextField(db_index=True)),
                ('action', models.TextField(db_index=True)),
                ('resource_objects', models.JSONField(default=list)),
                ('decision', models.TextField(db_index=True)),
                ('reason', models.TextField(default='')),
                ('policy_version', models.TextField(default='')),
                ('autonomy', models.TextField(default='human_only')),
                ('process_state', models.JSONField(blank=True, null=True)),
                ('budget', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
