# Generated by Django 5.2.3 on 2026-09-13 22:01

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0039_runjournalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTask',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('run_id', models.TextField(blank=True, db_index=True, default='')),
                ('step_id', models.TextField(blank=True, default='')),
                ('process_instance', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('capability', models.TextField(db_index=True, default='')),
                ('process_version', models.TextField(default='')),
                ('capability_version', models.TextField(default='')),
                ('canonical_args', models.JSONField(default=dict)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('effect_limits', models.JSONField(default=dict)),
                ('consequence', models.TextField()),
                ('objects_revisions_json', models.JSONField(default=dict)),
                ('before_json', models.JSONField(default=dict)),
                ('after_json', models.JSONField(default=dict)),
                ('evidence_json', models.JSONField(default=dict)),
                ('evidence_digest', models.TextField(default='')),
                ('reversibility', models.TextField()),
                ('required_authority', models.TextField(db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('alternatives_json', models.JSONField(default=list)),
                ('status', models.TextField(db_index=True, default='pending')),
                ('grant_id', models.TextField(blank=True, db_index=True, null=True)),
                ('decided_by', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='ai_humantask_inbox_idx'), models.Index(fields=['required_authority', 'status'], name='ai_humantask_authority_idx')],
            },
        ),
    ]
