# Generated by Django 5.2.3 on 2026-09-13 23:25

import ai.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0040_humantask'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('app_identifier', models.CharField(db_index=True, default='carbon', max_length=64)),
                ('org_unit_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('host_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('id', models.CharField(default=ai.models.base.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('knowledge_class', models.CharField(choices=[('policy', 'Policy'), ('process_definition', 'Process definition'), ('business_fact', 'Business fact'), ('procedural_heuristic', 'Procedural heuristic'), ('episodic_observation', 'Episodic observation'), ('user_preference', 'User preference')], db_index=True, max_length=32)),
                ('source', models.CharField(max_length=255)),
                ('owner_id', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.JSONField(default=dict)),
                ('version', models.CharField(default='1', max_length=64)),
                ('effective_start', models.DateTimeField(blank=True, null=True)),
                ('effective_end', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('deprecated', 'Deprecated'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=16)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=16)),
                ('supersedes_id', models.CharField(blank=True, default='', max_length=36)),
                ('content', models.TextField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['knowledge_class', 'review_status'], name='ai_ki_class_status_idx'), models.Index(fields=['knowledge_class', 'effective_end'], name='ai_ki_class_effend_idx')],
            },
        ),
    ]
