# Generated by Django 5.2.3 on 2026-09-15 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0041_knowledgeitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseHeartbeat",
            fields=[
                ("app_identifier", models.CharField(db_index=True, default="carbon", max_length=64)),
                ("org_unit_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("host_user_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("visibility", models.CharField(default="private", max_length=16)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("instance_id", models.TextField(db_index=True)),
                ("loop", models.CharField(db_index=True, max_length=32)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, max_length=16)),
                ("items_produced", models.IntegerField(default=0)),
                ("llm_calls", models.IntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "app_label": "ai",
            },
        ),
    ]
