# Generated by Django 5.2.3 on 2026-07-18 20:24

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataschema', '0002_datafield_reference_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Evidence file (PDF, image, Excel, etc.)', upload_to=evidence.models.evidence_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by user', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='application/octet-stream', help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when file was uploaded')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag (preserve audit trail)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when file was deleted (soft delete)', null=True)),
                ('data_row', models.ForeignKey(help_text='The data row this evidence is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='dataschema.datarow')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['data_row', '-uploaded_at'], name='evidence_ev_data_ro_d42f59_idx'), models.Index(fields=['is_deleted'], name='evidence_ev_is_dele_e79a98_idx'), models.Index(fields=['uploaded_by'], name='evidence_ev_uploade_5c664a_idx')],
            },
        ),
    ]
