# Generated by hand for Phase P1C — remove the adopted models from datahub's
# app state. The tables were renamed to catalog_* by catalog.0007's
# database_operations; this migration only deletes the models from datahub's
# state so the app ends up with zero models. Nothing is dropped from the DB.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_dataset_steward_datasetversionmember'),
        ('turnkey', '0002_alter_turnkeymodellink_dataset_version'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Dataset'),
                migrations.DeleteModel(name='DatasetVersion'),
                migrations.DeleteModel(name='DatasetVersionMember'),
                migrations.DeleteModel(name='DataContract'),
                migrations.DeleteModel(name='DataContractViolation'),
                migrations.DeleteModel(name='DatasetAccessPolicy'),
            ],
            database_operations=[],
        ),
    ]
