# File: people/urls.py
# People & Payroll API routes (NIR-1C). The ``/carbon-api/people/`` prefix is
# applied by ``config/urls.py``; these paths are relative to that prefix.

from django.urls import path

from .views import (
    AttendancePermissionDetailView,
    AttendancePermissionListCreateView,
    AttendanceRecordDetailView,
    AttendanceRecordListCreateView,
    BenefitTypeDetailView,
    BenefitTypeListCreateView,
    CertificationDetailView,
    CertificationListCreateView,
    ComplianceRuleDetailView,
    ComplianceRuleListCreateView,
    EmployeeBenefitDetailView,
    EmployeeBenefitListCreateView,
    EmployeeCompensationView,
    EmployeeDeactivateView,
    EmployeeDetailView,
    EmployeeListCreateView,
    EmployeeEOSIView,
    EmployeeReactivateView,
    EmployeeTimelineView,
    LeaveEntitlementDetailView,
    LeaveEntitlementListCreateView,
    LeaveRecordDetailView,
    LeaveRecordListCreateView,
    LoanDetailView,
    LoanInstallmentDetailView,
    LoanInstallmentListCreateView,
    LoanListCreateView,
    OrgUnitTimelineView,
    PayrollRunCommitView,
    PayrollRunComputeView,
    PayrollRunDetailView,
    PayrollRunListCreateView,
    PayrollRunValidateView,
    PayrollRunValidationsListView,
    PayrollRunWPSExportView,
    PayslipLineListView,
    PersonnelEventListView,
    PositionDetailView,
    PositionListCreateView,
    PositionTimelineView,
    RotationScheduleDetailView,
    RotationScheduleListCreateView,
)

urlpatterns = [
    path('compliance-rules/', ComplianceRuleListCreateView.as_view(),
         name='people-compliance-rules'),
    path('compliance-rules/<int:pk>/', ComplianceRuleDetailView.as_view(),
         name='people-compliance-rule-detail'),
    path('employees/', EmployeeListCreateView.as_view(), name='people-employees'),
    path('employees/<int:pk>/', EmployeeDetailView.as_view(),
         name='people-employee-detail'),
    path('employees/<int:pk>/eosi/', EmployeeEOSIView.as_view(),
         name='people-employee-eosi'),
    path('employees/<int:pk>/compensation/', EmployeeCompensationView.as_view(),
         name='people-employee-compensation'),
    path('employees/<int:pk>/deactivate/', EmployeeDeactivateView.as_view(),
         name='people-employee-deactivate'),
    path('employees/<int:pk>/reactivate/', EmployeeReactivateView.as_view(),
         name='people-employee-reactivate'),
    path('payroll-runs/', PayrollRunListCreateView.as_view(),
         name='people-payroll-runs'),
    path('payroll-runs/<int:pk>/', PayrollRunDetailView.as_view(),
         name='people-payroll-run-detail'),
    path('payslip-lines/', PayslipLineListView.as_view(),
         name='people-payslip-lines'),
    path('positions/', PositionListCreateView.as_view(),
         name='people-positions'),
    path('positions/<int:pk>/', PositionDetailView.as_view(),
         name='people-position-detail'),
    path('leave-entitlements/', LeaveEntitlementListCreateView.as_view(),
         name='people-leave-entitlements'),
    path('leave-entitlements/<int:pk>/', LeaveEntitlementDetailView.as_view(),
         name='people-leave-entitlement-detail'),
    path('leave-records/', LeaveRecordListCreateView.as_view(),
         name='people-leave-records'),
    path('leave-records/<int:pk>/', LeaveRecordDetailView.as_view(),
         name='people-leave-record-detail'),
    path('benefit-types/', BenefitTypeListCreateView.as_view(),
         name='people-benefit-types'),
    path('benefit-types/<int:pk>/', BenefitTypeDetailView.as_view(),
         name='people-benefit-type-detail'),
    path('benefits/', EmployeeBenefitListCreateView.as_view(),
         name='people-benefits'),
    path('benefits/<int:pk>/', EmployeeBenefitDetailView.as_view(),
         name='people-benefit-detail'),
    path('loans/', LoanListCreateView.as_view(),
         name='people-loans'),
    path('loans/<int:pk>/', LoanDetailView.as_view(),
         name='people-loan-detail'),
    path('loan-installments/', LoanInstallmentListCreateView.as_view(),
         name='people-loan-installments'),
    path('loan-installments/<int:pk>/', LoanInstallmentDetailView.as_view(),
         name='people-loan-installment-detail'),
    path('attendance/', AttendanceRecordListCreateView.as_view(),
         name='people-attendance'),
    path('attendance/<int:pk>/', AttendanceRecordDetailView.as_view(),
         name='people-attendance-detail'),
    path('attendance-permissions/', AttendancePermissionListCreateView.as_view(),
         name='people-attendance-permissions'),
    path('attendance-permissions/<int:pk>/',
         AttendancePermissionDetailView.as_view(),
         name='people-attendance-permission-detail'),
    path('certifications/', CertificationListCreateView.as_view(),
         name='people-certifications'),
    path('certifications/<int:pk>/', CertificationDetailView.as_view(),
         name='people-certification-detail'),
    path('rotation-schedules/', RotationScheduleListCreateView.as_view(),
         name='people-rotation-schedules'),
    path('rotation-schedules/<int:pk>/', RotationScheduleDetailView.as_view(),
         name='people-rotation-schedule-detail'),
    path('payroll-runs/<int:pk>/compute/', PayrollRunComputeView.as_view(),
         name='people-payroll-run-compute'),
    path('payroll-runs/<int:pk>/validate/', PayrollRunValidateView.as_view(),
         name='people-payroll-run-validate'),
    path('payroll-runs/<int:pk>/commit/', PayrollRunCommitView.as_view(),
         name='people-payroll-run-commit'),
    path('payroll-runs/<int:pk>/validations/',
         PayrollRunValidationsListView.as_view(),
         name='people-payroll-run-validations'),
    path('payroll-runs/<int:pk>/wps/', PayrollRunWPSExportView.as_view(),
         name='people-payroll-run-wps'),
    path('employees/<int:pk>/timeline/', EmployeeTimelineView.as_view(),
         name='people-employee-timeline'),
    path('positions/<int:pk>/timeline/', PositionTimelineView.as_view(),
         name='people-position-timeline'),
    path('org-units/<int:pk>/timeline/', OrgUnitTimelineView.as_view(),
         name='people-orgunit-timeline'),
    path('events/', PersonnelEventListView.as_view(),
         name='people-events'),
]
