# Generated by Django 5.2.3 on 2026-08-18 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('entry_route', models.CharField(blank=True, help_text='Frontend React router path e.g. /apps/healthy', max_length=200)),
                ('required_modules', models.JSONField(default=list)),
                ('required_capabilities', models.JSONField(default=list)),
                ('consumed_datasets', models.JSONField(default=list, help_text='Dataset.slug values this app reads (informational).')),
                ('is_system', models.BooleanField(default=False, help_text='System apps (emissions) cannot be deactivated.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_apps', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_apps', to=settings.AUTH_USER_MODEL)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='appregistry.appmanifest')),
            ],
        ),
    ]
