# Generated by Django 5.2.3 — Healthy Foods Factory (Phase P4-A)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_view', models.CharField(max_length=200)),
                ('extract_params', models.JSONField(blank=True, default=dict)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('dataset_version_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_snapshots', to='connections.datasource')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthy_erp_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadoutSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('rep_code', models.CharField(max_length=64)),
                ('rep_name', models.CharField(blank=True, max_length=200)),
                ('prediction_ref', models.UUIDField(blank=True, null=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthy_loadout_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'rep_code'],
                'unique_together': {('week_start', 'rep_code')},
            },
        ),
        migrations.CreateModel(
            name='RepHealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('rep_code', models.CharField(max_length=64)),
                ('churn_probability', models.FloatField(blank=True, null=True)),
                ('active_customer_count', models.IntegerField(blank=True, null=True)),
                ('visit_coverage', models.FloatField(blank=True, null=True)),
                ('avg_order_value', models.FloatField(blank=True, null=True)),
                ('ar_overdue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prediction_ref', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start', 'rep_code'],
                'unique_together': {('week_start', 'rep_code')},
            },
        ),
    ]
