# Generated by Django 5.2.3 on 2026-07-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_copilot', '0002_add_token_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationmessage',
            name='ai_copilot__project_27b666_idx',
        ),
        migrations.RemoveIndex(
            model_name='proactiveinsight',
            name='ai_copilot__project_243753_idx',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='proactiveinsight',
            name='project',
        ),
    ]
