# Generated by Django 5.2.3 on 2026-07-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_scope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='tenant',
        ),
    ]
