# Generated by Django 5.2.3 on 2026-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_unique_together_remove_project_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Feedback'},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='module',
            name='project',
        ),
    ]
