# Generated by Django 5.2.3 on 2026-07-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_roleassignmentauditlog_project_and_more'),
        ('ai_copilot', '0003_remove_conversationmessage_ai_copilot__project_27b666_idx_and_more'),
        ('core', '0005_alter_project_unique_together_alter_feedback_options_and_more'),
        ('emissions', '0004_remove_calculation_emissions_c_project_f4484e_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
