# Generated by Django 5.2.3 on 2026-07-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_project'),
        ('mdm', '0003_alter_orgunit_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='mdm.orgunit'),
        ),
    ]
