# Generated by Django 5.2.3 on 2026-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When locked, prevents accidental deletion or modification (admin override available)'),
        ),
    ]
