# Generated by Django 5.2.3 on 2026-08-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_module_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='e.g. submitted, verified, rejected, batch_complete', max_length=50)),
                ('message', models.TextField(help_text='Human-readable notification body')),
                ('link', models.CharField(blank=True, default='', help_text='Optional URL to related resource', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx')],
            },
        ),
    ]
