# Generated by Django 5.2.3 on 2026-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], db_index=True, default='INFO', max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('user', models.CharField(blank=True, default='anonymous', max_length=150)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('slow_request', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', '-timestamp'], name='core_reques_level_6247df_idx'), models.Index(fields=['status_code', '-timestamp'], name='core_reques_status__b56483_idx')],
            },
        ),
    ]
