# Generated by Django 5.2.3 on 2026-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_module_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='domain_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Per-domain-app metadata keyed by app_id (e.g. {"carbon": {"scope": 1}}).'),
        ),
    ]
