# Generated by Django 5.2.3 on 2026-08-26 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_domain_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_reques_user_id_778055_idx'), models.Index(fields=['path', 'timestamp'], name='core_reques_path_852ff7_idx')],
            },
        ),
    ]
